### PR TITLE
fixed issue 15639 - allocator.make enables abstract class instantiation

### PR DESCRIPTION
**Pull request by BBasile**

### CODE REVIEW

**Comment by BBasile** [comment]
Changelog:  `$(LI $(BUGZILLA 15639): it was possible instantiate an abstract class with experimental allocators.make`

**Comment by JackStouffer** [comment]
LGTM

**Comment by schveiguy** [comment]
> Changelog

Please put changelog entries into changelog.dd in phobos root directory. These will be merged and put into main changelog on release.

**Comment by BBasile** [comment]
Ok actually I was not sure of the way to do but so far not merged so I'll wait.

**Comment by MetaLang** [comment]
@schveiguy Can you take a look at https://github.com/D-Programming-Language/phobos/pull/4022 as well?

**Comment by BBasile** [comment]
@schveiguy updated #4023, Is it like that that changelog should be updated ?

**Comment by schveiguy** [comment]
Oh, I apologize completely! I saw your message comment about the changelog, and not thinking, I assumed you expected that that comment to be included somehow in the changelog. I'm honestly doing more harm than good today :(

changelog.dd is for changes that need further explanation (e.g. new features or behavior changes). Bug fixes will automatically be included as long as there is a bugzilla issue that is fixed during the release cycle (@MartinNowak I believe has a script to do that). I realize now, this (and the other update) are bugs that have corresponding bugzilla entries. So the changelog.dd update is not necessary (I think). I don't know if it's helpful to have them listed there, as @MartinNowak is the one to update the change log.

So sorry to waste your time with that! I will shut up now...

**Comment by BBasile** [comment]
#4023 Ready as well, even if only one GTM.

**Comment by BBasile** [comment]
plz, this is just a bug fix. can you have a look before next time greenify polute the PR stack.

**Comment by schveiguy** [comment]
LGTM

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Comment by schuetzm** [comment]
Stupid question - this seems the wrong place to fix the problem... Shouldn't `emplace()` itself be changed to reject abstract classes?

**Comment by BBasile** [comment]
Yes It's also allowed.

**Comment by BBasile** [comment]
A BR must be created so that it'll be referenced in the changelog, but actually since emplace() is an old function there's a risk, even if very small, of breakage.

**Comment by BBasile** [comment]
fix proposed in #4057

**Pull request merged**
