### PR TITLE
Remove dead insert() comment

### PR DESCRIPTION
**Pull request by dsp**
The comment about insert() is from 2011. insert() is long gone and insertInPlace
is the standard. No need to keep the old commented-out function around.

### CODE REVIEW

**Comment by yebblies** [comment]
This is meant to be the new code, and can be uncommented now that the old insert has been renamed.  But yeah, we should either uncomment it or delete it.

**Comment by dsp** [comment]
I guess then let's pick a side, this pull requests deletes it, so if we want to go for the delete way then we just pull it in.

**Comment by yebblies** [comment]
Meh let's just kill it we can always add it back later.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Pull request merged**
