### PR TITLE
std.string.stripRight_string_alias_fix

### PR DESCRIPTION
**Pull request by burner**
make stripRight accept custom types with alias this to string
member(functions)

### CODE REVIEW

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by burner** [comment]
thanks

**Comment by MartinNowak** [comment]
We need to consistently check and fix all the rangified functions, can you please help us with that.
http://dlang.org/changelog/2.068.0.html#rangified-functions
http://dlang.org/changelog/2.069.0.html#more-rangified-functions

**Comment by burner** [comment]
I'm already working on it, see:

https://github.com/D-Programming-Language/phobos/pull/3705

**Pull request merged**
