### PR TITLE
Cent-ify std.traits.

### PR DESCRIPTION
**Pull request by redstar**
Adds traits support for cent/ucent if supported.

### CODE REVIEW

**Comment by redstar** [comment]
This was a good hint. The diff is now much smaller. I also used `is(ucdent)´ as suggested by @yebblies.

**Comment by redstar** [comment]
Ok, I checked `is(ucent)` with the wrong compiler. It does not work.

**Comment by redstar** [comment]
`is(ucent)` results in the error: `cent and ucent types not implemented` :-)

**Comment by yebblies** [comment]
> is(ucent) results in the error: cent and ucent types not implemented :-)

With which compiler?

**Comment by redstar** [comment]
@yebblies dmd master.

**Comment by yebblies** [comment]
I'm not seeing that error with dmd master.  eg
```d
void main()
{
    static if (is(cent))
    {
        cent x = 3;
    }
    static if (is(ucent))
    {
        ucent x = 3;
    }
}
```
Can you show me an example that errors for you?

**Comment by redstar** [comment]
I did not pay enough attention to the faulty line. Here is an example:

    import std.typetuple;
    
    static if (__traits(compiles, is(ucent)))
    {
        alias TypeList = TypeTuple!(ucent);
    }
    else
    {
        alias TypeList = TypeTuple!();
    }

The error is in line 5 which means that `is(ucent)` compiles but does not work as intended.

**Comment by yebblies** [comment]
The mistake is checking that `is(cent)` compiles instead of checking that it's true.
It should be:
```d
import std.typetuple;

static if (is(ucent))
{
    alias TypeList = TypeTuple!(ucent);
}
else
{
    alias TypeList = TypeTuple!();
}
```

**Comment by redstar** [comment]
I see. This simplifies the implementation a lot.

**Comment by yebblies** [comment]
Excellent.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by Orvid** [comment]
It would be nice if we could use `cent` and `ucent` as types, but not values. It would make it so that there is no need for the extra code to check if they are supported when doing introspection like this.

**Pull request merged**
