### PR TITLE
Mark RBTree.length as const

### PR DESCRIPTION
**Pull request by rsw0x**
[Issue 14234](https://issues.dlang.org/show_bug.cgi?id=14234)

### CODE REVIEW

**Comment by JakobOvrum** [comment]
An accompanying unit test would help enforce the commitment. Otherwise LGTM.

**Comment by schuetzm** [comment]
Great! Can you squash the two commits? I think it's fine then.

**Comment by schveiguy** [comment]
Thanks for doing this. I should have done it, sorry.

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Comment by schveiguy** [comment]
@rsw0x Just FYI, please name your Pull Request something with "Fix issue 14234" in the title and the git commit hook will automatically reference the commit in bugzilla, and probably automatically close the issue. Thanks for doing this again!

**Pull request merged**
