### PR TITLE
std.digest.sha remove static constructor

### PR DESCRIPTION
**Pull request by WalterBright**
Makes branch prediction work better this way, rather than indirection. Double plus good!

Requires https://github.com/D-Programming-Language/druntime/pull/1311

### CODE REVIEW

**Comment by schveiguy** [comment]
Doesn't this get rid of the cache though? I didn't write the code, but I did refactor it recently so the static ctor for the cache moved outside the template. I assumed there was a good reason for caching that bit.

**Comment by schveiguy** [comment]
Nevermind, I see the required change puts the cache in druntime. Nice.

**Comment by WalterBright** [comment]
Yeah, druntime's cupid already has a static constructor that'll do the job. No need to repeat it.

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Pull request merged**
