### PR TITLE
Remove implicit conversions from array to bool

### PR DESCRIPTION
**Pull request by yebblies**
In preparation for the warning in https://github.com/D-Programming-Language/dmd/pull/2885

### CODE REVIEW

**Comment by monarchdodra** [comment]
LGTM. Doesn't style mandate we use `if (arr is null)`/`if (arr !is null)` though?

**Comment by yebblies** [comment]
I don't really feel strongly either way.  Do you want me to change it?

**Comment by yebblies** [comment]
If you're referring to comparing class handles with `null` using `==`, that is disallowed because of overloading problems, and overloading is not possible with arrays.

**Comment by yebblies** [comment]
Thanks!

**Pull request merged**
