### PR TITLE
Forward std.math intrinsics to core.math

### PR DESCRIPTION
**Pull request by yebblies**

### CODE REVIEW

**Comment by yebblies** [comment]
All green, ready to go.  I avoided using aliases for this to prevent the generated documentation from regressing.

This is a partial fix for [Issue 4541 - Intrinsic functions do not have pointers](https://issues.dlang.org/show_bug.cgi?id=4541)

**Comment by DmitryOlshansky** [comment]
> I avoided using aliases for this to prevent the generated documentation from regressing.

pragma(inline, true) then ?

**Comment by yebblies** [comment]
Is it really necessary?

**Comment by DmitryOlshansky** [comment]
> Is it really necessary?

A look at disassembly would answer that I guess. I just don't want to silently regress numerics performance.

**Comment by yebblies** [comment]
Ok, done.

**Comment by ibuclaw** [comment]
> I just don't want to silently regress numerics performance.

Not that I want to make the tongue in cheek response, but they are already silently regressed on x86 by forcing operations to be done in the highest precision.  ;-)

**Comment by DmitryOlshansky** [comment]
> but they are already silently regressed on x86 by forcing operations to be done in the highest precision. ;-)

No point destroying them further then ;)

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Comment by yebblies** [comment]
Thankyou.

**Pull request merged**
