### PR TITLE
Update contributing guide

### PR DESCRIPTION
**Pull request by JackStouffer**
* Added a FAQ section to answer some common questions from people have about their PRs. This was inspired about by https://github.com/D-Programming-Language/phobos/pull/3594, where a lot of good work was almost lost. 
* fixed the links to be in a list rather than headers

### CODE REVIEW

**Comment by Hackerpilot** [comment]
:white_check_mark:

**Comment by CyberShadow** [comment]
I think this should be on the wiki, since it applies to all projects.

**Comment by JackStouffer** [comment]
Ok, but I think it should be in here as well, because I think more people read `CONTRIBUTING.md` as GitHub auto links to it.

**Comment by CyberShadow** [comment]
Then it should link to the wiki. DRY.

**Comment by CyberShadow** [comment]
To clarify...

We seem to have a plethora of contribution guides. Everyone seems to want to write a contribution guide, because it's going to be better than all the other ones or something. As a result we have an uncoordinated duplication of information and effort. This can lead to situations such as "OK, how did you manage to create this git/PR/etc. abomination?" "I followed the guide." "Which guide?" "The one on the D website." ...

First, there's the wiki pages which are already linked to from this file:

http://wiki.dlang.org/Starting_as_a_Contributor
http://wiki.dlang.org/Pull_Requests
http://wiki.dlang.org/Building_DMD

More D Wiki pages:

http://wiki.dlang.org/Get_involved
http://wiki.dlang.org/Phobos_Quality
http://wiki.dlang.org/How_You_Can_Help

...and other pages on http://wiki.dlang.org/Category:Contribution_Guidelines.

Then, there's the projects' .md files:

https://github.com/D-Programming-Language/druntime/blob/master/HACKING.md
https://github.com/D-Programming-Language/dlang.org/blob/master/CONTRIBUTING.md

- GitHub projects

If anything, we need to turn the valve in the other direction, and work on consolidation and quality, not quantity.

**Comment by JackStouffer** [comment]
Well, I just created this page http://wiki.dlang.org/Contributing_FAQ and linked it in the file

**Comment by CyberShadow** [comment]
No, as I wrote on the talk page please do not create any more pages. Add the information to one of the many existing pages instead.

**Comment by JackStouffer** [comment]
I'll add it to the "Starting as a Contributor" page, butI don't have permission to delete pages.

**Comment by CyberShadow** [comment]
Can you integrate any useful information into http://wiki.dlang.org/Pull_Requests ? It already covers the topic of rebasing.

**Comment by JackStouffer** [comment]
@CyberShadow I'd rather not write a tutorial on squashing or updating with rebase as I think the tutorials I link do a better job than I could of explaining things.

**Comment by CyberShadow** [comment]
Are those tutorials significantly better than the information we have on the wiki? We should avoid relying on 3rd-party resources anyway, as they're not updatable and subject to bitrot.

**Comment by JackStouffer** [comment]
Updated link

> Are those tutorials significantly better than the information we have on the wiki

Yes, there is nothing that I see in "Pull Requests" that explains squashing and I think the tutorial for rebasing does a much better job of explaining rebasing for updating PRs.

**Comment by CyberShadow** [comment]
OK, then how about adding the links to http://wiki.dlang.org/Pull_Requests?

**Comment by JackStouffer** [comment]
Why don't I just take this opportunity to merge 

http://wiki.dlang.org/Starting_as_a_Contributor
http://wiki.dlang.org/Pull_Requests
http://wiki.dlang.org/Building_DMD

into 

http://wiki.dlang.org/Starting_as_a_Contributor

**Comment by CyberShadow** [comment]
That would be great if you want to undertake such a project.

**Comment by JackStouffer** [comment]
Sure. Can you delete http://wiki.dlang.org/Contributing_FAQ

**Comment by CyberShadow** [comment]
Done.

**Comment by JackStouffer** [comment]
@CyberShadow I think I've successfully done it http://wiki.dlang.org/Starting_as_a_Contributor

**Comment by CyberShadow** [comment]
Haven't reviewed it but good work :+1: You can change the other pages to be redirects to relevant sections to this one, then fix links to the olde pages.

**Comment by JackStouffer** [comment]
Updated changes to CONTRIBUTING.md

**Comment by CyberShadow** [comment]
@JackStouffer Check out https://www.mediawiki.org/wiki/Help:Redirects

**Comment by CyberShadow** [comment]
And another page that needs merging: http://wiki.dlang.org/Using_Git_on_Windows

**Comment by JackStouffer** [comment]
I will fix the redirects and merge the other article, but I believe this can be merged regardless.

**Comment by CyberShadow** [comment]
Can we get rid of the single-item-list? Maybe integrate the link into the above paragraph, e.g. "To get started, please read the [Starting as a Contributor](http://wiki.dlang.org/Starting_as_a_Contributor) article on the D wiki."

**Comment by JackStouffer** [comment]
Fixed

**Comment by CyberShadow** [comment]
> (But of course, only if the result is not less informative than its parts.)

Seems the new page is less informative than its parts. For example, there is no mention of Digger or the other build tools.

**Comment by CyberShadow** [comment]
Auto-merge toggled on

**Comment by JackStouffer** [comment]
Added the existing tools section onto the page.

**Comment by JackStouffer** [comment]
> Auto-merge toggled on

Thanks

**Comment by CyberShadow** [comment]
> Added the existing tools section onto the page.

Can you please make sure that nothing else was missed?

**Pull request merged**
