### PR TITLE
Update index.d

### PR DESCRIPTION
**Pull request by CyberShadow**
- Add missing modules
- Remove obsolete modules
- Normalize markup
- Add intentionally-omitted modules as a comment

Fixes issue 14695: https://issues.dlang.org/show_bug.cgi?id=14695

### CODE REVIEW

**Comment by quickfur** [comment]
LGTM

**Comment by aG0aep6G** [comment]
LGTM

**Comment by quickfur** [comment]
Auto-merge toggled on

**Comment by JackStouffer** [comment]
This does not actually fix issue 14695. std.uuid is still not on the index page.

**Comment by CyberShadow** [comment]
Haha, I set out to fix this and ended up overlooking the thing I wanted to fix.

**Comment by CyberShadow** [comment]
https://github.com/D-Programming-Language/phobos/pull/3616

**Pull request merged**
