### PR TITLE
Add workaround for issue 1238

### PR DESCRIPTION
**Pull request by tom-tan**
Issue 1238: https://issues.dlang.org/show_bug.cgi?id=1238

This request fixes [Issue 14405](https://issues.dlang.org/show_bug.cgi?id=14405) which was introduced by #1414

### CODE REVIEW

**Comment by davideagen** [comment]
Looks good to me.

It's sad that it's required because of the module naming visibility problem we have but at least this works around it.

**Comment by burner** [comment]
LGTM

**Comment by burner** [comment]
Auto-merge toggled on

**Comment by tom-tan** [comment]
Thanks!

**Comment by quickfur** [comment]
This works, but wow it is ugly. Are we ever going to get the fix for https://issues.dlang.org/show_bug.cgi?id=1238 ? :-(

**Pull request merged**
