### PR TITLE
Introduce std.range.generate

### PR DESCRIPTION
**Pull request by monarchdodra**
`generate` (name up to debate) simply takes a callable, and turns it into a range. Particularly useful for things like random number generators, functions with state, or functions that modify a global state.

As requested in the forums. Pinging @MartinNowak.

### CODE REVIEW

**Comment by MartinNowak** [comment]
Anyone take this over? This is almost finished.

**Comment by burner** [comment]
I will work on this.

**Comment by burner** [comment]
https://github.com/D-Programming-Language/phobos/pull/3002

**Comment by MartinNowak** [comment]
> I will work on this

Great, thanks Robert. I'll close this one.

**Pull request closed without merging**
