### PR TITLE
Fix issue 12987 - topN should return the top portion of the range 

### PR DESCRIPTION
**Pull request by Infiltrator**

### CODE REVIEW

**Comment by Infiltrator** [comment]
Could somebody please have a look over this and see whether the tests need to be more robust?  I'm not sure how all ranges would interact with these changes.

**Comment by andralex** [comment]
Yah, that's right. Thanks!

**Comment by Infiltrator** [comment]
There are problems with my changes in this PR, and I have updated my branch with some fixes.  To get them, do we need to revert this PR and then do I need to open a new PR?  Or is there an easier way?

@JackStouffer: please scrutinise.  :)

**Comment by JackStouffer** [comment]
You should open a new PR. Reverting this would take an extra PR anyway, so it might as well just be fixed.

**Pull request merged**
