### PR TITLE
Rename toXCase -> xCaser, toCapitalized -> capitalizer in std.uni

### PR DESCRIPTION
**Pull request by JakobOvrum**
Current state:

<table>
    <tr>
        <td><strong>toLower</strong></td>
        <td>eagerly convert to lower case</td>
    </tr>
    <tr>
        <td><strong>toUpper</strong></td>
        <td>eagerly convert to upper case</td>
    </tr>
    <tr>
        <td><strong>toLowerCase</strong></td>
        <td>lazily convert to lower case</td>
    </tr>
    <tr>
        <td><strong>toUpperCase</strong></td>
        <td>lazily convert to upper case</td>
    </tr>
    <tr>
        <td><strong>capitalize</strong></td>
        <td>eagerly capitalize</td>
    </tr>
    <tr>
        <td><strong>toCapitalized</strong></td>
        <td>lazily capitalize</td>
    </tr>
</table>

What I propose:

<table>
    <tr>
        <td><strong>toLower</strong></td>
        <td>eagerly convert to lower case</td>
    </tr>
    <tr>
        <td><strong>toUpper</strong></td>
        <td>eagerly convert to upper case</td>
    </tr>
    <tr>
        <td><strong>lowerCaser</strong></td>
        <td>lazily convert to lower case</td>
    </tr>
    <tr>
        <td><strong>upperCaser</strong></td>
        <td>lazily convert to upper case</td>
    </tr>
    <tr>
        <td><strong>capitalize</strong></td>
        <td>eagerly capitalize</td>
    </tr>
    <tr>
        <td><strong>capitalizer</strong></td>
        <td>lazily capitalize</td>
    </tr>
</table>

Currently there is no clue in the name whether the algorithm is eager or lazy. The normalized (or nounified) forms `lowerCaser`, `capitalizer` etc. has both an inherent semantic clue in that the name is not a verb, and there is precedent for them in Phobos (`joiner` and `splitter` being the older examples, but Walter has added a whole flurry of them since last release).

It is a valuable distinction to make, as it makes it easier for users to recognize whether an algorithm is eager or lazy. With the current state of casing and capitalization, the only way to do that is to memorize which is which.

This is not a breaking change as the new lazy algorithms have not been released yet.

Ping @WalterBright

### CODE REVIEW

**Comment by WalterBright** [comment]
Please, no. Chasing a naming convention for lazy vs eager is chasing rainbows and unicorns that left the barn several years go. Note that the algorithms in std.algorithm are lazy and eager and follow no naming convention.

Any new algorithms should be lazy unless there is a very, very good reason otherwise.

Furthermore, we need to stop this constant churn of endlessly revisiting names and arguing about them.

**Comment by JakobOvrum** [comment]
> Any new algorithms should be lazy unless there is a very, very good reason otherwise.

Yet we're stuck with the old eager algorithms, and the new names you chose do absolutely nothing to differentiate themselves from them. Convention or not, the proposed names are better because they are different. Having both `toLower` and `toLowerCase` as two *different* functions in the *same module* is a pretty dreadful proposition.

> Furthermore, we need to stop this constant churn of endlessly revisiting names and arguing about them.

There is a problem when it breaks code. This doesn't.

I don't see a good reason not to merge this.

**Comment by WalterBright** [comment]
This was all discussed and decided upon in the PR for these functions. This new PR does not add material points that were overlooked before.

**Comment by CyberShadow** [comment]
@JakobOvrum BTW, in case you missed it, there is a discussion to move forward with this and other renames: http://forum.dlang.org/post/fafybgnltpkfwpugyqvm@forum.dlang.org

**Pull request closed without merging**
