### PR TITLE
std.algorithm.iteration: Add permutations

### PR DESCRIPTION
**Pull request by CyberShadow**
https://issues.dlang.org/show_bug.cgi?id=13596

A range which lazily computes all permutations of its input using Heap's algorithm.

Not sure if this is the best module for it though.

### CODE REVIEW

**Comment by DmitryOlshansky** [comment]
I swear I've seen it somewhere. `nextPermutation` or so

**Comment by CyberShadow** [comment]
Yep, but that's not a range.

Forgot to add `See_Also` though, fair remark

**Comment by MetaLang** [comment]
Wouldn't it make sense to implement this in terms of `nextPermutation`?

**Comment by CyberShadow** [comment]
`nextPermutation` does a lot more work because it does a different thing (next lexicographical permutation).

**Comment by DmitryOlshansky** [comment]
Please add "fix issue 13596" to commit message and let's merge it.

**Comment by CyberShadow** [comment]
Done

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Pull request merged**
