### PR TITLE
std.json: Encode control characters

### PR DESCRIPTION
**Pull request by dcarp**
Currently `std.json` treats the Unicode control characters asymmetrically: it can decode them, but on encoding it throws an exception.
This PR implements the control character encoding similarly to other JSON libraries (ex. python)

### CODE REVIEW

**Comment by Hackerpilot** [comment]
Auto-merge toggled on

**Comment by JackStouffer** [comment]
@dcarp can you make a PR to update the changelog informing people of this new functionality?

**Comment by dcarp** [comment]
@JackStouffer just added #3881

**Comment by CyberShadow** [comment]
This pull request introduced a regression:
https://issues.dlang.org/show_bug.cgi?id=17555

**Pull request merged**
