### PR TITLE
Precise fsum

### PR DESCRIPTION
**Pull request by 9il**
#### Issues [DMD]
 1. ~~[ICE] https://issues.dlang.org/show_bug.cgi?id=14158~~  (workaround)
 2. ~~https://issues.dlang.org/show_bug.cgi?id=13485~~ (fixed)
 3. ~~https://issues.dlang.org/show_bug.cgi?id=13474~~  (workaround)

Note issue 13469 while testing:
https://issues.dlang.org/show_bug.cgi?id=13469  (workaround)

### Example 0:
```D
import std.numeric.summation;
import std.math, std.algorithm, std.range;
auto r1 = iota(  1, 501 ).map!(a => (-1.0)^^a/a);
auto r2 = iota(501, 1001).map!(a => (-1.0)^^a/a);
Summator!double s1 = 0, s2 = 0;
foreach(e; r1) s1.put(e); 
foreach(e; r2) s2 -= e;  //put(-e)
s1 -= s2;
assert(s1.sum == -0.69264743055982025);
```

### Example 1:
```D
import std.algorithm : map;
import std.numeric : fsum;
auto ar = [1, 1e100, 1, -1e100].map!(a => a*10000);
double r = 20000;
assert(r != ar.fsum!(Summation.Naive));
assert(r != ar.fsum!(Summation.Pairwise));
assert(r != ar.fsum!(Summation.Kahan));
assert(r == ar.fsum!(Summation.KBN)); //Fails with dmd -O -m32: DMD Optimizer BUG.   :(
assert(r == ar.fsum!(Summation.KB2));
assert(r == ar.fsum);  //Summation.Precise
```

### Example 2:
```D
//Summation.Precise is default

// Works like Python's fsum, 
// but  current implementation re-establish special
// value semantics across iterations (i.e. handling -Inf + Inf).

import std.numeric : fsum;
import std.math, std.algorithm, std.range;
auto ar = iota(1000).map!(a => 1.7.pow(a+1) - 1.7.pow(a)).chain([-(1.7.pow(1000))]);
assert(ar.fsum  ==  -1.0);
assert(ar.fsum!real  ==  -1.0);
```

### CODE REVIEW

**Comment by andralex** [comment]
May I convince some of the dmd core team to take a look at https://issues.dlang.org/show_bug.cgi?id=13485, https://issues.dlang.org/show_bug.cgi?id=13474, and https://issues.dlang.org/show_bug.cgi?id=13469

Perhaps aim the fixes for 2.067?

cc @WalterBright @donc @9rnsr @yebblies

**Comment by yebblies** [comment]
I can probably have a look at the optimizer bugs when I'm done with va_copy.  Do we have any sort of timeline on 2.067?

**Comment by andralex** [comment]
Let's aim for Sunday March 1st, which means we need to have a prerelease by Sun Feb 15.

**Comment by yebblies** [comment]
This needs rebasing.

**Comment by 9il** [comment]
Whoohooo! I starting to rewrite this code now! Thanks!

**Comment by 9il** [comment]
rebased

**Comment by yebblies** [comment]
Doesn't compile.

**Comment by 9il** [comment]
Fixed.

**Comment by yebblies** [comment]
So with that fix, these are the platforms it still fails on: https://auto-tester.puremagic.com/?projectid=10

It could easily be https://issues.dlang.org/show_bug.cgi?id=13474#c7 (these are all non-xmm platforms).  @WalterBright @andralex Can you comment on if that's a bug or it's indended?

**Comment by 9il** [comment]
All failures is for non-xmm platforms except Win64.
For Win64 linker fails to find fabsl and fabsf.
```
../dmd/src/dmd -g -m64 -O -w -dip25 -L/OPT:NOICF -unittest unittest.d unittest1.obj  unittest2.obj  unittest2a.obj  unittestM.obj  unittest3.obj  unittest3a.obj  unittest3b.obj  unittest3c.obj  unittest4.obj  unittest5.obj  unittest6a.obj  unittest6b.obj  unittest6c.obj  unittest6d.obj  unittest6e.obj  unittest6f.obj  unittest6g.obj  unittest6h.obj  unittest6i.obj  unittest6j.obj  unittest7.obj  etc\c\zlib\zlib64.lib ..\druntime\lib\druntime64.lib
unittest2.obj : error LNK2019: unresolved external symbol fabsl referenced in function _D3std7numeric9summation11__T4fabsTeZ4fabsFNbNiNfeZe
unittest2.obj : error LNK2019: unresolved external symbol fabsf referenced in function _D3std7numeric9summation11__T4fabsTfZ4fabsFNbNiNffZf
unittest.exe : fatal error LNK1120: 2 unresolved externals
```

**Comment by 9il** [comment]
Fix for Win64 https://github.com/D-Programming-Language/druntime/pull/1162

**Comment by 9il** [comment]
ICE https://issues.dlang.org/show_bug.cgi?id=14158

**Comment by 9il** [comment]
[Issue 13485 ](https://issues.dlang.org/show_bug.cgi?id=13485) fixed (Thanks to @yebblies).
[Issue 13474](https://issues.dlang.org/show_bug.cgi?id=13474) still blocks this PR.

**Comment by yebblies** [comment]
Would doing all the internal calculations explicitly with `real` on x86 work around the failures?

**Comment by 9il** [comment]
Yes, for real it works well.
I will try to create internal representation with real for x86.

**Comment by 9il** [comment]
There are will be some minimal precision loss for `float` and `double` versions of `fsum` on  `x87`:
`nextDown(s) <= r && nextUp(s) >= r`
instead of `s == r`. I think it is acceptable.

**Comment by 9il** [comment]
Reopened in https://github.com/D-Programming-Language/phobos/pull/2991.

**Pull request closed without merging**
