### PR TITLE
add version blocks for OS specific files

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
The background for this is that we compile all D files on __one__ OS to generate the documentation.

**Comment by quickfur** [comment]
Yes, finally!! Sanity!! The lack of generated docs for core.windows.* has been bugging me for a loong time.

**Comment by quickfur** [comment]
Auto-merge toggled on

**Comment by schveiguy** [comment]
Just so I can understand, this is so you can compile docs for e.g. FreeBSD on Windows, without having to have Windows process the lower level imports that have no docs?

**Comment by andralex** [comment]
Great, thanks.

**Comment by MartinNowak** [comment]
> Just so I can understand, this is so you can compile docs for e.g. FreeBSD on Windows, without having to have Windows process the lower level imports that have no docs?

The dpl-docs tool is build around compiling every source file and processing dmd's JSON output.
So we need to able to compile code on different platforms.

**Pull request merged**
