### PR TITLE
Documentation fixes.

### PR DESCRIPTION
**Pull request by veelo**
Replaces #3907.

### CODE REVIEW

**Comment by burner** [comment]
LGTM
@MartinNowak

**Comment by veelo** [comment]
BTW thanks for picking up #3906 from the forum. I hadn't noticed.

**Comment by quickfur** [comment]
LGTM

**Comment by quickfur** [comment]
Oops, looks like I introduced a conflict with the latest doc merge. Rebase please?

**Comment by JackStouffer** [comment]
Needs a rebase, then LGTM

**Comment by quickfur** [comment]
LGTM, thanks!

**Pull request merged**
