### PR TITLE
Add CopyShared

### PR DESCRIPTION
**Pull request by MetaLang**
This builds on @Hackerpilot's previous PR for [CopyStorageClasses](https://github.com/D-Programming-Language/phobos/pull/2782). It adds a template that will only copy the "sharedness" of a type, leaving its constness unchanged. This is a companion PR to https://github.com/D-Programming-Language/phobos/pull/3441.

### CODE REVIEW

**Comment by burner** [comment]
see my comment in https://github.com/D-Programming-Language/phobos/pull/3441

other than that LGTM

**Comment by DmitryOlshansky** [comment]
LGTM too

**Comment by burner** [comment]
there is some bad white space

:%s/\t/    /g
:%s/[ ]\+$//g

**Comment by MetaLang** [comment]
@burner I fixed this one up as well. Good to merge?

**Comment by burner** [comment]
please rebase

**Pull request closed without merging**
