### PR TITLE
std.uni: Remove stray std.stdio import

### PR DESCRIPTION
**Pull request by CyberShadow**
https://github.com/D-Programming-Language/phobos/commit/1b6b381fa42142a258a521f1aefc1360dccacc0f#commitcomment-11860337

### CODE REVIEW

**Comment by DmitryOlshansky** [comment]
Wow.. Thanks. LGTM obviously

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Comment by CyberShadow** [comment]
Apparently this caused a regression in the filesize of a compiled "Hello, world" program:

http://forum.dlang.org/post/wakzcvzqtmpxtuobkrey@forum.dlang.org

Any ideas why?

**Comment by DmitryOlshansky** [comment]
What gets pulled into binary with/without this patch?

**Comment by CyberShadow** [comment]
Before: http://thecybershadow.net/d/mapview/view.php?id=559059336fc0b
After: http://thecybershadow.net/d/mapview/view.php?id=5590593fc4513

**Comment by DmitryOlshansky** [comment]
Something is seriously wrong - now it pulls in std.stream (!) for hello world, a module long deprecated and fairly stand-alone.

**Comment by CyberShadow** [comment]
Regression filed:
https://issues.dlang.org/show_bug.cgi?id=14748

**Pull request merged**
