### PR TITLE
std.stdio: Fix documentation of File.error

### PR DESCRIPTION
**Pull request by CyberShadow**
Fixes doc to match code and test.

### CODE REVIEW

**Comment by quickfur** [comment]
LGTM

**Comment by quickfur** [comment]
Auto-merge toggled on

**Comment by schveiguy** [comment]
@quickfur damn, beat me to it, was just about to do that :)

**Comment by quickfur** [comment]
:-)

**Comment by quickfur** [comment]
I think we need some elbow grease for the PR queue... lately it's been clogging up a lot. Back when @Dicebot was on board, we managed to get it down to around ~40 or so PRs, but since that time the number of stagnating PRs has doubled. :-(

**Pull request merged**
