### PR TITLE
remove sleep times in std.file test

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
I ran that test several times in a loop and couldn't reproduce any race between file creation and dirEntry. I'd be surprised to see that happening, but maybe on Windows or NFS.
In any case this test spent 16s doing nothing.

**Comment by MartinNowak** [comment]
https://github.com/D-Programming-Language/phobos/pull/193

**Comment by MartinNowak** [comment]
The sleeping didn't intend to prevent any sort of race. It's sole idiosyncratic purpose of using sleep was to get an old/new time to compare it with file access and mod times.
Obviously it's much faster to simply add/subtract 2 seconds from the current time instead of sleeping 4 seconds.

**Comment by MartinNowak** [comment]
I also combined all the test cases into a single loop.

**Comment by jmdavis** [comment]
While I do agree that these tests needed to be improved, I would point out that it now no longer verifies that `timeLastModified` is actually getting the time that the file was last modified or that it differs appropriately from `timeCreated`. Now, if I were to go into `timeLastModified` and make it return `timeCreated` on Windows, or if I made all of them return `Clock.currTime`, then the tests wouild fail. Now, they'll succeed. At least some sleeping is required for that functionality to be tested (though certainly not as much sleeping as there was - the tests needed to be combined).

And maybe the loss of that testing is worth the time gained in the time the tests run, particularly since this code isn't likely to be messed with much, but without any sleeps, it's now easy to break the file time functions without the tests catching it.

**Comment by MartinNowak** [comment]
You're right, in order to check `timeLastModified` against `timeCreated`, I'd have to sleep between creating and modifying a file. It would be more clever to manipulate the created at to something in the paste.
But you're missing an important point, there were/are no tests that check `timeLastModified` after modifying any files. The existing tests only times after file creation, and compare `timeCreated` and `timeLastModified` with `currTime`.

**Comment by jmdavis** [comment]
Well, if the tests weren't testing that `timeLastModified` actually changed after the file was modified, then they were that much more faulty, since that would be the main reason that you would actually need sleeps. And I thought that they tested that, but it's been a while since I really looked at them.

**Comment by MartinNowak** [comment]
Let's make a deal, I add tests for mtime, and you finish #2956 :).

**Comment by jmdavis** [comment]
LOL. Okay. I keep meaning to get back to that, but I've been busy and haven't managed it. I expect to get to it within the next few days though. It shouldn't take very long (and I really should have finished it by now).

**Pull request merged**
