### PR TITLE
Remove suggestion in documentation to add an alias to uses of Flag

### PR DESCRIPTION
**Pull request by eco**
Per [Andrei's comments](https://forum.dlang.org/post/n7rbm7$2s20$1@digitalmars.com). We might also consider explaining why an alias is a bad idea (I haven't quite figured it out myself).

### CODE REVIEW

**Comment by JackStouffer** [comment]
I disagree with this change. We should really hash this out in the forum before any action is taken.

**Comment by 9il** [comment]
LGTM

**Comment by quickfur** [comment]
LGTM

**Comment by quickfur** [comment]
Alright let's hash it out in the forum first.

**Comment by andralex** [comment]
The code should be left but without the alias. It should be clarified that `Yes.xxx` and `No.xxx` are shorthands for flags.

**Comment by eco** [comment]
How's that?

**Comment by eco** [comment]
In case it's not clear, the example being deleted already existed above, just without the alias. It'd be an exact copy if it were left in but with the aliasing removed.

**Comment by andralex** [comment]
cool thx!

**Pull request merged**
