### PR TITLE
stream deprecation

### PR DESCRIPTION
**Pull request by burner**
stream needs to go

as discussed at dconf15:

* remove streams from docs 2.068
* deprecate streams 2.069
* remove streams 2.071 ( move to undead)

### CODE REVIEW

**Comment by quickfur** [comment]
LGTM

**Comment by quickfur** [comment]
Maybe also update the ddoc headers to indicate deprecation/removal dates?

**Comment by burner** [comment]
@quickfur done

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Comment by DmitryOlshansky** [comment]
Let's burn ;)

**Comment by burner** [comment]
indeed :-)

**Comment by jmdavis** [comment]
In general, I agree with this, but I am concerned that outright removing them in 2.071 is a bit premature. Arguably, we should have deprecated std.stream some time ago, but normally stuff is deprecated for about a year before it's removed from the docs, and it's about another year after that before it's removed from the code. So, unless 2.071 is incredibly delayed, this is going from compiling without any message to not compiling awfully fast. Hopefully, not many folks have been using std.stream, since it's been marked as on its way out for quite some time now (just not actually deprecated), but it's also clear based on the newsgroups and SO and whatnot that there are folks using it.

So, I don't mind pushing up the time table a bit on this in comparison to normal, but we probably want to at least keep std.stream around past 2.071 for at least a little while even if it's undocumented just so that we minimize how much unexpected code breakage we cause.

**Comment by burner** [comment]
This has been discussed at DConf, and this course of action was choose
For a hour it was actually deprecated at DConf.

People, have 2.0(69,70) to remove their stream use. I think we should stop being scared about breaking peoples stream code, when it has been marked out of date for many years by now.

**Comment by jmdavis** [comment]
Sure, we need to get rid of std.stream. I don't disagree, and I'm not against getting rid of it a lot faster than normal. I just think that outright removing it from Phobos that quickly goes against our attempts to avoid breaking existing code. Having it deprecated for only 2 major releases seems a bit quick. The only warning we've had for std.stream has been at the top of its documentation, not part compilation, and folks have clearly missed the warning or have chosen to use it anyway (though hopefully that warning has seriously reduced its usage). So, if we want to kill it off really quickly, I'd just suggest that we remove it from the documentation after 2.070 and leave it around in the code for a couple of releases after that before actually shooting it in the head. So, the folks that are slow to upgrade and find out that std.stream is getting axed won't have their code broken just by upgrading from 2.068 to 2.071. And if we actually start getting a major release every two months or so like Martin wants to do, 2.071 is going to be upon us fairly quickly. Someone who doesn't update their compiler for six months would never see the deprecation message, and they're code would simply break.

Yes, the number of people that this happens to _should_ be far lower than normal thanks to the note in the documentation, but we know that folks have been using it anyway, and it really doesn't cost us much to leave it around as undocumented for at least a couple of releases longer rather than simply removing it.

**Comment by burner** [comment]
it has been removed from documentation with 2.068. I'm just following what was discussed with @WalterBright  at dconf.

please create a PR that changes the version number, in the deprecation message, to what you think is reasonable, and ping me.

**Comment by jmdavis** [comment]
I did not realize that it had already been removed from the documentation. That was obviously done by a different PR that I missed. Normally, we haven't been putting version numbers in the deprecation messages at all (if nothing else, because we've usually provided approximate dates rather than version numbers, since version numbers haven't been consistent enough to correspond to a time frame). I can certainly create a PR to adjust the message though.

**Comment by WalterBright** [comment]
I'm not in a great rush to remove it. Deprecating it is fine. Removing it from the documentation later is fine. What is lacking are suggestions on how users can migrate their code.

And yeah, it should probably appear in https://github.com/DigitalMars/undeaD sooner rather than later.

**Comment by jmdavis** [comment]
@burner This PR updates the deprecation message: https://github.com/D-Programming-Language/phobos/pull/3647

@WalterBright 
> What is lacking are suggestions on how users can migrate their code.

Well, we basically don't _have_ a replacement. Just using range-based stuff like std.mmfile or std.stdio.byChunk is the best that we can suggest. Steven has been working off and on on std.io as a replacement for std.stdio which supports streams with ranges, but he hasn't gotten it fully ready for inclusion in Phobos yet, and no one else has brought anything to the table. And since we don't have a replacement that does roughly the same thing, we really don't have a migration path. Users will simply have to figure out how to write their code so that it's range-based rather than stream-based. And I don't know what else we can do, especially since most of us probably aren't even familiar with std.stream at this point since it's been marked as on its way to the executioner for years now.

**Pull request merged**
