### PR TITLE
Close only the descriptors that are open.  

### PR DESCRIPTION
**Pull request by ttung**
Linux, FreeBSD, and OSX all provide a directory where the files are the file descriptor numbers.  Rather than closing all the descriptors from 3 up to the resource limit, we can just close the ones that are open.  On other platforms, we fall back to the current behavior.

### CODE REVIEW

**Comment by JakobOvrum** [comment]
So I'm guessing this is intended as a performance boost? Has the difference been measured?

**Comment by ttung** [comment]
Closing a file descriptor on a test system took about 7us.  On a system with RLIMIT_NOFILE=65535, that adds up to .458s.

**Comment by JakobOvrum** [comment]
How did you measure that? Which number is 7 microseconds? If that's simply the raw result of a single execution, then that's not at all a reliable measurement.

**Comment by ttung** [comment]
It was total time.  There were other extenuating circumstances though, which I'm trying to sort through, so this optimization may or may not make sense.

**Comment by JakobOvrum** [comment]
Ping @ttung

**Comment by schveiguy** [comment]
How long does it take to query the number of open file descriptors from /proc?

Have you considered using `poll` to figure out which ones are valid?

**Pull request closed without merging**
