### PR TITLE
Fix Issue 14884 - `among` docs broken link to `find` and `canFind`

### PR DESCRIPTION
**Pull request by luismarques**

### CODE REVIEW

**Comment by luismarques** [comment]
Bugzilla link: <https://issues.dlang.org/show_bug.cgi?id=14884>

**Comment by schveiguy** [comment]
I'm going to wait until the doc tester is fixed before reviewing... @CyberShadow ?

**Comment by CyberShadow** [comment]
Git repository corruption, again. I nuked the submodule, maybe it'll work for a while longer. I'm on vacation right now.

**Comment by CyberShadow** [comment]
I fixed the corruption but master is still not buildable:

http://dtest.thecybershadow.net/results/89405386935902ebf4b5de778365e9144e9a8a57/!base/build.log

It looks like it's not fetching dmd-2.068. Not sure if this is a regression.

**Comment by CyberShadow** [comment]
I think it was broken by https://github.com/D-Programming-Language/dlang.org/pull/1050

I did not really understand the motivation for than change. IMHO it was the wrong fix for the problem it was trying to fix. The second change in particular had little to do with the arguments presented in the PR.

CC @andralex @MartinNowak

**Comment by CyberShadow** [comment]
I cloned it by invoking the make target manually, and master builds again, but this will likely come up again at the next (dot-)release.

**Comment by schveiguy** [comment]
@CyberShadow Thanks for looking at it on your vacation!

**Comment by schveiguy** [comment]
I think there is an issue with the documentation tester. Whenever I go to any of the pages, I get a 502 error.

**Comment by aG0aep6G** [comment]
Documentation tester is up again. LGTM

**Comment by CyberShadow** [comment]
Ugh, absolute URLs to dlang.org :/

**Comment by quickfur** [comment]
LGTM. Tested locally, looks great. Thanks!

The absolute URL issue is outside the scope of this PR; it should be fixed in the dlang.org repo.

**Comment by quickfur** [comment]
Filed issue for the absolute URL bug: https://issues.dlang.org/show_bug.cgi?id=14963

**Comment by CyberShadow** [comment]
Thanks.

**Comment by quickfur** [comment]
Fix attempt: https://github.com/D-Programming-Language/dlang.org/pull/1082

(Should work, but I didn't inspect every generated link for correctness.)

**Pull request merged**
