### PR TITLE
[std.regex] Faster compile-time regex

### PR DESCRIPTION
**Pull request by DmitryOlshansky**
Finally generate optimal source code for small codepoint sets. Large improvement for these cases.

### CODE REVIEW

**Comment by DmitryOlshansky** [comment]
pic10

**Comment by 9il** [comment]
> What compiler was used for benchmark? If this was DMD, please add the same with LDC
 Hide all checks

**Comment by 9il** [comment]
> What compiler was used for benchmark? If this was DMD, please add the same with LDC

This is stupid question, my bad

**Comment by 9il** [comment]
Auto-merge toggled on

**Comment by schveiguy** [comment]
Auto-merge toggled off

**Comment by schveiguy** [comment]
Reenable merge after fix for win64 build.

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Pull request merged**
