### PR TITLE
Remove use of exit() in std.getopt example

### PR DESCRIPTION
**Pull request by JakobOvrum**
Supersedes #3875

### CODE REVIEW

**Comment by jamadagni** [comment]
What the difference between directly returning from within the `switch..case` as in my #3875 and your creating a new boolean variable to hold the parsing status? IMO creating the boolean variable clutters the logic and gives opportunity for other mistakes (like resetting the variable accidentally or such).

**Comment by JackStouffer** [comment]
It's customary to only supersede a PR if the original is closed.

**Comment by JakobOvrum** [comment]
@jamadagni, like I pointed out in #3875, one of your return statements was inside a nested function. It doesn't return from `main` and won't even compile since the nested function has `void` return type.

@JackStouffer, the old PR was inactive for almost a month despite comments. It is customary to take over inactive PRs. I'm waiting to close the old one until this is merged, that's all.

**Comment by jamadagni** [comment]
@JakobOvrum: I acknowledge that I hadn't acted upon it, but I hadn't really understood the problem. Your [comment](https://github.com/D-Programming-Language/phobos/pull/3875/files#r47878788) was very terse and I didn't realize it was pointing out a problem that needed to be fixed. You could have pinged me... Ah well. Will close my PR. Go ahead and merge this.

**Comment by andralex** [comment]
Auto-merge toggled on

**Pull request merged**
