### PR TITLE
Decode-free std.regex

### PR DESCRIPTION
**Pull request by DmitryOlshansky**
I'm reviving some of my 2014 work on std.regex. Decoding UTF was deemed to be one of major performance problems in std.regex, and now it's gone.

As a side effect there are few cases left where now it does encode instead of decoding e.g. when doing some complex backwards matching, totally eliminating these (rare) cases would be further improvement.

I'm letting it hang here while I run benchmarks and otherwise make sure it does deliver. I vaguely remember getting numbers of around 15% speed up.

Also includes a few simplifications in both regex engines.

P.S. Pardon for this being a big chunk of changes, the layout of std.regex now has `std.regex.internal` package while the code was developed with plain `std.regex` in mind.

### CODE REVIEW

**Comment by quickfur** [comment]
Although I don't really have the time to review this large change right now, I have to say that I like the idea of decode-free regex. Have you managed to run the benchmarks? Thanks to D unittests, I'm reasonably confident that if the benchmarks show significant improvement, we should be ready to merge this.

**Comment by DmitryOlshansky** [comment]
@quickfur Hm I've been meaning to post something here abnout benchmarking but never composed hard data.  I'll try to get to it sometime this week. 
With DMD on most patterns: 15%  faster Thompson engine, 25% faster Backtracking engine.
Haven't checked GDC/LDC yet.

There is however regression with patterns that had a couple of intervals like `[a-zA-Z0-9]`. Previously it used special path to just check 3 if/else ranges linearly but with this patch I removed it  for simplicity. No-decode version works with encoded chars so there is no such simple range inclusion.  I'll figure out what should be the analog to restore this.

**Comment by quickfur** [comment]
One idea is to break those ranges into separate ranges whose encodings are sequential. There would be single-code-unit ranges, which work just like in an ASCII regex matcher, 2-code-unit ranges, where the matcher checks code unit pairs (for UTF-16), and increment the least significant code unit each time, etc., up to 5 (or was it 6?) code unit ranges. As long as the split-up ranges don't cross a boundary where the binary value of the incremented code unit no longer matches the correct encoding, this should work as usual.

**Comment by DmitryOlshansky** [comment]
@quickfur Yeah, 4 sub-ranges for UTF-8 and 2 for UTF-16. I guess I'll go with a single packed array with `[a,b)`'s  and depending on code point length and just use the right slice of it and proper step size. The only trick is to preserve alignment of sub-ranges.

**Comment by DmitryOlshansky** [comment]
Temporarily closing. Need to prepare and merge a few pulls and reboot this.
See the 1st one -  #3710

**Pull request closed without merging**
