### PR TITLE
Undo changes that move std.datetime unit tests inside of templates

### PR DESCRIPTION
**Pull request by jmdavis**
This reverts the changes that Robert made to some of std.datetime's tests in three recent PRs:

https://github.com/D-Programming-Language/phobos/pull/3655
https://github.com/D-Programming-Language/phobos/pull/3662
https://github.com/D-Programming-Language/phobos/pull/3661

Robert's changes are well-intentioned, but putting unit tests inside of templates results in them be instantiated every time that the template is instantiated, resulting in extra compilation time and making the tests take longer. Even worse, if all of the tests are moved into the template, then they don't even get instantiated.

The *Interval structs in std.datetime are templated, and the tests were quite carefully put outside of the templates so that they would not get instantiated over and over again or run over and over again. That unfortunately means that the examples cannot be ddoced like Robert did, but the examples are unit tests. They're just unit tested outside of the template so that they don't get instantiated and run several times over.

So, while I applaud Robert's desire to ddoc unit test blocks for the examples, in this case, I think that it is very much the wrong approach. std.datetime's unit tests take long enough as it is without having extraneous tests being compiled and run. So, I'd like the PRs for this that have been merged to be reverted (which this PR does), and the other pending ones closed:

https://github.com/D-Programming-Language/phobos/pull/3660
https://github.com/D-Programming-Language/phobos/pull/3659
https://github.com/D-Programming-Language/phobos/pull/3658
https://github.com/D-Programming-Language/phobos/pull/3657
https://github.com/D-Programming-Language/phobos/pull/3656
https://github.com/D-Programming-Language/phobos/pull/3663
https://github.com/D-Programming-Language/phobos/pull/3664

I'd do it myself, but obviously, because three of those PRs were merged, either some of the Phobos devs disagree with me, or they did not realize that the tests in question were inside of templated structs (probably the latter, but I don't know without them responding).

### CODE REVIEW

**Comment by quickfur** [comment]
Auto-merge toggled on

**Comment by quickfur** [comment]
Oops, I didn't realize the unittests were being added inside templated structs when I automerged these PR's. I was under the impression that they were free functions.  Should have checked more carefully. Sorry about that!!

**Comment by quickfur** [comment]
On a forward-going basis, though, I think it's high time we revisited this topic of unittests for template members.

While the current workaround of moving such unittests outside the template declaration works, it's inconvenient to do so as it separates the test from the code being tested, and is likely to tend toward poor maintenance. And more importantly, it makes the ddoc unable to have properly-tested code examples.  Robert actually found a bug in one of the code examples, which has been overlooked probably for a long time until it finally got turned into a real unittest.

We need some way of attaching unittests to template members yet without incurring the cost of having the same test instantiate more than once.

**Comment by jmdavis** [comment]
I certainly have no problem with us making a change to the language that makes it so that you can put unit tests within a template without them being instantiated with each template and such that they get compiled regardless of whether the template is instantiated by other code, but until we have that, it doesn't make sense to put unit tests inside of templates unless they're designed to test each and every template instantiation. And yes, that sucks, but it's the reality that we have to deal with at the moment.

**Comment by quickfur** [comment]
Do we need language support, though?

I haven't thought through the details yet, but one thought I have is something along these lines:
````
///
struct S(T)
{
    ///
    auto member() { ... }
    /// (don't know if ddoc will pick this up?)
    static if (is(T == int)) unittest
    {
        auto s = S!int;
        s.member();
    }
}

version(Phobos_unittest) auto __dummy = S!int; // force instantiation
````

This is just a very crude, rudimentary idea, but I think it might be possible to polish it into an idiom that can be widely deployed.

**Comment by jmdavis** [comment]
That gets messy fast IMHO. Honestly, I'd argue that the language should just be improved so that if you mark a `unittest` block within a template as `static`, then it's treated as independent from the template as far as compilation and instantiation goes. It avoids having to put `unittest` blocks outside of the template to instantiate it, and it allows the tests to essentially look exactly like they would normally except that they have `static` on them.

**Comment by burner** [comment]
@jmdavis how about splitting this beast finally? and merging (Pos|Neg)InfInterval?

**Comment by jmdavis** [comment]
@burner  I'm planning to tackle splitting std.datetime again as soon as I've finished updating the functions in std.datetime which use `TickDuration` to use `MonoTime` and `Duration` and put those in std.benchmark, which I'm almost done with - though that'll probably require some discussion in the newsgroup given that it's a new module, though it's not a lot of functions, and they're just new versions of existing ones that are going to be phased out. But leaving `TickDuration` around is doing a lot more damage than std.datetime being in one piece, and now that we have `MonoTime`, we can replace all of the `TickDuration` stuff and finally get rid of it.

 But what do you mean by merging the *Interval structs? No one has suggested anything of the sort before, and I don't know in what way you'd want to merge them. They do have similarities, but they're definitely distinct. In any case, they work as-is, and no one ever brings them up, so I haven't messed with them. With the split, they'll be going in `std.datetime.interval`.

**Comment by burner** [comment]
@jmdavis I looked at them side by side most difference are of the nature

```d
<= 
=> 
```

the rest seams to be nearly equal docu and boilerplate

**Comment by jmdavis** [comment]
They're very similar, but they're distinct types, because what they represent is distinct. And some of their functions are subtly different with regards to which Interval types they accept and what the resulting type is (e.g. `intersection` and `merge` are very specific about how the different Interval types interact - or whether they're allowed to interact at all).

Regardless, I honestly think that doing much with the Interval types at this point is just unnecessary churn. They have more boilerplate than would be nice, but they work, and no one is complaining about them. Messing with them would increase the chance of breaking someone's code for marginal benefit, and there are plenty of other things in Phobos that need doing that matter much more. The only plans I have to do anything with them at this point is to fix how they interact with ranges, since that wasn't done very well, but it's not high on my todo list.

**Comment by schveiguy** [comment]
> Do we need language support, though?

Yes



> one thought I have is something along these lines:

No, this means that every instance of S(T) used by external modules will compile S(T)'s unit tests.

This is the mechanism I used in RedBlackTree, and it's terrible for people using the library who want to unit test their code, not RedBlackTree's.

We need some sort of language change that allows importing modules to exclude template unit tests unless they specifically ask for them.

**Comment by quickfur** [comment]
That sounds like DIP material. I think it's worth pushing for.

**Comment by jmdavis** [comment]
I'll probably try and find time to write up a DIP this weekend. It shouldn't need to be long. I figure that we can go with marking unittest blocks as static in a template in order to make it so that they're not really compiled as part of the template - they're just there for maintainability and so that they can be used for ddoced unit tests. Based on some of Walter's past comments, I suspect that the maintainability argument won't sway him, but the ddoc issue might.

**Comment by jmdavis** [comment]
I was a bit slow about getting done, but I've written up the DIP and just posted about it: http://forum.dlang.org/post/ozvzscpmbixskarsgruw@forum.dlang.org

**Pull request merged**
