### PR TITLE
Break up unittest8.obj (SRC_TO_COMPILE_NOT_STD) to unittest[a-f].obj

### PR DESCRIPTION
**Pull request by 9rnsr**

### CODE REVIEW

**Comment by BBasile** [comment]
can this be put in the auto-merge pool in priority? 

It's the same fix as W.Bright but for the right platform this time.

**Comment by DmitryOlshansky** [comment]
LGTM

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Comment by schveiguy** [comment]
I un-auto merged all pulls that I had permission to (not a dmd contributor, so can't do those two).

**Comment by CyberShadow** [comment]
> I un-auto merged all pulls that I had permission to (not a dmd contributor, so can't do those two).

Pretty sure that won't do anything?

**Comment by schveiguy** [comment]
re-auto-merged all the ones I disabled. Hopefully this does it.

**Comment by BBasile** [comment]
Still a a couple of hours to be sure.

**Pull request merged**
