### PR TITLE
moveEmplace

### PR DESCRIPTION
**Pull request by MartinNowak**
- combined move and emplace

- moves a value and emplaces it into an
  uninitialized value of the same type

- more efficient than init + move

### CODE REVIEW

**Comment by MartinNowak** [comment]
Because I need this everytime I have to deal with struct lifetime.

**Comment by DmitryOlshansky** [comment]
Awesome. How about a version that does it in bulk (that is arrays of T's)? It's what std.array.insertInPlace should be doing.

**Comment by MartinNowak** [comment]
You're right, no more patchwork.
I added `moveEmplace`, `moveEmplaceAll`, and `moveEmplaceSome` and reimplemented the existing `move` functions in terms of `moveEmplace`. Furthermore I made `move` and `moveEmplace` attribute correct, i.e. they both inherit their attributes from T's destructor, but `moveEmplace` is always `@system`.

I also took the chance to get rid of the stale changelog and start a phobos local one, as discussed [here](http://forum.dlang.org/post/55B80051.3060501@dawg.eu) and [here](https://trello.com/c/iY3PYSeQ/37-changelog-changelog-changelog).

**Comment by MartinNowak** [comment]
We should also turn the `enforce` in `moveAll` into an assertion, b/c if people don't know whether that precondition holds they should use `moveSome`. But I'll spare that for a separate PR so that this one doesn't get too controversial.

**Comment by DmitryOlshansky** [comment]
Excellent. Merging this in a moment, I've long wanted to have it cleaned up.

**Comment by DmitryOlshansky** [comment]
Also outside the scope of this PR but I'd love to get CTFE-able move that was once upon a time shown by @denis-sh :

https://bitbucket.org/denis-sh/unstandard/src/ab5e199797e809ba4668affdc4fc8e84f40d2440/unstd/array.d?at=master#array.d-90

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Comment by DmitryOlshansky** [comment]
OT: @MartinNowak how do I do anything on that Trello thing? I mean I'm registered with my Google account but that's pretty much it.

**Comment by MartinNowak** [comment]
I made a follow-up #3531 for the enforce vs. assert change. Not sure about the ctfe thing, I usually do something like `if (__ctfe) a = b; else a = move(b);` which of course only for copyable values. It would be nice to have a better support for unique/non-copyable values even in CTFE, but since their use-case is mostly resource ownership, I'm not so sure CTFE support is that important.

**Comment by MartinNowak** [comment]
> OT: @MartinNowak how do I do anything on that Trello thing?

I added you to the board.

**Pull request merged**
