### PR TITLE
std.logger_consolidate_default_loglevel

### PR DESCRIPTION
**Pull request by burner**
* change default FileLogger LogLevel to all
* fix minor doc error

### CODE REVIEW

**Comment by JakobOvrum** [comment]
LGTM

**Comment by quickfur** [comment]
LGTM

**Comment by quickfur** [comment]
This does potentially break existing code, but since it's `std.experimental`, I guess that's OK.

**Comment by quickfur** [comment]
Auto-merge toggled on

**Comment by burner** [comment]
thank you

**Comment by ZombineDev** [comment]
std.experimental has no backwards compatability guarantees, but maybe it's still a good idea to add a changelog entry if it affects users of this module. Don't if it's applicable to this PR, though.

**Comment by burner** [comment]
https://github.com/D-Programming-Language/phobos/pull/3912

**Pull request merged**
