### PR TITLE
update zlib to v.1.2.8

### PR DESCRIPTION
**Pull request by data-man**
Is it necessary?
Tested only for Win32.

### CODE REVIEW

**Comment by data-man** [comment]
I something wrong done?
Just this is my first commit by Git.

**Comment by yebblies** [comment]
If you're referring to the fact that it has been open for 8 hours without comment, this is completely normal, especially with a part of the library like this that is rarely touched.

You can view the pull request's status on the autotester: https://auto-tester.puremagic.com/pulls.ghtml?projectid=1

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by andralex** [comment]
Interrogative: is it worth translating zlib to D? Disadvantage is we diverge from the C library so we won't benefit of updates like this.

**Comment by quickfur** [comment]
Unless we have a dedicated maintainer for dzlib, or a superior innovation on zlib, I suggest no. The last thing we need is an outdated, buggy, NIH version of zlib that's bitrotting and of inferior quality to the upstream C zlib.

Of course, it's another story if we have somebody who's interested to implement zlib in D, and do things like optimize for performance, scrutinize for security flaws, etc.. But until said person shows up, I don't think it's a good idea.

**Comment by yebblies** [comment]
It may be possible to use a magicport-like approach to automatically translate it to D, if somebody wants to have a go at that.  I think we should consider moving it out of phobos into a dub package at some point.

**Pull request merged**
