### PR TITLE
fix Issue 14548 - std.stdio.File should have sync() method (fsync/FlushF...

### PR DESCRIPTION
**Pull request by CyberShadow**
...ileBuffers wrapper)

https://issues.dlang.org/show_bug.cgi?id=14548

### CODE REVIEW

**Comment by JakobOvrum** [comment]
Makes sense to me, but I had to look up the difference between flush and sync. Maybe the documentation should explain this somewhere?

**Comment by CyberShadow** [comment]
Added some more docs

**Comment by JakobOvrum** [comment]
LGTM

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Pull request merged**
