### PR TITLE
Revert "Merge pull request #3379 from andralex/build-per-package"

### PR DESCRIPTION
**Pull request by MartinNowak**
This reverts commit a928a21dff5b4dbc70a69220ca8a53d846a02851, reversing
changes made to 7ca4060b721f2a2b886f60b6e1a85af63e5b5341.

### CODE REVIEW

**Comment by MartinNowak** [comment]
Doc tests fail b/c they can't handle stable yet.

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Comment by andralex** [comment]
So what's the procedure here? Do we remove from master as well or fix it there?

**Comment by andralex** [comment]
Also I see in the email notification the `tee` PR has been undone as well, what's with that?

**Comment by MartinNowak** [comment]
> So what's the procedure here? Do we remove from master as well or fix it there?

Yes, stable will get merged into master regularly.

> Also I see in the email notification the tee PR has been undone as well, what's with that?

We had to undo it as well, b/c it was a follow-up of the original PR. FWIW it was only a sublemental fix for the package split.

**Comment by andralex** [comment]
I see a procedural problem here. There was some work put into making the build a lot faster and it was just undone. Now the net result is we're back to slow builds and the reason for that is not super clear (what doc tests? where are they? hot to repro? etc) and there is no task filed for the person who did the original work (in this case me) to fix it and resubmit.

What we do at Facebook is when we undo someone's work (which is fairly rare and done only in somewhat urgent situations, as is arguably the case here) we also file a task assigned to the person whose work was undone to re-submit it after fixes.

So could we submit an issue when we revert a pull? Also, @MartinNowak could you please explain what the problem is here? What fails and how to repro? Thanks.

**Comment by andralex** [comment]
ping @MartinNowak @9rnsr thx

**Pull request merged**
