### PR TITLE
[REG-master] Fix Issue 14817 - std.algorithm.copy/std.file.copy conflict

### PR DESCRIPTION
**Pull request by Poita**
https://github.com/D-Programming-Language/phobos/pull/2799 introduced a regression, which prevented module that imported both std.algorithm and std.file to use unqualified calls to copy(string, string). The regression was caused by the removal of template constraints, which were preventing the std.algorithm copy from being considered for overload resolution.

std.algorithm.copy has two paths: an path for array copies, and a path for all other copies. Previously they were forked using static if inside function. Now the decision is made using template constraints.

### CODE REVIEW

**Comment by Poita** [comment]
I recommend viewing diff with whitespace ignored: https://github.com/D-Programming-Language/phobos/pull/3509/files?w=1

**Comment by quickfur** [comment]
Makes sense to me. Though I can't say I'm pleased with the gratuitous naming conflict between `std.file.copy` and `std.algorithm.copy`. But that's outside the scope of this PR.

**Comment by WalterBright** [comment]
You can still make it one function. Use a constraint that ORs the constraints for the two overloads.

Also needs a unit test to verify the fix.

**Comment by MartinNowak** [comment]
AFAIK this should go into stable b/c it fixes a regression.

**Comment by DmitryOlshansky** [comment]
@Poita - add a unittest for the fix and it should be good to go.

Personally I think splitting the function makes it simpler then following all of static if/else chains.

**Comment by WalterBright** [comment]
> splitting the function makes it simpler then following all of static if/else chains.

Harder for the user reading the documentation, though.

**Comment by DmitryOlshansky** [comment]
Ping @Poita

**Comment by DmitryOlshansky** [comment]
See #3649

**Pull request closed without merging**
