### PR TITLE
Add message free list to std.concurrency

### PR DESCRIPTION
**Pull request by complexmath**
I experimented with a lock-free freelist (which turned out to be ridiculously slow) and a locked freelist.  The locked freelist provided a bit of a performance advantage over no free list at all in my tests, and should scale better in large applications.

### CODE REVIEW

**Comment by MartinNowak** [comment]
The lock-free list is definitely faster for me, though the difference is hard to measure, given that node allocation hardly contributes to the benchmark execution time.

Maybe you forgot the static in front of `shared Node* sm_freeNodes`?
Also the [cas](http://dlang.org/phobos/core_atomic.html#.cas) arguments were swapped.

Anyhow, made a pull for you repo @complexmath, merging it will update this pull as well.
https://github.com/complexmath/phobos/pull/1

**Comment by MartinNowak** [comment]
I @complexmath doesn't respond in the next few days, we might as well merge this and I turn my changes into a separate pull.

**Comment by yazd** [comment]
This is a little bit OT but if anyone is looking at std.concurrency, a reply to this bug (https://issues.dlang.org/show_bug.cgi?id=13916) would be nice.

**Comment by MartinNowak** [comment]
see #2874

**Pull request merged**
