### PR TITLE
Implement mapJoiner

### PR DESCRIPTION
**Pull request by tmccombs**
A function similar to flatMap/bind

I'm not completely sold on the name, but mapJoiner seems more consistent with map and joiner, than flatMap.

### CODE REVIEW

**Comment by JackStouffer** [comment]
What's the rational? This is adding 84 lines for what is essentially an alias to three function calls.

**Comment by JakobOvrum** [comment]
I don't think this carries its own weight. We already have `joiner` and `cache` seems like an orthogonal issue.

We recently added a reference to `flatten` to `joiner`'s docs to improve searchability, but more could be done on the documentation front.

**Comment by greenify** [comment]
+1 for adding this as a ddoc unittest example to `joiner`'s doc.

**Comment by quickfur** [comment]
Closing this since it seems that the consensus is not to merge this.  Please open a new PR for adding the ddoc unittest example (or reopen this PR when the code is ready). Thanks!

**Pull request closed without merging**
