### PR TITLE
Fix name of package documentation: std_xyz_package.html -> std_xyz.html

### PR DESCRIPTION
**Pull request by andralex**
Also put in order the package and module definitions.

### CODE REVIEW

**Comment by WalterBright** [comment]
shouldn't these two commits be in separate PRs? They don't seem to have anything to do with each other.

**Comment by andralex** [comment]
yah sorry please refresh

**Comment by CyberShadow** [comment]
I was going to look into this today, but I was going to use redirects, to avoid the `std_algorithm.html` / `std.algorithm.package` inconsistency.

Now that we have `.htaccess` redirects, there could me a Makefile rule that creates a `.htaccess` file with the necessary rewrite rules.

But this is good too.

**Comment by CyberShadow** [comment]
win32.mak will need to be updated too, as well as the Phobos navigation in dlang.org of course.

**Comment by andralex** [comment]
Don't pull; I need to fix the menu links.

This is better than redirects because it offers a scalable approach to adding new packages or converting modules to packages.

**Comment by CyberShadow** [comment]
I don't understand. How? You list the packages explicitly, so you could create redirects in the same way.

**Comment by andralex** [comment]
>I don't understand. How? You list the packages explicitly, so you could create redirects in the same way.

With this pull all you need is specify the package in one place and its files next to it. The rest is automated.

**Comment by CyberShadow** [comment]
Why do you think the same technique can't be applied to redirects?

**Comment by andralex** [comment]
>Why do you think the same technique can't be applied to redirects?

Of course it can. What I see here is this is the direct, obvious, and already implemented approach so in a way it's incumbent already. No need to argue for it. If you think redirects are any better the burden of proof is on you. No need to waste time debating this.

**Comment by andralex** [comment]
Related: https://github.com/D-Programming-Language/dlang.org/pull/905

**Comment by CyberShadow** [comment]
Please do not put the blame on me for this.

I've already said:

> But this is good too.

I've only continued the discussion because, as I understood at the time, you said something that contradicted my understanding of the situation, so one of us was wrong or there was a miscommunication. I only wanted to find the problem to ensure we're on the same page.

I was not arguing in favor of redirects, I only wanted to know why you said that your approach was technically better when I did not see how.

**Pull request merged**
