### PR TITLE
add missing @nogc for Windows-only function

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
This issue wasn't yet noticed until the 2.069.2 stable branch was merged back, b/c allocator was still missing from phobos' makefiles.

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
How could someone miss that the tests for allocator weren't running on Windows?

**Comment by JackStouffer** [comment]
Is there a single contributor other than Adam Ruppe who uses windows?

**Comment by MartinNowak** [comment]
> Is there a single contributor other than Adam Ruppe who uses windows?

Quite a few, from the core team it's Walter, Kenji, and Daniel.

**Comment by schveiguy** [comment]
I think the answer to "How could someone miss that <insert some test here> aren't running on <insert some situation here>" is because the auto tester doesn't tell you tests that it doesn't run :)

Anyway, problem solved for now, someone should investigate why the test fails when enabled.

**Pull request merged**
