### PR TITLE
Separate linux kernel, glibc, and bionic APIs where appropriate

### PR DESCRIPTION
**Pull request by joakim-noah**
Building on submitted dmd pulls [#4111](https://github.com/D-Programming-Language/dmd/pull/4111) and [#3643](https://github.com/D-Programming-Language/dmd/pull/3643) and druntime pull [#1010](https://github.com/D-Programming-Language/druntime/pull/1010), this pull substitutes the new `CRuntime_Glibc` and `CRuntime_Bionic` predefined global versions where appropriate.  After those dmd pulls are merged, `linux` will be defined for both desktop/server linux and Android, as opposed to the current situation where either `linux` or `Android` alone is expected to be defined (which is why I had to change the order in `std.system`).  dmd #4111 will have to be merged before this pull will compile and pass tests.

### CODE REVIEW

**Comment by joakim-noah** [comment]
When used with druntime PRs 1010 and [1069](https://github.com/D-Programming-Language/druntime/pull/1069), this pull now passes all tests on Android/x86 too, with the long-standing exception of `std.datetime`.  I also more narrowly scoped an import in `std.path`, as `getpwnam_r` isn't provided by bionic.  I noticed that `IPPROTO_GGP` in `std.socket` isn't declared on linux/Glibc either, so I simply defined it in druntime for Android and removed the unnecessary duplicate declarations of those protocols.

This pull is now ready for review.

**Comment by joakim-noah** [comment]
Ping, I marked this pull ready for review a month ago, should be easy to go through.

**Comment by joakim-noah** [comment]
Would somebody please remove the "needs work" label on this?  I marked it ready for review 3 months ago, it needs no more work.

**Comment by JakobOvrum** [comment]
LGTM, with the caveat that I'm not familiar with the particular differences between glibc and bionic.

Would this break the build for targets linking with non-glibc C runtime implementations on Linux that happened to implement the same extension as glibc? Perhaps not a noteworthy issue, I don't know.

**Comment by joakim-noah** [comment]
You mean someone who used the `CRuntime_Glibc` version specifier but wasn't using glibc?  Doesn't sound likely.

**Comment by JakobOvrum** [comment]
> You mean someone who used the `CRuntime_Glibc` version specifier but wasn't using glibc? Doesn't sound likely that someone would do that.

I mean the instances of using `linux` that were changed to `CRuntime_Glibc`.

**Comment by joakim-noah** [comment]
I'm still not completely clear, as I cannot make out what "the same extension as glibc" means.  `linux` used to implicitly mean "linux kernel + glibc."  After this change, it will mean only "linux kernel," but [an explicit `CRuntime_Glibc` is set by default on the linux compiler](https://github.com/D-Programming-Language/dmd/pull/4111/files#diff-791916028fd5cf71b2903bad5fe4ddf3L1162), so the behavior of druntime/phobos will not change.  If you set [the `-m32android` flag when compiling, then `linux` and `CRuntime_Bionic` will be defined instead](https://github.com/D-Programming-Language/dmd/pull/3643).  That's what's changed.

**Comment by JakobOvrum** [comment]
Thanks for the explanation.

**Comment by yebblies** [comment]
This looks good, will merge if there are no objections in the next couple of days.

**Comment by joakim-noah** [comment]
Looks like there are no objections and the related druntime pulls were just merged.

**Comment by joakim-noah** [comment]
ping, @yebblies, I updated to fix the merge and it passes the tester again.

**Comment by yebblies** [comment]
Merging in 3...2...1...

**Comment by joakim-noah** [comment]
And... nothing.  I want to update the wiki with the latest patches to build from git for Android/x86, but this patch will have to be applied manually if it isn't merged, as druntime and phobos are now out of sync in the versioning they're using.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by joakim-noah** [comment]
Finally, thanks.  I'll update the wiki.

**Pull request merged**
