### PR TITLE
fix issue 15914 - [REG 2.071] getopt doesn't accept anymore a character for a bool option

### PR DESCRIPTION
**Pull request by BBasile**

### CODE REVIEW

**Comment by BBasile** [comment]
@CyberShadow sorry for the earlier comment. During 30 minutes I've been misleaded by a unittest that was failing for another reason. And more generally sorry for this regression. Curriously there was no test to verify the most simple case: a char and a bool.

**Comment by CyberShadow** [comment]
> @CyberShadow sorry for the earlier comment. During 30 minutes I've been misleaded by a unittest that was failing for another reason.

No problem :)

**Comment by BBasile** [comment]
green and more tests added.

**Comment by DmitryOlshansky** [comment]
LGTM @CyberShadow ?

**Comment by CyberShadow** [comment]
Yep, LGTM

**Comment by CyberShadow** [comment]
Auto-merge toggled on

**Pull request merged**
