### PR TITLE
index.d: proper table rows

### PR DESCRIPTION
**Pull request by aG0aep6G**
Before, table rows were faked with $(BR). This has a couple issues:
* pseudo rows fall apart when one cell breaks but the other doesn't;
* copy/paste doesn't work properly;
* editing the table is more complicated and error-prone;
* it's just plain wrong.

### CODE REVIEW

**Comment by quickfur** [comment]
Would you like to combine efforts with https://github.com/D-Programming-Language/phobos/pull/3607 ? Both touch the same file, and will probably conflict if merged separately.

**Comment by DmitryOlshansky** [comment]
LGTM

**Comment by aG0aep6G** [comment]
> Would you like to combine efforts with #3607 ? Both touch the same file, and will probably conflict if merged separately.

Sure thing. How do we go about that? If #3607 is good to go, you can just merge it. I wouldn't mind updating this one.

**Comment by aG0aep6G** [comment]
Rebased on top of the now merged #3607.

**Comment by quickfur** [comment]
Could  you also merge https://github.com/quickfur/phobos/commit/a94edb5e7d1594e35b511c32fe64618bc2cc6de2 ?  This is a followup to PR #3607 which turns out not to have actually fixed the issue it was supposed to.

**Comment by aG0aep6G** [comment]
> Could you also merge quickfur@a94edb5 ?

done

**Comment by aG0aep6G** [comment]
> Nit, commit message should say "fix issue NNNN" so that the issue automatically gets marked as fixed.

I changed the message here.

**Pull request merged**
