### PR TITLE
[std.regex] Allow nextChar to be inlined by DMD

### PR DESCRIPTION
**Pull request by DmitryOlshansky**
Healthy 2-3% of speedup.

### CODE REVIEW

**Comment by eco** [comment]
Nice trick. Maybe a comment to explain why the code is like this as it's rather unusual.

**Comment by quickfur** [comment]
It's because DMD is currently unable to recognize that an `if ... return;` block is the same as an `if ... return; else ... return;` block and can therefore be converted into an expression. This is a fairly well-known workaround for DMD's inliner. LGTM.

**Comment by quickfur** [comment]
Auto-merge toggled on

**Comment by JackStouffer** [comment]
Wait wait wait, so 7625 wasn't actually fixed?

**Comment by quickfur** [comment]
Hmm, apparently I haven't been keeping up with things. Indeed, 7625 has been fixed (at least as far as I can tell with a simple test, not sure if it might break again with slightly more complex code), so this PR is kinda redundant now.

**Comment by quickfur** [comment]
Hmm, actually, it still exhibits this problem when the else branch (with omitted `else`) contains more than just a single return statement. Test case:
````
int tembo(int x, int y)
{
        if (y == 0) return 0;
        x++;
        return x / y;
}
int pembo(int x, int y)
{
        if (y == 0) return 0;
        else
        {
                x++;
                return x / y;
        }
}
int twiga(int x, int y, int z)
{
        auto w = tembo(x, y);
        return w * z;
}
int simba(int x, int y, int z)
{
        auto w = pembo(x, y);
        return w * z;
}
````

Compiling with `dmd -O -inline -c` and disassembling, I see that `twiga` still contains a function call to `tembo`, whereas in `simba`, `pembo` has been inlined.  Removing the `x++` from `tembo` and `pembo` causes both to be inlined.  So the fix for 7625 was incomplete.

**Pull request merged**
