### PR TITLE
fix issue 15884 - Assigning char[] to std.json.JSONValue creates array, not string

### PR DESCRIPTION
**Pull request by BBasile**

### CODE REVIEW

**Comment by DmitryOlshansky** [comment]
What about wchar[]/dchar[]?

**Comment by BBasile** [comment]
I was about to do it but actually `wstring` and `dstring` are not accepted, which is a prerequisite (since the fix is actually just a `.idup`.

**Comment by BBasile** [comment]
More precisely

```D
JSONValue wide = "a"w;
assert(wide.type == JSON_TYPE.ARRAY);
```

They are handled as array. So before making the support for wchar[] / dchar[] as string, wstring and dstring must be themselves handled as string.

**Comment by DmitryOlshansky** [comment]
> So before making the support for wchar[] / dchar[] as string, wstring and dstring must be themselves handled as string.

Okay let's defer that to some other day. LGTM

**Comment by BBasile** [comment]
It's possible to call `to!string` for each type that verify `(isSomeString!T && !is(T==string))` but I'm afraid of the consequences. Also as one day or the other a new json lib will come (std.data.json, right ?), I think it's only worth to apply simple bug fix.

That said if someone else thinks that all the cases should be handled then let's handle them all.

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Pull request merged**
