### PR TITLE
Add predicate to splitter

### PR DESCRIPTION
**Pull request by kuettler**
I had the need to split an array of structs using a modified equality test. Since slitter is build on top of find, this is a rather simple change. I do not know of any downsides.

### CODE REVIEW

**Comment by andralex** [comment]
Well you need to improve the documentation as well :o). Pliz pliz...

**Comment by kuettler** [comment]
Done. There seems to be a problem if separator is an input range and `pred != "a == b"`. The problem seems to be with `find` or rather `startsWith`. I guess this should be addressed in a new PR.

**Comment by andralex** [comment]
Nice work. Thanks! Separator cannot be an input range, if that's not caught by the template constraint please follow up.

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by kuettler** [comment]
My mistake. I was talking about the second overload of `splitter`, which requires a `ForwardRange`. The problem I talked about has been addressed in #2865.

**Pull request merged**
