### PR TITLE
Add ArrayToExpTuple to std.meta

### PR DESCRIPTION
**Pull request by Hackerpilot**
This is a metaprogramming helper template that's been in EMSI's internal D library for a while. We've found it to be very useful for converting the results of CTFE function calls to Arguments used by static foreach loops.

### CODE REVIEW

**Comment by jcrapuchettes** [comment]
This was shown in my lightning talk at DConf2015.

**Comment by JakobOvrum** [comment]
See #1472. The range is a better abstraction than the array for this functionality.

**Comment by schuetzm** [comment]
See also this thread, which contains a very elegant implementation:
http://forum.dlang.org/thread/cxahuyvnygtpsaseieeh@forum.dlang.org?page=2

**Comment by Hackerpilot** [comment]
Is anybody going to make a pull request for that alternate implementation?

**Pull request closed without merging**
