### PR TITLE
Fix 14616 - ddoc shows std.socket.UnixAddress as "abstract" 

### PR DESCRIPTION
**Pull request by dcarp**
https://issues.dlang.org/show_bug.cgi?id=14616

### CODE REVIEW

**Comment by schveiguy** [comment]
You have to implement the abstract functions from `Address` too. There are 3. No need to ddoc those.

**Comment by dcarp** [comment]
Ok... added 3 more.

**Comment by schveiguy** [comment]
Looks good.

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Pull request merged**
