### PR TITLE
std.container.rbtree cleanup

### PR DESCRIPTION
**Pull request by pt-get**
- import only binaryFun from std.functional
- moved _add down with the rest of private functions since issue 2810 has been fixed
- added reference equality optimization in opEquals
- added reflexivity unittest for opEquals
- fixed documented time complexity of opEquals (should be O(n) since range is traversed once)
- removed "use more efficient algo" FIXME; this is the same equality check that SGI's C++ stl_tree.h uses, so I am fairly certain there is no better algorithm

### CODE REVIEW

**Comment by schveiguy** [comment]
Nice.

> added reference equality optimization in opEquals

This is not necessary, `object.opEquals` already tests for this: https://github.com/D-Programming-Language/druntime/blob/master/src/object.di#L61

Other than that, LGTM. I'll turn on the auto-tester for you.

**Comment by pt-get** [comment]
Done, thanks for the info.

**Comment by schveiguy** [comment]
> Does the autotester run after every new commit?

Yes, any time it sees a change, it deprecates all existing tests and starts again. It also sticks it higher in the queue when you have newer commits.

**Comment by pt-get** [comment]
Tests pass, ready.

**Comment by schveiguy** [comment]
@pt-get Typically, one other reviewer must approve before it's pulled.

**Comment by pt-get** [comment]
Ah, sorry. Not very used to bigger projects yet ;)

**Comment by JakobOvrum** [comment]
LGTM

**Comment by JakobOvrum** [comment]
Auto-merge toggled on

**Pull request merged**
