### PR TITLE
Revert PR 3379 & 3382

### PR DESCRIPTION
**Pull request by 9rnsr**
This is a challenge to revert #3379 (and its supplemental change #3382).
As you see the commit log, first I reverted any `posix.mak` changes until #3379 change, then "revert revert" necessary changes.

I think it would be correct, but I cannot test it in posix platform (because I have only windows PC).

### CODE REVIEW

**Comment by 9rnsr** [comment]
I could not open this on `stable, because those commits contains a small difference between `master` and `stable` branches. After the merge, I'll open an equivalent PR on stable.

**Comment by schuetzm** [comment]
Please make sure to squash the commits before this is merged.

**Comment by 9rnsr** [comment]
@schuetzm Yes, I'll do it.

**Comment by 9rnsr** [comment]
Squash done. Please test this.

**Comment by MartinNowak** [comment]
Thx.

> I could not open this on stable, because those commits contains a small difference between master and stable branches. After the merge, I'll open an equivalent PR on stable.

Please don't do this, committing different fixes to master and stable means I'll have to sort out a merge conflict without any git support. Rather submit this PR to the stable branch and create a merge request to merge stable into master.

**Comment by MartinNowak** [comment]
See #3513.

**Pull request closed without merging**
