### PR TITLE
Internet address constructors

### PR DESCRIPTION
**Pull request by Imagix**
Added constructors for InternetAddress and Internet6Address from a sockaddr_in or sockaddr_in6, respectively.

### CODE REVIEW

**Comment by schveiguy** [comment]
LGTM, nice work! Enabling auto-tester.

**Comment by Imagix** [comment]
Hmm... from an offline conversation, I should complete the implementation by also implementing for UnixAddress, as well as adding asserts for the address family in the constructors.

**Comment by Imagix** [comment]
Rebased to resolve a conflict that happened due to #3344 being merged.

**Comment by schveiguy** [comment]
Looked at all the updates, still LGTM.

A note: github sends out email for messages, but not for updated branches, so I didn't know about your updates until you just posted!

**Comment by Imagix** [comment]
This is my first PR, so please bear with me if this is a silly question:  What's next in this process?  Are we just waiting for someone else with write access to merge this?  

Side note: perhaps the Pull Requests page on the wiki should lay out a little more formally how this process will work to help us noobs be more comfortable in this process.

**Comment by schveiguy** [comment]
Generally, for changes in druntime and phobos, 2 eyes are required. For very small/obvious or documentation changes, most people will merge without waiting for a concurring opinion. Some changes may require approval from Walter or Andrei, or a specific maintainer (e.g. if you want to make API changes to std.datetime, I would expect Jonathan to approve).

Unfortunately, there is no specific requirement for developers to review pull requests (kind of hard when we're all volunteers). I generally will only review code that is simple (like this), or that I am involved with (i.e. have written or contributed to in the past). In fact, I don't think there's any formal rules for how or when a change should be reviewed. I looked at the wiki, I may just put the 2-eyes rule in there, and see if that sticks.

Note that only one reviewer has to have commit access. In this case, if someone else tagged this with LGTM, I'd merge it.

**Comment by MetaLang** [comment]
I don't know much about this module, but the changes look pretty straightforward.

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Comment by schveiguy** [comment]
> I don't know much about this module, but the changes look pretty straightforward.

Somewhat hard to read, but I can infer a "Looks good to me" out of that ;)

**Comment by CyberShadow** [comment]
This pull request broke building the documentation on Linux:

```
../dmd/src/dmd -c -o- -version=CoreDdoc -version=StdDdoc -Df.prerelease-dummy.html \
          -Xfdocs-prerelease.json -I../phobos @.prerelease-files.txt
../phobos/std/socket.d(3453): Error: std.socket.UnixAddress.__ctor called with argument types () matches both:
../phobos/std/socket.d(1945):     std.socket.UnixAddress.this()
and:
../phobos/std/socket.d(1950):     std.socket.UnixAddress.this()
make: *** [docs-prerelease.json] Error 1
```

Please address this ASAP (documentation build errors are a blocker for any and all updates to dlang.org).

**Comment by schveiguy** [comment]
> I may just put the 2-eyes rule in there, and see if that sticks.

Updated: http://wiki.dlang.org/Pull_Requests#Create_a_pull_request

**Pull request merged**
