### PR TITLE
Make phobos.lib include std.experimental.logger 

### PR DESCRIPTION
**Pull request by e10s**
Note this is **NOT** tested on Win64 because I have no such environment.

### CODE REVIEW

**Comment by burner** [comment]
what was the problem? from the diff it looked like you just moved the lines!

**Comment by burner** [comment]
did not work for win64

**Comment by burner** [comment]
@MartinNowak somehow the logger was not included in the win32 and win64 build.
this is strange as win32/64 failed me regularly before I rewrote FileLogger.
Anyway, this and #3024 should fix that. IMO this needs to go into 2.067. 
Sorry for the inconvenience.

**Comment by MartinNowak** [comment]
> looking at different autotester output from phobos testing, I got it.

So what was fixed here?

**Comment by burner** [comment]
all logger source where not include in phobos.lib and the unittest

this fixes it for win32

**Pull request merged**
