### PR TITLE
Const correctness in std.net.isemail

### PR DESCRIPTION
**Pull request by legrosbuffle**
Make std.net.isemail.EmailStatus properties const.

### CODE REVIEW

**Comment by quickfur** [comment]
LGTM

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Comment by legrosbuffle** [comment]
Thanks. This is my first contribution there, I understand that I'm just waiting for the pull now ?

**Comment by schveiguy** [comment]
> Thanks. This is my first contribution there, I understand that I'm just waiting for the pull now ?

We require all pull requests to be auto-tested. See here: https://auto-tester.puremagic.com/pull-history.ghtml?projectid=1&repoid=3&pullid=2861

When you see "auto-merge toggled on" it means the auto-tester prioritizes your PR, and when it passes all tests, it will be merged automatically. The comment, and the merging itself is all done on the committer's behalf. It's quite nice actually :)

And welcome!

**Comment by legrosbuffle** [comment]
Thanks for the explanations !

**Pull request merged**
