### PR TITLE
CTFE-able poly

### PR DESCRIPTION
**Pull request by 9il**
This PR allows many special math function be executed at compile time.

### CODE REVIEW

**Comment by burner** [comment]
the version else branch and your ctfe branch look alike, could you merge them. Keeping it DRY and all.

**Comment by 9il** [comment]
OK. It will be `polyImpl2` ;)

**Comment by 9il** [comment]
Rebased

**Comment by burner** [comment]
LGTM

**Comment by 9il** [comment]
Thanks!

**Comment by burner** [comment]
welcome

**Pull request merged**
