### PR TITLE
Trivial Improvements To SortedRange

### PR DESCRIPTION
**Pull request by JackStouffer**
* removed dead code
* moved imports to local

### CODE REVIEW

**Comment by JackStouffer** [comment]
I just tested this and this change fixes Issue 15003 https://issues.dlang.org/show_bug.cgi?id=15003

**Comment by schveiguy** [comment]
OK, so 2 things:

1. Change commit message to say "fix issue 15003" so bugzilla will close it automatically
2. Add unit test to verify 15003 is fixed.

Note: I'm surprised the text(st) doesn't allocate. I would think it would.

**Comment by JackStouffer** [comment]
> Note: I'm surprised the text(st) doesn't allocate. I would think it would.

That's because it does. I was running the unit tests for the wrong package. I wonder how many times I have to make that mistake before I stop.

However, I believe that my new change to remove the text call here is justified, as just printing out the tested subset of the passed range to the user doesn't make much sense to begin with. Honestly, the question of checking sorted-ness at all in a function called `assumeSorted` seems weird to me, but that's a discussion for a future PR.

**Comment by schveiguy** [comment]
> Honestly, the question of checking sorted-ness at all in a function called assumeSorted seems weird to me

It's kind of a strange thing, but I think it's correct. When you are saying `assumeSorted`, you are making a blind assumption that the type system does not check. In debug mode, it's useful to have the compiler double-check your work, to catch any specific bugs.

The removal of the text function is unfortunate, since it provides a clear idea to the user why the range isn't sorted. I'm wondering whether it would be possible for the compiler to ignore gc-allocating functions inside an assert for `@nogc` purposes, or possibly with assert while inside debug code. But that's a separate discussion.

**Comment by schveiguy** [comment]
LGTM

**Comment by yebblies** [comment]
> I'm wondering whether it would be possible for the compiler to ignore gc-allocating functions inside an assert for `@nogc` purposes, or possibly with assert while inside debug code. But that's a separate discussion.

It really should be doing that, like it ignores `pure` violations in `debug` blocks.

**Comment by JackStouffer** [comment]
> It really should be doing that, like it ignores pure violations in debug blocks.

https://issues.dlang.org/show_bug.cgi?id=15100

**Comment by burner** [comment]
LGTM

**Comment by burner** [comment]
Auto-merge toggled on

**Pull request merged**
