### PR TITLE
Removed Old Phobos1 Aliases From std.math

### PR DESCRIPTION
**Pull request by JackStouffer**
These have been deprecated for some time now, I think it's safe to remove these.

### CODE REVIEW

**Comment by quickfur** [comment]
This needs to be approved by decision-makers. Ping @WalterBright @andralex @jmdavis

**Comment by JackStouffer** [comment]
Ping @WalterBright @andralex 

Also, there is no way that this PR is causing the errors in `std.net.curl` on the auto tester, as none of the code in that module uses these aliases.

**Comment by JackStouffer** [comment]
@quickfur Could you please add the "Needs Approval" tag to this so it won't be buried forever.

**Comment by quickfur** [comment]
There's no "needs approval" label, I chose "decision block" as the next closest match. Hope it means what I think it means?

**Comment by andralex** [comment]
@WalterBright and I decided these should stay in for much longer. They're undocumented, trigger a warning if used, and shouldn't be a real bother to anyone writing new code.

**Comment by JackStouffer** [comment]
@andralex Thank you for taking a look at this. I'm glad to at least have an answer.

**Pull request closed without merging**
