### PR TITLE
Rename obsolete TypeTuple to AliasSeq

### PR DESCRIPTION
**Pull request by dcarp**
Replace following names:
std.typetuple      -> std.meta
TypeTuple          -> AliasSeq
ParameterTypeTuple -> Parameters
FieldTypeTuple     -> Fields

std.traits requires more work than search/replace and is left unchanged.

### CODE REVIEW

**Comment by JackStouffer** [comment]
Well, I am just going to assume that this is fine as it passes the auto tester, because manually reviewing 600+ lines of changes is extremely tedious.

On a related note, can the compatibility aliases for these be marked as deprecated so people will be incentivized to use the new stuff. There is no message to the user that they are using obsolete models right now.

**Comment by DmitryOlshansky** [comment]
LGTM though I haven't bothered checking every file as long as the conversion was semi-automatic it should be fine.

**Comment by dcarp** [comment]
@JackStouffer: as long as std.traits still uses TypeTuple it makes no sense to mark it as deprecated. You don't want deprecation messages just by using std.traits yet.
On the other hand the documentation already says in text that they are obsolete.

**Comment by JackStouffer** [comment]
@dcarp one of the reasons it should be deprecated is to fix all of the instances in Phobos where it's used before the next release. It will encourage people to fix std.traits instead of leaving it as is.

**Comment by Hackerpilot** [comment]
Well, this wins the prize for "most boring code review".

**Comment by Hackerpilot** [comment]
Auto-merge toggled on

**Pull request merged**
