### PR TITLE
[Trivial] Add Params section to UnqualRef documentation

### PR DESCRIPTION
**Pull request by MetaLang**

### CODE REVIEW

**Comment by Hackerpilot** [comment]
:white_check_mark:

**Comment by CyberShadow** [comment]
What is "a reference to a class"? Without context I would think this would mean `ref SomeClass someClass`. But this doesn't even refer to a variable, but to a type.

**Comment by MetaLang** [comment]
You're missing the crucial part. A reference to a class or interface __*object*__.

**Comment by CyberShadow** [comment]
A type is not an object by any D-related terminology I'm familiar with.

**Comment by MetaLang** [comment]
I've changed the wording.

**Pull request merged**
