### PR TITLE
Adds utilities for runtime conversion of hexadecimal strings

### PR DESCRIPTION
**Pull request by McSherry**
Adds `std.conv.hex` and `std.conv.isHexLiteralString` for converting hexadecimal strings to numeric values at runtime.

### CODE REVIEW

**Comment by schveiguy** [comment]
Isn't this already accomplished with `to` and `parse`?

**Comment by schveiguy** [comment]
In fact, I'm thinking now that merging https://github.com/D-Programming-Language/phobos/pull/3343 was incorrect... I had forgotten about `std.conv.parse`.

**Comment by McSherry** [comment]
Apologies, it does appear to be covered by `parse`. I didn't see that the method did radix conversion when taking a quick look through the docs.

**Comment by McSherry** [comment]
It may be an idea to have one call the other. Unless you're familiar with the function, the purpose of `parse(varName, 16)` or `parse(varName, 8)` might not be immediately clear.

**Comment by McSherry** [comment]
`parse` also doesn't seem to handle underscores in strings:

```D
string s = "FF_FF";
auto a = parse!uint(s, 16);
writeln(a); // 255
```

**Comment by schveiguy** [comment]
A good PR to parse may be to handle underscores.

**Pull request closed without merging**
