### PR TITLE
Add maxCount and maxPos

### PR DESCRIPTION
**Pull request by andralex**
These are convenience functions that are technically unnecessary. However, the fact that `minCount!"a > b"` is actually `maxCount` creates endless confusion. So, to heck with it, let's add `maxPos` and `maxCount`.

I've also made a pass through the respective documentations.

### CODE REVIEW

**Comment by quickfur** [comment]
LGTM. Based on the forum discussion, it seems we have general consensus? Should we merge?

**Comment by Hackerpilot** [comment]
:white_check_mark:

**Comment by quickfur** [comment]
Alright, let's do it.

**Comment by quickfur** [comment]
Auto-merge toggled on

**Pull request merged**
