### PR TITLE
const RedBlackTree.opBinaryRight

### PR DESCRIPTION
**Pull request by aG0aep6G**
Fixes Issue 12702.

https://issues.dlang.org/show_bug.cgi?id=12702

### CODE REVIEW

**Comment by schveiguy** [comment]
Works for me

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Comment by schveiguy** [comment]
Auto-merge toggled off

**Comment by schveiguy** [comment]
Wait, can you do `leftmost`, `rightmost`, `next`, and `prev`? Those all can be tail-inout without much effort.

**Comment by aG0aep6G** [comment]
> Wait, can you do leftmost, rightmost, next, and prev? Those all can be tail-inout without much effort.

done

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Comment by schveiguy** [comment]
Thanks!

**Pull request merged**
