### PR TITLE
[allocators] add approxMaxNodes for shared free list

### PR DESCRIPTION
**Pull request by 9il**
Root PR - https://github.com/andralex/phobos/pull/22 

ping @andralex

### CODE REVIEW

**Comment by MartinNowak** [comment]
Is it necessary to go into stable, or can this wait until the next release?

**Comment by 9il** [comment]
It would be great to add this PR to stable because it is used in production.

**Comment by andralex** [comment]
Yes, nice. Sorry for the delay.

**Comment by andralex** [comment]
Auto-merge toggled on

**Pull request merged**
