### PR TITLE
Add getUDA template

### PR DESCRIPTION
**Pull request by Hackerpilot**
This pull adds a template to get a user-defined attribute of a specific type from a symbol.

### CODE REVIEW

**Comment by jcrapuchettes** [comment]
CC @atilaneves

**Comment by jcrapuchettes** [comment]
LGTM

**Comment by Geod24** [comment]
This only gets an the first symbol, doesn't it ? Vibe.d has something that returns an `Arguments`:
https://github.com/rejectedsoftware/vibe.d/blob/master/source/vibe/internal/meta/uda.d#L191

**Comment by Hackerpilot** [comment]
I never thought anybody would apply more than one of the same UDA to something. Do people actually do that?

**Comment by Geod24** [comment]
> I never thought anybody would apply more than one of the same UDA to something. Do people actually do that?

If you want to emulate UDA on parameters (a la Java), you got to. Example here: https://github.com/rejectedsoftware/vibe.d/blob/a373835c4ac71db7c7d0b70fc925eb8410d8f4ab/source/vibe/web/rest.d#L1356
That's the only valid use case I've come across so far.

**Comment by Hackerpilot** [comment]
That example only has one `headerParam` attribute on it.

**Comment by Geod24** [comment]
I was just showcasing how we emulate UDA on parameters, I figured you'll fill in the blank.

But if you want a concrete example:
````
interface Policies {
	@headerParam("auth", "Authorization")
	@headerParam("expiry", "Expires")
	string BasicAuth(string auth, ulong expiry);
}
````

Note that `headerParam` (and `queryParam` / `bodyParam`) are actually functions that return the same structure (with different values).

**Comment by Hackerpilot** [comment]
In the case of functions that return a value getUDAs doesn't make any sense because the following are the same as far as `__traits` is concerned:
```d
string getString(string a) { return a ~ "!"; }
@getString("a") int a;
@("a!") int b;
pragma(msg, __traits(getAttributes, a)); // tuple("a!")
pragma(msg, __traits(getAttributes, b)); // tuple("a!")
```
In this case the user should be calling getUDA or just using `__traits(getAttributes` directly.

**Comment by Hackerpilot** [comment]
Can I get somebody to review or pull this?

**Comment by burner** [comment]
LGTM

**Comment by burner** [comment]
Auto-merge toggled on

**Comment by atilaneves** [comment]
LGTM

**Comment by TurkeyMan** [comment]
LGTM

**Comment by schveiguy** [comment]
I know @Hackerpilot erroneously identified this as the one that hasn't made it in, but it was merged 5 days ago :) We can probably stop reviewing it. #3421 was the one that needed review, but I merged it recently.

**Pull request merged**
