### PR TITLE
Suppress gcc warnings in zlib

### PR DESCRIPTION
**Pull request by andralex**
Got sick and tired of seeing those warnings...

### CODE REVIEW

**Comment by ibuclaw** [comment]
Perhaps you are building with the wrong cflags then.  I'll have a check to see if I'm doing things differently in gdc, because I don't recall there being warnings.

In any case, I consider it unwise to deviate from the original upstream sources.  You risk loosing them, or causing confusion when a future contributor updates zlib.

**Comment by andralex** [comment]
@ibuclaw It's because on OSX clang is actually used. I just go with the default flags.

I don't see how this is causing anyone trouble? Far as I can tell it's us who pull their sources and bake them in.

**Comment by schveiguy** [comment]
Nice. I agree with @andralex. I've been wishing to fix this, I didn't realize it was so easy.

An alternative is to propose the fix upstream ;) The repository is here: https://github.com/madler/zlib/tree/master

It hasn't been changed in 2 years, but it looks like the author is still paying attention, he's made comments on bug reports.

**Comment by schveiguy** [comment]
Hm... git clone of zlib and ./configure make produces no errors on mac. What did we do wrong for our import? Perhaps it's an issue with not properly fixing the things that ./configure did?

**Comment by schveiguy** [comment]
difference between our code and configured zlib:

zconf.h:
```diff
411c411
< #ifdef HAVE_UNISTD_H    /* may be set to #if 1 by ./configure */
---
> #if 1    /* was set to #if 1 by ./configure */
415c415
< #ifdef HAVE_STDARG_H    /* may be set to #if 1 by ./configure */
---
> #if 1    /* was set to #if 1 by ./configure */
```
Seems like if we define `HAVE_UNISTD_H` in our makefile, we're done. Will look into it further.

**Comment by schveiguy** [comment]
Done: #3396

**Comment by schveiguy** [comment]
I don't think this solution works for Windows, see autotester.

**Pull request closed without merging**
