### PR TITLE
Reset and update the change log

### PR DESCRIPTION
**Pull request by JackStouffer**

### CODE REVIEW

**Comment by DmitryOlshansky** [comment]
LGTM

**Comment by Hackerpilot** [comment]
Auto-merge toggled on

**Comment by JackStouffer** [comment]
Thanks!

**Comment by schveiguy** [comment]
Please note here, you need to be sure these changes you are removing actually go into the compiler.

For instance, see: #4175 which re-establishes the changelog entry for something that did not make it into 2.071.0, but was removed by this pull.

I'm not sure what the proper process should be. I'm thinking that we may want to have 2 sections in the file (one for next version, one for future), as the changelog process is kind of convoluted.

**Comment by JackStouffer** [comment]
Well, the best option would be to take out the change log from the repo and put it in the wiki so we don't have to have a PR for every change.

**Comment by schveiguy** [comment]
@JackStouffer the idea is to require a changelog entry before the PR is accepted. Since changelog lives in another repository, we do it this hacky way.

**Comment by JackStouffer** [comment]
> the idea is to require a changelog entry before the PR is accepted

Yeah, but that doesn't happen because it's an out of sight out of mind problem.

> Since changelog lives in another repository

Each repo has it's own changelog.

**Comment by schveiguy** [comment]
> Each repo has it's own changelog.

No, it lives here: https://github.com/D-Programming-Language/dlang.org/tree/master/changelog

On each release, the lines are copied from the changelog.dd file in each repository to there. The whole point of these changelog files is to force PR authors to simultaneously add changelog entries.

> Yeah, but that doesn't happen because it's an out of sight out of mind problem

This is an issue with reviewers. If it's not a bug fix (i.e. doesn't have a bug that is being fixed, and therefore automatically generates a changelog entry), then the reviewer should not auto-merge unless there is a changelog entry. I'm also guilty of this many times.

I'm almost thinking that the auto-tester can join forces with the dlang bot to make sure every auto-merge pull has a changelog modification, is set to fix a bug, or at least warns the person auto-merging that no changelog entry is going to be made.

But in any case, this is the process we have right now.

**Pull request merged**
