### PR TITLE
Introduce std.meta.Repeat

### PR DESCRIPTION
**Pull request by e10s**
This template `Repeat` is an easy way to make an `AliasSeq`. For example, `Repeat!(3, real)` is equal to `AliasSeq!(real, real, real)`.

### CODE REVIEW

**Comment by quickfur** [comment]
I like the idea of `Repeat`, since I've also found use for it in my own code.  I'm unsure about the mixin, though. Is that the only way to make the compiler handle large values of `n`? Is it possible to use binary expansion instead? Generally I try to only use mixins as a last resort, when all else has failed, or when the alternative is significantly uglier and more unwieldy.

**Comment by e10s** [comment]
> Is it possible to use binary expansion instead?

Sounds very good. It should be extremely effective.

**Comment by e10s** [comment]
Modified.

**Comment by quickfur** [comment]
There is no UFCS for compile-time arguments.

**Comment by JackStouffer** [comment]
LGTM

Could use a change log entry though

**Comment by e10s** [comment]
> it seems that the argument order is backwards

It's a trade-off.

`template Repeat(T...) if (T.length > 1 && is(typeof(T[$ - 1]) : size_t) && T[$ - 1] > 0)` allows `Repeat!(int, 3)` but users who see the parameter list won't recognize at once the last parameter as the number of repetition, I think. Of course, such a relation must be documented.

**Comment by quickfur** [comment]
LGTM, thanks!

**Comment by quickfur** [comment]
@e10s Please add a changelog entry to `changelog.dd`, then let's merge.

**Comment by e10s** [comment]
Ready to go!

**Comment by quickfur** [comment]
Auto-merge toggled on

**Comment by quickfur** [comment]
Let's just merge now, and revert it later if there are problems. The PR queue has been too slow lately.

**Pull request merged**
