### PR TITLE
std.functional housekeeping

### PR DESCRIPTION
**Pull request by burner**
some bugs where resolved, so some tests could be enabled
remove outcomment code last modifed 2009

### CODE REVIEW

**Comment by schveiguy** [comment]
> remove outcomment code last modifed 2009

Actually, it was checked in originally that way by Andrei. @andralex, any reason why this code was checked in as commented out? Was it going to be used for something, or did it just not compile at the time? I'd hate to remove it for arbitrary reason, it seems like it could be useful, maybe the right thing is to uncomment it and fix any bit-rot.

The rest LGTM.

**Comment by burner** [comment]
half a year ago we had a similar solution, and we came to the conclusion that we have git to get deleted code back.

**Comment by schveiguy** [comment]
> and we came to the conclusion that we have git to get deleted code back.

This is likely the only time anyone will look at this code before it's buried in an ancient git commit (actually, it likely was an svn commit). Since it was never active, and there's no indication of what it should be used for, I think it's good to examine why it was added in the first place before removing all traces of it.

**Comment by burner** [comment]
lets see what @andralex has to say

**Comment by andralex** [comment]
`NaryFun` was an attempt to generalize `unaryFun` and `binaryFun`. Since then, the emphasis of using strings for code has fallen out of favor. So it's okay to delete.

But why remove the doc comment for `compose`?

**Comment by schveiguy** [comment]
> But why remove the doc comment for compose?

Yeah, I think that was a mistake. I can't believe I missed that! @burner please fix.

**Comment by andralex** [comment]
I'm okay with pulling this after the doc comment is restored. Thanks!

**Comment by burner** [comment]
@schveiguy @andralex fixed

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Comment by burner** [comment]
thanks

**Pull request merged**
