### PR TITLE
Faster topN using a heap (or two)

### PR DESCRIPTION
**Pull request by andralex**
When looking for the median, quickselect (which topN currently uses) is a good choice. However when the sought point is close to one edge, of the range, an alternate strategy is better.

This requires https://github.com/D-Programming-Language/phobos/pull/3933.

cc @9il

### CODE REVIEW

**Comment by 9il** [comment]
> Should this be nth <= eighth ?

The reason is situation when `eighth == 0 && nth == 0`. Other LGTM

This PR improves performance for 7x7 blocks. I will post final results after correction of the inequalities.

Anyway #3922 makes `getPivot` significantly slower for `topN`.
Can `getPivot` be a combination of the new one (#3922) for ranges with length greater or equal 256 and old one for ranges with length less then 256?

**Comment by andralex** [comment]
> The reason is situation when eighth == 0 && nth == 0. Other LGTM

Oh, I missed this. Will make the correx. Thanks!

**Comment by andralex** [comment]
>Anyway #3922 makes getPivot significantly slower for topN.
>Can getPivot be a combination of the new one (#3922) for ranges with length greater or equal 256 and old one for ranges with length less then 256?

Well the thing is the new getPivot is faster when nth is closer to median. With this change, we improve performance in the other case when nth is closer to a boundary. So all in all I think we're in good shape with the combination.

**Comment by andralex** [comment]
@9il ok, done. One good first step would be to review https://github.com/D-Programming-Language/phobos/pull/3933 so as to get it out of the way. Thx!

**Comment by 9il** [comment]
Final numbers: tests with 3x3 blocks are 2-3% slower, and with 7x7 blocks are 5-6% faster. Thanks!

**Comment by 9il** [comment]
Auto-merge toggled on

**Comment by 9il** [comment]
Auto-merge toggled off

**Comment by 9il** [comment]
Rebase please

**Comment by 9il** [comment]
Blocked by forum discussion http://forum.dlang.org/thread/n7dndu$2kch$1@digitalmars.com?page=1

**Comment by andralex** [comment]
OK, the plot thickens :o). Now we have the following algorithm. In a loop:
* If `nth <= r.length / log2(r.length)^^2`, use topNHeap with one heap and stop
* If `nth <= r.length / log2(r.length)`, use topNHeap with two heaps and stop
* Take a quickselect step, adjust `r` and `nth`, and continue

**Comment by 9il** [comment]
Looks good. I will wait a day for other reviewers.

**Comment by andralex** [comment]
I have more work to do on this.

**Pull request closed without merging**
