### PR TITLE
logger housekeeping

### PR DESCRIPTION
**Pull request by burner**
* removed some debug statements
* fixed TODO (because of druntime fix)

### CODE REVIEW

**Comment by JackStouffer** [comment]
Pretty simple, LGTM.

BTW is `std.logger` going to be moved out of `experimental` for 2.069?

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Comment by burner** [comment]
thanks,

I don't think the move will happen for 2.069

**Comment by JackStouffer** [comment]
That's a shame. I was under the impression that it was usually one release between experimental -> main-line.

**Pull request merged**
