### PR TITLE
Build phobos package at a time

### PR DESCRIPTION
**Pull request by andralex**
On my Powerbook, ran the command:

    make clean && /usr/bin/time -lp make -j6 BUILD=debug MODEL=64

Took the best of three runs for baseline and proposed.

Before:  4.93s, 960270336 maximum resident set size
After: 3.85s, 618004480 maximum resident set size

On a big iron at work running Centos 6, ran the command:

    make clean && /usr/bin/time -f "%P %M" make -j64 BUILD=debug MODEL=64 lib

Took the best of three.

Before: 5.12s, 1191664
After: 3.86s, 767252

### CODE REVIEW

**Comment by andralex** [comment]
Forgot to build and include the extra files. This has low impact of performance as follows:

OSX: 4.01s, 617668608
Centos: 3.85s, 767256

**Comment by MartinNowak** [comment]
Sure this was worth the trouble? Combining all the static libs already takes 300ms on my machine.

**Comment by rsw0x** [comment]
This commit increased the size of libphobos2.a by 16MiB according to http://digger.k3.1azy.net/trend/

**Comment by CyberShadow** [comment]
Well spotted, @rsw0x.

This is bad. I think we should revert this. A 300ms build time improvement does not justify increasing the download size.

**Comment by quickfur** [comment]
Yeah, this is very bad. Please revert this.

**Comment by CyberShadow** [comment]
Well, this can't be reverted automatically now.

Anyone up for Makefile surgery?

**Comment by 9rnsr** [comment]
@MartinNowak @rsw0x @quickfur @CyberShadow I opened #3461 to try revert this PR. Could you test that will correctly fix the problem?

**Comment by 9rnsr** [comment]
And to @andralex , please review #3461.

**Pull request merged**
