### PR TITLE
Delete typelist.d

### PR DESCRIPTION
**Pull request by BBasile**
In #3238, @Dicebot told that it will be removed but it's still there (2.068).

### CODE REVIEW

**Comment by BBasile** [comment]
I've proposed him to put it in undeaD

**Comment by jmdavis** [comment]
> @WalterBright has prohibited removing it

AFAIK, it was never even compiled into Phobos. It's been in the repo but not in the makefiles. I don't see any reason why it would make any sense to keep it around. I don't see how any code could be using it.

**Comment by quickfur** [comment]
@jmdavis So we should merge this then? Nothing in dmd/druntime/phobos references it, right?

**Comment by jmdavis** [comment]
@quickfur If anything in Phobos ever referenced it, it was _years_ ago. When I first learned about std.typelist, it was not in the Makefile, and it hasn't been since. I should have just deleted it then, but I wasn't that smart apparently. But if the repo history shows that std.typelist was never part of the Makefile, then it should be easy to convince Walter that it should just be deleted. That does require digging through the repo history though, which is likely to be a bit tedious.

**Comment by DmitryOlshansky** [comment]
> But if the repo history shows that std.typelist was never part of the Makefile, then it should be easy to convince Walter that it should just be deleted. That does require digging through the repo history though, which is likely to be a bit tedious.

It's a header-only meta module. Thing is I don't think anybody used it even back in 2007-2009, as the module was an experiment

**Comment by BBasile** [comment]
the module that was intended to replace it is itself now renamed and deprecated.
`std.typelist -> std.typetuple -> std.meta.`
You're not so punctilious with std.streams.By the way, it should be visible in the thread but since the beginning of this absurd discussion the move to undead is proposed:
https://github.com/DigitalMars/undeaD/pull/5

**Pull request closed without merging**
