### PR TITLE
Rename std.string.splitterLines to std.string.lineSplitter

### PR DESCRIPTION
**Pull request by schuetzm**
As discussed in PR #2987.

### CODE REVIEW

**Comment by schuetzm** [comment]
Actually I'd prefer to call it `byLine` in analogy with `std.stdio.byLine`, but I'm worried about the small difference in behaviour with respect to line endings (thanks to @ntrel for pointing it out).

**Comment by ntrel** [comment]
LGTM

**Comment by quickfur** [comment]
LGTM

**Comment by quickfur** [comment]
ping @andralex @AndrejMitrovic

**Comment by AndrejMitrovic** [comment]
Sorry but there's some issue with the autotester.

```
Sorry, it looks like you don't have permission to this project at github.
```

**Comment by quickfur** [comment]
Brad needs to approve him before his PRs will get auto-tested.

**Comment by AndrejMitrovic** [comment]
No, I have the same problem with Kenji's pull. :/

**Comment by quickfur** [comment]
Oh? Is something wrong with the auto-tester? I did notice this past week that auto-merged PRs get credited to Brad no matter who toggled it. Wonder if that's related...

**Comment by burner** [comment]
LGTM

**Comment by burner** [comment]
Auto-merge toggled on

**Comment by kuettler** [comment]
Call me old-fashioned. (And I know I am late to the party.) This is a very recent addition and I think it rather rude to rename a library function without consent of its author, especially if the author is @WalterBright. Am I really so far off?

**Comment by schuetzm** [comment]
Well, there seemed to have been consensus, and Walter didn't speak up in a week so far (neither here nor in his PR). I guess he's ok with it. The important thing IMO is to get a decision before the release, which is due soon.

**Comment by tom-tan** [comment]
Was `splitterLines` completely deleted?
IMHO it will be better to leave `splitterLines` with `deprecated` attribute to show the migration path to the users.

**Comment by ntrel** [comment]
@tom-tan splitterLines was never released, so it's OK to rename it.

**Comment by ntrel** [comment]
Actually it does appear in the release branch [here](https://github.com/D-Programming-Language/phobos/blob/2.067/std/string.d#L2066) - we need to get this pull merged into 2.067.

**Comment by burner** [comment]
@MartinNowak "we need to get this pull merged into 2.067."

**Comment by tom-tan** [comment]
> splitterLines was never released, so it's OK to rename it.

I see. I did not notice that.

**Pull request merged**
