### PR TITLE
.gitignore: Add Windows intermediate files

### PR DESCRIPTION
**Pull request by CyberShadow**

### CODE REVIEW

**Comment by JakobOvrum** [comment]
Yeah this was pretty annoying. LGTM.

**Comment by quickfur** [comment]
:+1:

**Comment by quickfur** [comment]
Auto-merge toggled on

**Comment by andralex** [comment]
I continue to believe that growth of `.gitignore` files is a symptom of a larger problem: a disorganized build process that leaves junk files left where they don't belong. Am I alone?

**Comment by cym13** [comment]
@andralex : That's exactly the comment I would have written!

**Comment by CyberShadow** [comment]
@andralex In this instance, yes. The Phobos win32.mak is less organized in where it creates temporary files than posix.mak, but I didn't want to risk breaking things by moving things around.

**Comment by CyberShadow** [comment]
BTW, there are some entries in our .gitignore files that shouldn't be there. For example, the `Makefile` and `GNUmakefile` entries do not belong in `.gitignore`, they should be in `.git/info/exclude`. And I've no idea what the `.*.sw*` is for.

**Comment by schuetzm** [comment]
`*.*.sw*` is for the temporary files that vi creates during editing of a file.

**Comment by CyberShadow** [comment]
Those should not be in our .gitignore either. They should be in users' global .gitignore.

**Pull request merged**
