### PR TITLE
enhance std.string.chomp so it accepts ranges

### PR DESCRIPTION
**Pull request by WalterBright**
1. accept ranges as input
2. `nelSep` is accepted as a line ending
3. unittests to 100% coverage
4. Params: and Returns: documentation

http://dlang.org/phobos/std_string.html#.chomp

### CODE REVIEW

**Comment by MetaLang** [comment]
Should these enhancements be added in std.string? Seems like a more generic version of chomp should go in std.range or std.algorithm.

**Comment by JakobOvrum** [comment]
> Should these enhancements be added in std.string? Seems like a more generic version of chomp should go in std.range or std.algorithm.

The generic version of chomp is std.algorithm.strip.

**Comment by MetaLang** [comment]
So what's the point of adding range support to chomp? I thought the point of std.string is that it's generic algorithms specialized for strings.

**Comment by WalterBright** [comment]
The difference is that chomp handles the vagaries of line endings.

**Comment by WalterBright** [comment]
I added a `See_Also` for `stripRight`.

**Comment by JakobOvrum** [comment]
> So what's the point of adding range support to chomp? I thought the point of std.string is that it's generic algorithms specialized for strings.

It's just as useful to use text-specific algorithms on arrays of characters as it is using them on ranges of characters.

**Comment by WalterBright** [comment]
Using bidirectional ranges would have to be a completely different algorithm. This one returns slices, which is quite efficient, and why it requires indexing.

**Comment by Panke** [comment]
It is not consistent to #3085

**Comment by WalterBright** [comment]
> It is not consistent to #3085

Please explain.

**Comment by Panke** [comment]
splitLines now also splits on \v and \f but chomp does not treat them as line terminators.

**Comment by WalterBright** [comment]
added \v and \f

**Comment by JakobOvrum** [comment]
The Unicode correctness is a nice improvement, but the range generalization is practically useless since it still requires a random access range. I don't think many users use non-slice containers like `Array!char` for their strings. I guess it works for people experimenting with `RCString`...

Still a net improvement, so LGTM.

**Comment by WalterBright** [comment]
Many algorithms, such as byCodeunit, 'pass through' the characteristics of their input ranges, like indexability. But they pass them on as indexable ranges, not as arrays. So while I agree that it would be better if chomp() did not require indexability, it at least makes it usable in a lot of places where it wasn't before (without additional memory allocation).

**Comment by JakobOvrum** [comment]
> Many algorithms, such as byCodeunit, 'pass through' the characteristics of their input ranges, like indexability. But they pass them on as indexable ranges, not as arrays. So while I agree that it would be better if chomp() did not require indexability, it at least makes it usable in a lot of places where it wasn't before (without additional memory allocation).

Yeah, you're right, this does make it work nicely with `byCodeUnit` and friends. I can't think of many other use cases but that's probably just me not thinking hard or long enough.

**Comment by MetaLang** [comment]
👌

**Comment by JakobOvrum** [comment]
Auto-merge toggled on

**Pull request merged**
