### PR TITLE
Remove unneeded @disable clear now that clear is removed from object.di

### PR DESCRIPTION
**Pull request by schveiguy**

### CODE REVIEW

**Comment by quickfur** [comment]
Do we need to stagger this by one release, or is it OK to remove it now?

**Comment by schveiguy** [comment]
@quickfur it is no longer needed. Druntime has now removed the `clear` function. What the `@disable clear` did was to prevent you from doing `appender.clear()` and what it was really doing is calling `destroy(appender)`, not what you want to do.

See here: https://github.com/D-Programming-Language/phobos/pull/3129

No API changes are happening here. `Appender!(someImmutableType[]).clear` didn't work before, and won't work after.

**Comment by quickfur** [comment]
Fair enough.

**Comment by quickfur** [comment]
Auto-merge toggled on

**Pull request merged**
