### PR TITLE
fix issue 14920 - [REG2.067.0] SList.insertAfter on uninitialized list triggers assertion in _first targeting stable branch

### PR DESCRIPTION
**Pull request by tosttost**
same as https://github.com/D-Programming-Language/phobos/pull/3554 but targeting the stable branch. I can't edit the target branch. More information about desired target branch on http://wiki.dlang.org/Pull_Requests would help:)

fix https://issues.dlang.org/show_bug.cgi?id=14920
- add a call to initialize() (similar to other insert* functions)
- add unit test

### CODE REVIEW

**Comment by tosttost** [comment]
made some mistake when changing the target -> a lot of commits from master are part of this PR. Trying to fix it.
Sorry for the chaos...

**Comment by tosttost** [comment]
chaos resolved.

**Comment by atilaneves** [comment]
LGTM

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Pull request merged**
