### PR TITLE
Merge branch 'stable' into merge_stable

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
The merged change should be removed right away.

**Comment by schveiguy** [comment]
> The merged change should be removed right away.

huh? I'd pull this thinking it was simply a maintenance pull, but I'm puzzled by the comment.

**Comment by MartinNowak** [comment]
We deprecated something in the point release that was accidentally released in 2.067.0, and we should remove that alias in 2.068.0.

**Comment by MartinNowak** [comment]
ping

**Pull request merged**
