### PR TITLE
Issue 14763 - Use optionsData argument for options function.

### PR DESCRIPTION
**Pull request by karronoli**
Test code is in https://github.com/karronoli/std_net_curl_test
It is not tested in curl.d unittest block, because test http server is poor.
- client
 - options.d
- server
 - options.go

### CODE REVIEW

**Comment by DmitryOlshansky** [comment]
This one is strange: OPTIONS do not carry any data in ordinary case unlike POST and PUT. It's sole purpose is to query what methods are allowed for a particular resource. If anything it's closer to GET.

**Comment by karronoli** [comment]
OPTIONS method can carry some data by RFC 2616.
Sorry if I understand.

HTTP/1.1: Method Definitions
http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html
>If the OPTIONS request includes an entity-body (as indicated by the presence of Content-Length or Transfer-Encoding), then the media type MUST be indicated by a Content-Type field.

**Comment by DmitryOlshansky** [comment]
> Although this specification does not define any use for such a body, future extensions to HTTP might use the OPTIONS body to make more detailed queries on the server. A server that does not support such an extension MAY discard the request body. 

I'm OK to follow spec to a word even if it has no use for now.

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Comment by karronoli** [comment]
Certainly It has come to feel this commit strange.
But optionsData argument is also strange because it is not used anywhere.

I do not know what to do this.
I am sorry, but please could you not merge this commit?

**Comment by DmitryOlshansky** [comment]
@karronoli can you be more specific? Link relevant lines of code.

Also at worst I can just make a pull with revert. Or you can trace down OPTIONS with data code path futher and fix it.

**Comment by karronoli** [comment]
Please a couple of days to think about this problem.. sorry.

**Comment by karronoli** [comment]
Please reverts D-Programming-Language/phobos#3466

I am sorry to change the opinion.
I think that optionsData should not accept string,
because it is not used anywhere and options function do not carry data any data.
I want to change to confirm that optionsData is null.
6a93ca1095bb409bd86bf0da7f8451b6807e51d4

I make a new issue instead of this issue If need.

**Comment by DmitryOlshansky** [comment]
> Please reverts D-Programming-Language/phobos#3466

Done

**Comment by MartinNowak** [comment]
FWIW the right thing to do is to disable data, #3570.

**Pull request merged**
