### PR TITLE
Unittest failures

### PR DESCRIPTION
**Pull request by andralex**
This fixes unittest failures with BUILD=debug. I'll submit separate bug reports for the respective issues.

### CODE REVIEW

**Comment by burner** [comment]
I basically made the same changes a second ago. I really think we should figure out why sort is safe in release and not in debug. The other way round might just make sense.

Other than that. LGTM

**Comment by andralex** [comment]
See also https://issues.dlang.org/show_bug.cgi?id=14105

**Comment by andralex** [comment]
See also https://issues.dlang.org/show_bug.cgi?id=14106

**Comment by andralex** [comment]
@burner ok then why don't you merge? Oh you're not on the team. Fixed.

**Comment by burner** [comment]
Auto-merge toggled on

**Comment by burner** [comment]
@andralex what an honor, thank you

**Pull request merged**
