### PR TITLE
Fix-up coefficients and smallest denormal value for ieeeDouble in exp()

### PR DESCRIPTION
**Pull request by MartinNowak**
[Issue 14732 – [2.068 beta] Failing unittest in std.math](https://issues.dlang.org/show_bug.cgi?id=14732)

### CODE REVIEW

**Comment by ibuclaw** [comment]
Note, though doesn't actually fix the bug. The problem is with the test itself.

**Comment by MartinNowak** [comment]
> Note, though doesn't actually fix the bug. The problem is with the test itself.

Can you make a pull to fix the test then?
And let's please merge this.

**Comment by ibuclaw** [comment]
According to @kinke - the test works on Win64 and when using LLVM intrinsics.  However I get an "off by one" precision difference when using this function at double precision, when using glibc, and when using GCC builtins.

I think the conclusive result might be to ensure that we are accurate up to mantissa bits - 1?  This would mean that all tests would be affected.

**Comment by MartinNowak** [comment]
> I think the conclusive result might be to ensure that we are accurate up to mantissa bits - 1? This would mean that all tests would be affected.

I understand too little of the topic to make that decision and lack the time to go into the details.
Why would our implementation fail to deliver the correct result?

Can we already merge __this__ PR which seems to fix some constants, then follow-up on the test failure.

**Comment by ibuclaw** [comment]
> Why would our implementation fail to deliver the correct result?

I don't know.  When I run the test using GDC to build, I get the same result back as when using GCC to call the libm function.  @kinke used LDC and LLVM and got back a different result (albeit, on a different platform).

It might be purely down to a conflict between compiler backends/C runtimes.

**Pull request merged**
