### PR TITLE
Add travis to CI list

### PR DESCRIPTION
**Pull request by greenify**
Hi all,

Autotester is great and getting such a wide coverage with free tools is quite hard, however there are great tools like travis out there which run reliable and could assist your PR workflow.

It runs for every commit and PR _reliably_ the unittests on a Linux 64bit machine and on OSX. On every forced push it runs again, too. Everyone can immediately see/follow the _entire_ log.
It takes ~15min for both builds to complete.

You can see an example build here:

https://travis-ci.org/greenify/phobos/builds/111955286

I assume that you all are familiar with travis - it's probably the most popular ci service out there and has a lot of other features in case they might be needed.

PS: If you decide to merge this, don't forget to add travis to the hooks list.

### CODE REVIEW

**Comment by greenify** [comment]
DMD also uses a [similar setup](https://github.com/D-Programming-Language/dmd/blob/master/travis.sh) - maybe @MartinNowak can push Travis testing forward for Phobos?

**Comment by greenify** [comment]
@klickverbot 

> Duplicating this on Travis for no good reason seems like a waste of their resources.

My experience from the CI results of autotester over the last two weeks is that its mostly on pending (as you can see here) and travis will run smoothly -> usually a good & fast feedback (failing tests, correct style e.g. no trailing whitespaces ...)

**Comment by MartinNowak** [comment]
I agree with @klickverbot here, let's not another CI that tests the same thing, it will just incur more maintenance cost w/o providing any benefit.
We can't replace the auto-tester b/c of all the other platforms we're testing.
A big delay in the auto-tester is caused by a lack of github hooks, sth. that is relatively easy to fix.

**Comment by greenify** [comment]
> A big delay in the auto-tester is caused by a lack of github hooks, sth. that is relatively easy to fix.

Okay I do agree, but it would be nice to have that. I filed an issue for this:
https://issues.dlang.org/show_bug.cgi?id=15746

**Pull request closed without merging**
