### PR TITLE
Fix Issue 15553 - topN very inefficient [slower than sort, even for topN(0)] but should be O(n)

### PR DESCRIPTION
**Pull request by andralex**
* Replace random selection with getPivot, which is also used by sort. 
* Use a local copy instead of swapping range elements around when possible
* Special-case n==0, which may be either requested from the beginning or occur naturally toward the end of the search.

### CODE REVIEW

**Comment by andralex** [comment]
While at it I've also improved performance of partition (which topN uses) to use indexing for arrays.

**Comment by andralex** [comment]
Ugh, I ran `make std.algorithm.sorting.test` instead of ``make std/algorithm/sorting.test` and it looked like it's working. We should improve our pattern matching...

**Comment by andralex** [comment]
minPos is now also faster for certain ranges.

**Comment by JackStouffer** [comment]
> We should improve our pattern matching...

You mean humans' ;)

**Comment by 9il** [comment]
LGTM
____
For ndslice example (see also update #3925)
- 3x3 blocks: the new `topN` 90% faster than old `topN` and 10 slower than `sort`
- 7x7 blocks: the new `topN` 110% faster than old `topN` and 10 faster than `sort`

**Comment by andralex** [comment]
@9il I just invited you to the team, I guess passing a library through the review process was testing enough. You'll have the right to pull if you accept the invite. Thanks!

**Comment by 9il** [comment]
@andralex Accepted. Thank you!

**Comment by andralex** [comment]
ping - including @9il :)

**Comment by 9il** [comment]
> ping - including @9il :)

How I can turn on `AutoMerge` next time?

**Comment by andralex** [comment]
@9il click on the "details" link by the "auto-tester", create an account, and then you can use the "Toggle" link in there.

**Pull request merged**
