### PR TITLE
Fix std.conv.emplace docs

### PR DESCRIPTION
**Pull request by ntrel**
1. Move `emplace!Class(Class*)` documented unittest to correct overload & update description.
2. Add actual example for `emplace!Class(void[])`.
3. Use ddoc precondition blocks.

[Existing docs](www.dlang.org/phobos/std_conv.html#.emplace) (see 3rd overload for `emplace!Class(void[])`).

### CODE REVIEW

**Comment by ntrel** [comment]
Updated, see new description.

**Comment by greenify** [comment]
@ reviewers - this is a rather trivial additions. It just changes the formatting of the ddoc header of two methods and adds ddoced unittests - LGTM.

**Comment by DmitryOlshansky** [comment]
LGTM

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Pull request merged**
