### PR TITLE
Fix issue 12367 - std.regex: Recognize (?# ... ) comment syntax

### PR DESCRIPTION
**Pull request by DmitryOlshansky**
Adds hackish comment syntax that's supported by a lot of regex engines.

### CODE REVIEW

**Comment by 9il** [comment]
Could you please update the docs?

**Comment by DmitryOlshansky** [comment]
> Could you please update the docs?

Added a mention in docs and the changelog

**Comment by 9il** [comment]
`Error - file 'std/regex/package.d' contains trailing whitespace at line 131`

**Comment by DmitryOlshansky** [comment]
> Error - file 'std/regex/package.d' contains trailing whitespace at line 131

Fixed

**Comment by 9il** [comment]
Auto-merge toggled on

**Pull request merged**
