### PR TITLE
Generic concept checker for phobos (std.experimental.concepts)

### PR DESCRIPTION
**Pull request by schancel**
This provides the template function isConcept.  It determines if some type supports the concept specified by a class/struct/interface.

### CODE REVIEW

**Comment by DmitryOlshansky** [comment]
Is it still kicking? If so a rebase and re-disucussion would be great.

**Comment by schancel** [comment]
Yes, I can rebase it in a few days.   I got the impression that there wasn't much interest in it.  I agree that it's not ideal, but it was the best I could do as a library solution.

**Comment by schancel** [comment]
It would be nice if @andralex would look at the code for this.  Regardless of if it goes into phobos or not, there is quite a few workarounds in this code for traits bugs.  Maybe some of them have been fixed -- I will find out when I rebase.

**Comment by DmitryOlshansky** [comment]
IMHO it's fit for a phobos proposal but is significant enough to warrant a review as any new module.

**Comment by schancel** [comment]
@DmitryOlshansky I rebased it -- What would you like me to do from here?

**Comment by DmitryOlshansky** [comment]
> @DmitryOlshansky I rebased it -- What would you like me to do from here?

Depending on how serious you are about making it part of phobos. But this stuff is big as in new module and new style of constraints.

So the steps are roughly: 
- make it std.experimental.concepts
- put into review queue
- list with [RFC] on NG and gather feedback

Sometime after the usual review + vote -> phobos.

**Comment by schancel** [comment]
I see that this is no longer quite working under the latest DMD.  Will update ASAP.

**Comment by schancel** [comment]
So,  I'm not going to update this.   My reason is this:

The diagnostics are hard to get correct with the way you must add a non-specialized template:

```
//Example of using conceptDiagnostic
> bool DoStuff(R, string F = __FILE__, size_t L = __LINE__ )(R infRange)
> {
>         mixin conceptDiagnostic!(R, F, L, COutputRange!string,
> CInfiniteInputRange!string);
>         return false;
> }
```

If you have multiple concepts which you would like to output diagnostics for, you have to add an additional line for each one, and have a static assert at the end to prevent things from compiling.  

So, I think this is really a non-starter.  It was more of an example of how this could be done -- but the compile time reflection code is very tricky to get correct and IMO unmaintainable.   The compiler interfaces for these features seem to be influx.

**Comment by JackStouffer** [comment]
@schancel Please close this then. Thank you for trying to contribute to D.

**Pull request closed without merging**
