### PR TITLE
fix casing for Flag name

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by JackStouffer** [comment]
Not sure how the tests are passing as none of the usages of the original alias in the rest of the code was changed.

**Comment by JackStouffer** [comment]
Actually, can you change the reference in the `Params` section as it's outdated now.

**Comment by schveiguy** [comment]
Fix the docs and I'll merge.

**Comment by schveiguy** [comment]
Another spurious error: https://trello.com/c/YwsVrCxj/114-fix-test-race-condition-in-phobos-std-net-curl

**Comment by Hackerpilot** [comment]
@MartinNowak, I think that @schveiguy is talking about this line: `allocate_gc = A $(D std.typecons.Flag!"AllocateGC") instance`.

**Comment by MartinNowak** [comment]
Done, there was no need to mention Flag!"AllocateGC" in the params list.

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Pull request merged**
