### PR TITLE
Deprecate the non-benchmarking uses of TickDuration in std.datetime.

### PR DESCRIPTION
**Pull request by jmdavis**
This gets us another step closer to being able to deprecate `TickDuration`.

### CODE REVIEW

**Comment by Hackerpilot** [comment]
:white_check_mark:

**Comment by Hackerpilot** [comment]
I wonder if I should invoke a variant of Cunningham's Law: Merge this pull request in order to summon other reviewers.

**Comment by jcrapuchettes** [comment]
Looks good except for one potential problem.

Moving from templated to non-templated methods without `const` parameters could break currently compiling code. Should this be considered?

**Comment by jmdavis** [comment]
> Moving from templated to non-templated methods without const parameters could break currently compiling code. Should this be considered?

I'm not aware of any potential code breakage here and don't know what you're referring to. Previously, the functions in question were templated but only accepted `Duration` and `TickDuration`. Now, they're separate functions which explicitly accept `Duration` and `TickDuration`. That shouldn't break anything. It's true that when I originally did std.datetime, I mistakenly used `in` on a bunch of parameters, because I didn't understand it properly at the time, and I did not put `in` on the now non-templated functions, but the constness of the parameters shouldn't matter at all, and `scope` currently does nothing for these types. The function arguments are taken by value, and they're value types, so they're copied. Their constness is irrelevant to the caller.

So, what are you seeing that I'm missing? Or did you think that more types than `Duration` and `TickDuration` were accepted previously?

**Comment by jcrapuchettes** [comment]
Your point about function args being by-value and being copied was something I had forgotten.

:+1:

**Comment by Hackerpilot** [comment]
Auto-merge toggled on

**Pull request merged**
