### PR TITLE
Fix std.csv assertion

### PR DESCRIPTION
**Pull request by KevinBrogan**
Modified double comparison from

    a == b

to

    abs(a-b) < epsilon

### CODE REVIEW

**Comment by burner** [comment]
LGTM

**Comment by yebblies** [comment]
Are you sure this isn't a bug in the floating point parser?  Shouldn't the conversion be deterministic?

**Comment by burner** [comment]
No, but float equality comparison is nearly always a bad idea or at least bad practice.

**Comment by KevinBrogan** [comment]
I checked out the failure before hand. The two doubles differed by a single
bit. Looked like a standard rounding issue to me.

**Comment by yebblies** [comment]
> No, but float equality comparison is nearly always a bad idea or at least bad practice.

One of the few places where they make sense is in unittests.

> I checked out the failure before hand. The two doubles differed by a single
bit. Looked like a standard rounding issue to me.

Is there any arithmetic done on the value after it's parsed?  Or is the rounding error inside the parsing function?  Because if it's the latter then that probably means this change is just hiding an actual bug.

**Comment by burner** [comment]
well there is multiplication inside the parse function

@KevinBrogan maybe you could add a unittest to std.conv

**Comment by KevinBrogan** [comment]
There's nothing to unittest. Floating point math is simple unstable by its very nature.

3673.562 != 3000+600+70+30+.5+.06+.002

**Comment by KevinBrogan** [comment]
I'd recommend that anyone who would like more information read the first five articles at this link about floating point math. It's quite well written.
https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/

**Comment by kuettler** [comment]
Is `to!double("3673.562") == 3673.562` allowed to be `false`?

**Comment by quickfur** [comment]
Yes, if there is no exact representation of 3673.562 as a double.

**Comment by quickfur** [comment]
Or if there are implicit conversions to types of different precisions. In the C/C++ world, some of the implicit conversions to double can cause the counterintuitive effect that `sin(3.14159) == sin(3.14159)` could be `false`.

**Comment by kuettler** [comment]
The question here is, if the compiler reading a double literal is supposed to do the same thing as to!double("..."). I do not know. However, the question seems legitimate to me.

**Comment by burner** [comment]
what is odd though is that this test passed and is still passing for years on different cpus (autotester)
@KevinBrogan what kind of cpu do you use. csv uses std.conv.to to parse the value why not add a unittest in std.conv with the same values. That two line will not hurt anyone and we get an idea if it works or not.

**Comment by KevinBrogan** [comment]
For the record, I'm compiling with msvc on 64 bit windows using an AMD Phenom II processor with a Thuban core.

@burner, what use would it be to put in a non deterministic calculation into a unit test? Do you just want to see if it fails in std.conv as well?

I don't think any of the unit tests should have any floating point comparisons in them of the form (literal == calculated). The result depends on processor type, mode, and even the compiler used.

There is even a note of this at http://dlang.org/d-floating-point.html

> D guarantees that all built-in floating-point types conform to IEEE 754 arithmetic, making behaviour entirely predictable (note that this is not the same as producing identical results on all platforms).

**Comment by burner** [comment]
thanks, I think we can merge this now.

**Pull request merged**
