### PR TITLE
Revert "Implement issue# 13996. Add File.tempFile."

### PR DESCRIPTION
**Pull request by WalterBright**
Reverts D-Programming-Language/phobos#2956
because of https://issues.dlang.org/show_bug.cgi?id=14539

### CODE REVIEW

**Comment by MartinNowak** [comment]
So what's the lesson here? We can't add a function because it increases the binary size? Ridiculous, please fix the compiler instead.

**Comment by MartinNowak** [comment]
See https://github.com/D-Programming-Language/dmd/pull/4638 and [Issue 13242 – imported aliases should be analyzed lazily](https://issues.dlang.org/show_bug.cgi?id=13242).

**Comment by WalterBright** [comment]
The issue is this function cannot be added until whatever reason it bloats the executable size is fixed.

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
This is why checks for executable size bloat should be in the test suite.

**Comment by andralex** [comment]
@MartinNowak do we have that check around yet? I recall you mentioned it at some point.

**Comment by MartinNowak** [comment]
Yes, here https://github.com/D-Programming-Language/dmd/blob/82b031c22f18334a7edeff437260b6802070a9e3/test/runnable/test13117.d.
Someone should update the thresholds. We can lower the tolerance to maybe 1%, it cannot be zero because the would affect too many pull requests.

**Comment by MartinNowak** [comment]
> The issue is this function cannot be added until whatever reason it bloats the executable size is fixed.

Sure, but the right direction to fix bugs is going forward not backward.
It was a huge effort to get this functionality into phobos, and not it's reverted because of compiler issues the phobos devs aren't accountable for.

**Comment by WalterBright** [comment]
I'm sorry about that, but we should never pull something that causes regressions, even if it is not the fault of the new code. This is not about assigning blame.

**Comment by schveiguy** [comment]
Can we close the regression now? It's still open.

**Comment by andralex** [comment]
@MartinNowak instead of having a tolerance the better policy is to update it on a case basis where justified. @schveiguy yes, could you please close - thanks.

**Pull request merged**
