### PR TITLE
Remove deprecated modules and symbols scheduled for removal in 2015

### PR DESCRIPTION
**Pull request by AndrewEdwards**
These were scheduled to be removed last year.

### CODE REVIEW

**Comment by AndrewEdwards** [comment]
Not understanding what's happening here. I started by performing a hard reset on my fork since I haven't been here in a while:
```
    git clone https://github.com/AndrewEdwards/phobos.git
    cd phobos/
    git remote add upstream https://github.com/D-Programming-Language/phobos.git
    git fetch upstream
    checkout master
    git reset --hard upstream/master
    git push origin master --force
```
Then I made the necessary changes and pushed them to the fork:
```
    git add -A
    git commit -m "Remove deprecated modules and symbols scheduled for removal in 2015"
    git push origin master
```
After this I went online and created the pull request: pull

The errors state that I'm leaving a module behind but I don't see how it's possible to miss is with this sequence. Running `git pull --rebase upstream master` suggests that the "**Current branch master is up to date.**" and `git push origin master` says basically the same: "**Everything up-to-date**". What am I missing?

**Comment by AndrewEdwards** [comment]
I believe I've got the hang of this now.

**Comment by jmdavis** [comment]
Auto-merge toggled on

**Comment by jmdavis** [comment]
@AndrewEdwards FYI. It's generally easier to create a branch for each pull request you make rather than making changes to your master. It's required if you ever want to have more than one PR at once, and even if you don't, it usually means that you avoid getting into a weird state with your master branch when anything goes wrong.

**Pull request merged**
