### PR TITLE
explicitly disable using a conf file during the build

### PR DESCRIPTION
**Pull request by braddr**

### CODE REVIEW

**Comment by quickfur** [comment]
LGTM

**Comment by schveiguy** [comment]
Apparently, the dmd.conf file specifies where to find libcurl, and the command line does not.

**Comment by braddr** [comment]
I don't expect this to work first time out the door.  I've only tested it on linux.  I've fixed the freebsd boxes (freebsd doesn't search /usr/local/lib by default).  I won't be surprised if windows needs more help before they both pass.

**Comment by braddr** [comment]
All fixed, ready to be pulled.  For posterity:

1) freebsd, now setting LIBRARY_PATH in env to tell gcc to pick up curl -- freebsd's gcc doesn't search /usr/local/ unlike linux and osx (and most other posix-like os's).  Oddly, it _does_ search /usr/local/lib for .so's at run time by default, just not during compilation.  Thanks FreeBSD.

2) win64, setting LINKCMD64 in env rather than sc.ini file (also setting all the VC related sc.ini hosted variables just in case for the time being (didn't want to iterate a bunch of times right now) which duplicate a bunch of others.. ripe for more investigation and reduction in duplication).

**Comment by schveiguy** [comment]
I'm not sure I like the requirement to set env. Does this mean someone who downloads D source will have to set their environment on Windows and FreeBSD, when before they didn't have to? Or is that a quirk of your installation on the test boxes?

**Comment by Orvid** [comment]
Why is this needed?

**Comment by yebblies** [comment]
> Why is this needed?

https://github.com/braddr/d-tester/issues/40

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by rainers** [comment]
Wouldn't it be better to make this optional by using `CONF=-conf=` that could be redefined on the command line? Or even default to `CONF=` and just use something different by the build server?

**Pull request merged**
