### PR TITLE
proposal for the EnumSet template

### PR DESCRIPTION
**Pull request by BBasile**
**proposal for the EnumSet template**

An EnumSet allows to create a bitfield using the members of an enum, whatever is the members type or the members values. In other languages this is often used to define a set of options, easily identifiable in the code.

This proposal contains a comprehensive template that covers the concept in a D flavor
- type safety: constraints.
- efficiency: the set is packed in a _value type_ that's efficient to use as parameter (e.g as ref)
- inclusion, exclusion, constructor using several parameter kinds, input range to iterate the members that are included and much more.
- well tested.

[Code](https://github.com/BBasile/iz/blob/master/import/iz/enumset.d), it's part of a bigger library. It's kept in sync with this PR.
[Doc](http://bbasile.github.io/iz/iz/enumset.html), rendered with harbored.

### CODE REVIEW

**Comment by quickfur** [comment]
Isn't this what `std.typecons.BitFlags` already does?

**Comment by BBasile** [comment]
It's related but EnumSet if focused on enum.

**Comment by BBasile** [comment]
EnumSet passes all the tests. Time to review.

**Comment by BBasile** [comment]
Even in the supermarkets people tells: _"every body uses this"_

**Comment by BBasile** [comment]
[**the thing**](https://www.youtube.com/watch?v=wU_WSdTKaHQ)

You have nothing to tell about this PR, me neither.

**Comment by BBasile** [comment]
[**frogs**](https://www.youtube.com/watch?v=o6IsvubMKrk)

**Comment by BBasile** [comment]
[**somtimes**](https://youtu.be/3hrfjSaW8TQ?t=7m57s)

**Comment by BBasile** [comment]
No it's ok now. Was high. Forgot to unplug ethernet. If anyone's read the things just forget , there nothing to understand.

**Comment by DmitryOlshansky** [comment]
> An EnumSet allows to create a bitfield using the members of an enum, whatever is the members type or the members values. In other languages this is often used to define a set of options, easily identifiable in the code.

Truth  be told it looks like small bitset (fits in one ubyte, ushort, uint ...) with slots labeled by enum members.

**Comment by BBasile** [comment]
@klickverbot no it's not me, i don't use Skype. Yesterday I didn't read carefully your message and I thought you was speaking about the comments sent **here** during the previous night. But Skype not me.

If you manage to get his address just send it to me. My mail is in the commit messages of the project s associated to this GH account.

**Comment by BBasile** [comment]
maybe in typecons ?

**Comment by BBasile** [comment]
@klickverbot I've found some rules on my box for SKYPE on the NNTP devices. I don't know who set them up but the spam could come from here. Anyway I don't know why you've especially get the spam ? I've been barely in contact with people from the Dlang org and you're not the first in the list. It's mostly Hackerpilot because his products are interesting for me (IDE tools for Coedit). But otherwise barely anybody...

**Pull request closed without merging**
