### PR TITLE
Rename Arguments to AliasSeq

### PR DESCRIPTION
**Pull request by MartinNowak**
- cherry-picked all merges regarding AliasSeq

### CODE REVIEW

**Comment by schuetzm** [comment]
I think this goes without saying, but: This time, please don't pull this before consensus is reached and both Walter and Andrei are ok with it.

**Comment by MartinNowak** [comment]
This is just for the release, already has been done on master.

**Comment by schuetzm** [comment]
Yes, but the discussion is still ongoing. I don't know whether someone will open yet another PR.

**Comment by MartinNowak** [comment]
Whatever, this is the latest state soon to be released.
If someone wants to change it again, good luck.

**Comment by quickfur** [comment]
Didn't @andralex already say that he wants to go back to `AliasSeq`?

**Comment by MartinNowak** [comment]
> Didn't @andralex already say that he wants to go back to AliasSeq?

Yes, and we already did that on master, hence the 4 commits to drag into stable.

**Comment by MartinNowak** [comment]
> DDoc tester failure seems unrelated.

Yes Vladimir doesn't yet support the stable branch.

**Pull request merged**
