### PR TITLE
2.068 renames

### PR DESCRIPTION
**Pull request by CyberShadow**
Follow-up to the discussion:
http://forum.dlang.org/post/rvaguhviuldknnqktkbq@forum.dlang.org

This PR targets the correct branch (stable).
Previous PR: https://github.com/D-Programming-Language/phobos/pull/3439

### CODE REVIEW

**Comment by jmdavis** [comment]
No changes to std.path? http://forum.dlang.org/post/mmktgszutvkqgrjmnice@forum.dlang.org

**Comment by MartinNowak** [comment]
I guess this is good to go? Will merge it this evening.
Please advice on what to do about std.path.

**Comment by CyberShadow** [comment]
Added `toXPath`

**Comment by CyberShadow** [comment]
Master branch will need an update as it is already using the symbols renamed here. This is why the doc tester is failing (ATM it tries to merge all PRs with master, not their target branch).

**Comment by MartinNowak** [comment]
As per http://forum.dlang.org/post/mmi1m9$1tq$1@digitalmars.com, waiting for @andralex to approve.

**Comment by andralex** [comment]
I see a mix of breaking changes (e.g. JsonOptions -> JSONOptions) and renames of new symbols, which are not breaking.

If JsonOptions is a breaking change, I am opposed to it. std.json is a low-quality package that needs wholesale replacement. Until then, breaking it repeatedly for cosmetic tweaks does only harm.

**Comment by CyberShadow** [comment]
JsonOptions is not a breaking change, it was added after 2.067.1.

**Comment by MartinNowak** [comment]
If that was the only criticism, then we might go on?

**Comment by MartinNowak** [comment]
Why wasn't `chainPath` renamed to `asPath`? That's the only couple in std.path where the `buildX` -> `asX` relation isn't used.

**Comment by CyberShadow** [comment]
Well, it wasn't proposed as a rename. But I think `chainPath` is a nice name, as it works just like `chain`. `asPath`, OTOH, is rather uninformative.

**Comment by MartinNowak** [comment]
> Well, it wasn't proposed as a rename. But I think chainPath is a nice name, as it works just like chain. asPath, OTOH, is rather uninformative.

You're right, I was tricked into consistency thinking, but it's only buildNormalizedPath that would fit the same pattern.

**Pull request merged**
