### PR TITLE
[std.regex] Even faster C-T regex

### PR DESCRIPTION
**Pull request by DmitryOlshansky**
By inlining a couple of functions on a critical path. This combines and builds on top of all other improvement pulls.

### CODE REVIEW

**Comment by DmitryOlshansky** [comment]
pic11

**Comment by 9il** [comment]
What compiler was used for benchmark? If this was DMD, please add the same with LDC

**Comment by DmitryOlshansky** [comment]
> What compiler was used for benchmark? If this was DMD, please add the same with LDC

Obviously this patch is specifically for DMD, LDC has no problems with inlining except for separate compilation issues.

What do you want LDC numbers for? To compare DMD and LDC?

**Comment by 9il** [comment]
> What do you want LDC numbers for? To compare DMD and LDC?

No. Just to know that this PR has not perfomance issues for LDC.

**Comment by 9il** [comment]
Auto-merge toggled on

**Comment by schveiguy** [comment]
Auto-merge toggled off

**Comment by schveiguy** [comment]
Reenable auto merge after fix for win64 build.

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Pull request merged**
