### PR TITLE
add documentation example for SList

### PR DESCRIPTION
**Pull request by greenify**
As a follow-up to #4038 (my confusion that SList isn't an InputRange).

Here's an example that might help newcomers to gain a better understanding of SList.

The documentation on containers is still pretty sparse, but let's go step by step ;-)

### CODE REVIEW

**Comment by JackStouffer** [comment]
Documentation examples should always be in `unittest` blocks. Otherwise the docs will stagnate if code changes.

**Comment by greenify** [comment]
@JackStouffer that makes totally sense ;-)
I updated all three PRs.

BTW I copied the "example template" with plain text examples from existing modules, so it make might sense to do a cleanup over old modules once ...

**Comment by BBasile** [comment]
You should take care not to waste too much time with std.containers improvment because it seems that the _big boss_ will propose soon or later a replacement (see for example https://forum.dlang.org/thread/n07rh8$dmb$1@digitalmars.com)

**Comment by burner** [comment]
LGTM

**Comment by burner** [comment]
Auto-merge toggled on

**Comment by greenify** [comment]
> You should take care not to waste too much time with std.containers improvment because it seems that the big boss will propose soon or later a replacement 

Thanks for the headsup, but for the time we have left on earth until god delivers us from our sins it will help other newcomers like myself ;-)

**Comment by BBasile** [comment]
I just mean that if one day the new containers come down to std.experimental you'll have a better playground. Like now with the allocators ;-)

**Comment by greenify** [comment]
> I just mean that if one day the new containers come down to std.experimental you'll have a better playground. Like now with the allocators ;-)

Understood and really looking forward :)

**Comment by BBasile** [comment]
@greenify You may look at expiremental ndslice since you like functional programming and have abilities with ranges, that's hot, new, and will have a direct impact on the quality. Std.container is not officially deprecated but almost.

**Pull request merged**
