### PR TITLE
Removed typo in std.concurrency, line 1196

### PR DESCRIPTION
**Pull request by Doado**
NB: Is the use of "analog" correct here? It sounds a bit odd to me.

### CODE REVIEW

**Comment by aG0aep6G** [comment]
Could you rebase so that we don't have four commits for one typo?

**Comment by quickfur** [comment]
Yes, please squash, then this is good to go.

**Comment by DmitryOlshansky** [comment]
> Yes, please squash, then this is good to go.

It rather should re-work this so that there is no merge commit, that needs at least reset --hard to some older commit then rebase.

**Comment by Doado** [comment]
Sorry, what went wrong? I had a problem with github yesterday.

**Comment by aG0aep6G** [comment]
> Sorry, what went wrong? I had a problem with github yesterday.

I don't know what exactly happened, but of the four commits in this pull request only the last one seems to actually do anything. It would be nice if we could get rid of the others.

If you're using the typical GitHub setup with origin and upstream remote branches, but you're not well-versed in git, here's a way to fix this: `git rebase --onto upstream/master master~1 master`
This takes the latest commit and re-applies it on top of upstream/master. The other commits between upstream/master and your local master are discarded.
Then `git push -f` to update the pull request.

**Comment by aG0aep6G** [comment]
I forgot the last step: leave a comment here when you're done. GitHub doesn't send notifications for pushed commits, so you have to ping the reviewers manually (or hope that someone notices it).

Looks good to me now.

**Comment by Doado** [comment]
Ok. I did what you recommended. I hope it's fine now.

**Comment by quickfur** [comment]
Auto-merge toggled on

**Pull request merged**
