### PR TITLE
make flags are automatically communicated to sub-make

### PR DESCRIPTION
**Pull request by MartinNowak**
- and it ought to be MAKEFLAGS=$(MAKEFLAGS) anyhow

### CODE REVIEW

**Comment by kuettler** [comment]
Yes, please.

**Comment by Safety0ff** [comment]
In that case it can be further simplified to:
```$(MAKE) -f $(MAKEFILE) unittest BUILD=$*```
Reasoning:
- ```OS``` detection is run unconditionally
- ```DMD``` should already be present in ```MAKEFLAGS```
- ```MODEL``` is either already in ```MAKEFLAGS``` otherwise we can re-detect it to simplify the command.

**Comment by MartinNowak** [comment]
No, `MAKEFLAGS` contains arguments to make itself, such as `-j`, `-w` or `-i`.
You can override any variable (`DMD`, `OS`, `MODEL`) by passing it as argument `MODEL=64`. Those need to be passed to sub-make.

**Comment by MartinNowak** [comment]
You're right, works as per https://www.gnu.org/software/make/manual/html_node/Options_002fRecursion.html.
The variable setting arguments are only visible during rule execution.

**Comment by MartinNowak** [comment]
Can I please merge this?

**Comment by JakobOvrum** [comment]
Auto-merge toggled on

**Comment by andralex** [comment]
@MartinNowak sorry, this is quite frustrating.

Could you explain what problem this is actually solving? Far as I can tell it's just creating one again. In comments in https://github.com/D-Programming-Language/phobos/pull/2946 I have explained at length, with experiments and command output, that on OSX `make` does not work the way you think it does. I assume you saw the related comments in https://github.com/D-Programming-Language/phobos/pull/2946?

It's not a matter of opinion. Let me redo the experiment here. So we're on OSX. With HEAD, if I run

    make unittest -j8

it spawns:

    /Library/Developer/CommandLineTools/usr/bin/make -f GNUmakefile unittest BUILD=debug
    /Library/Developer/CommandLineTools/usr/bin/make -f GNUmakefile unittest BUILD=release

Notice that there are two processes spawned, each with an implied `-j1`. So now I get to use 2 out of the machine's 8 cores.

Also notice that on OSX the parameters `MODEL`, `OS`, `DMD` are NOT automatically forwarded, as you and others INCORRECTLY claimed SEVERAL TIMES.

If add `$(MAKEFLAGS)` pull, I get:

    /Library/Developer/CommandLineTools/usr/bin/make -f GNUmakefile  --jobserver-fds=4,5 -j unittest BUILD=debug
    /Library/Developer/CommandLineTools/usr/bin/make -f GNUmakefile  --jobserver-fds=4,5 -j unittest BUILD=release

which nicely distributes the 8 cores to the two makefiles, see http://make.mad-scientist.net/papers/jobserver-implementation/.

Could we very nicely and seriously please focus on Good Work instead of this? This is wasting your time, my time, and reviewers' time to achieve a Net Negative. Thanks.

**Comment by Safety0ff** [comment]
> it spawns:
> ```/Library/Developer/CommandLineTools/usr/bin/make -f GNUmakefile unittest BUILD=debug```
> ```/Library/Developer/CommandLineTools/usr/bin/make -f GNUmakefile unittest BUILD=release```

 [Snip]
> Also notice that on OSX the parameters MODEL, OS, DMD are NOT automatically forwarded, as you and others INCORRECTLY claimed SEVERAL TIMES.

@andralex Are you considering what is passed via the environment?
The following reduced makefile:
```
MAKEFILE = $(firstword $(MAKEFILE_LIST))
.PHONY: all
all:
	@echo FOO is: $(FOO)
ifeq (,$(SUB))
	@echo Sub MAKEFLAGS should be: $(MAKEFLAGS) SUB=true
	$(MAKE) -f $(MAKEFILE) SUB=true
else
	@echo Sub MAKEFLAGS are: $(MAKEFLAGS)
endif
```
If invoked with: ```make -f posix.mak -j2 FOO=BAR```
Yields:
```
FOO is: BAR
Sub MAKEFLAGS should be: -j --jobserver-fds=3,4 -- FOO=BAR SUB=true
make -f posix.mak SUB=true
FOO is: BAR
Sub MAKEFLAGS are: w -j --jobserver-fds=3,4 -- SUB=true FOO=BAR
```
Does this reduced example yield something different on OSX?
I'm not trying to waste your time on this, just trying to resolve the disconnect.

**Comment by MartinNowak** [comment]
Don't want to waste your time @andralex, here is the rationale for the change, sorry for not having it reposted in this pull.
https://github.com/D-Programming-Language/phobos/pull/2946#discussion_r24944813
The way you pass MAKEFLAGS breaks my setup and is not how this variable is supposed to be used.

> Notice that there are two processes spawned, each with an implied -j1.

That's what you see, but the MAKEFLAGS are passed as env variable and a jobserver ensures that all running make instances consume a total of -j8 processes.
I'll retest make 3.8.1 on OSX (that's what you used last time), and will resubmit the pull.
https://developer.apple.com/library/mac/documentation/DeveloperTools/gnumake/make_5.html#SEC70

Testing doesn't run faster since the revert, btw.

https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=83506&dataid=575849
https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=83513&dataid=575919

**Comment by MartinNowak** [comment]
> Testing doesn't run faster since the revert, btw.
> 
> https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=83506&dataid=575849
> https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=83513&dataid=575919

Sorry, the macair doesn't run with parallel jobs, so there is no difference.
I'll do the testing on OSX.

**Comment by MartinNowak** [comment]
Just tested on OSX, it works as expected.
Both versions run 8 instances of dmd, but your `$(MAKEFLAGS)` passing only works by chance and breaks my setup.

top_a
top_b

**Comment by MartinNowak** [comment]
It was actually worth looking at this a bit closer. Something abnormal is going on with the release build times for a few phobos modules.
It's probably a Wiedergänger of [Issue 7157 – Optimiser is O(n^2) w.r.t. function length](https://issues.dlang.org/show_bug.cgi?id=7157).

```sh
time ../dmd/src/dmd -conf= -I../druntime/import  -w -dip25 -m64  -O -release -unittest -c -ofgenerated/osx/release/64/unittest/std/datetime.o -deps=generated/osx/release/64/unittest/std/datetime.deps.tmp std/datetime.d
      180.96 real       132.19 user        48.76 sys
time ../dmd/src/dmd -conf= -I../druntime/import  -w -dip25 -m64  -O -release -unittest -c -ofgenerated/osx/release/64/unittest/std/random.o -deps=generated/osx/release/64/unittest/std/random.deps.tmp std/random.d
       21.23 real        15.68 user         5.53 sys
time ../dmd/src/dmd -conf= -I../druntime/import  -w -dip25 -m64  -O -release -unittest -c -ofgenerated/osx/release/64/unittest/std/regex/internal/tests.o -deps=generated/osx/release/64/unittest/std/regex/internal/tests.deps.tmp std/regex/internal/tests.d
      250.31 real       184.75 user        65.55 sys
```

**Comment by andralex** [comment]
OK, thanks for the research! I don't have time to confirm this but I trust your results. FWIW there are two lingering questions:

1. Why does `$(MAKEFLAGS)` insert `--jobserver-fds=4,5 -j` on OSX but apparently nowhere else?

2. Why does the `$(MAKEFLAGS)` version work "only works by chance"? They should both work no problem.

A quick test on a cold build indicates a minimum of three 1:16 for `$(MAKEFLAGS)` and 1:20 for no `$(MAKEFLAGS)`. I think whatever the reason for the difference it's small enough, and definitely does not indicate the use of only 2 cores.

**Comment by MartinNowak** [comment]
> Why does the $(MAKEFLAGS) version work "only works by chance"? They should both work no problem.

Because `MAKEFLAGS` doesn't contain the pure arguments, e.g. `make -k` sets `MAKEFLAGS` to `k`, not `-k`. You could pass `MAKEFLAGS` like so `MAKEFLAGS=$(MAKEFLAGS)`, but it's better to leave the sub-make communication as is.

> Why does $(MAKEFLAGS) insert --jobserver-fds=4,5 -j on OSX but apparently nowhere else?

It's also done on linux.
https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=83490&dataid=575748
The weird thing is that `--jobserver-fds=4,5 -j` is passed as valid argument while something like `-k`, `-w` isn't. Because of that it appeared as working, but running `make -f posix.mak -k unittest` would have failed.

**Pull request merged**
