### PR TITLE
struct for URI representation fixes

### PR DESCRIPTION
**Pull request by anton-dutov**
New branch, changes to pull request #2257
1. Some methods removed.
2. Parsing algorithm changed from regexp to string slicing (by @s-ludwig)
3. proprety "auth" renamed to "userInfo"
4. Examples converted to documented unittests

### CODE REVIEW

**Comment by JakobOvrum** [comment]
ping @anton-dutov

**Comment by DmitryOlshansky** [comment]
@anton-dutov are you by any chance willing to revive this? Going to close it otherwise.

**Comment by anton-dutov** [comment]
Hello, i'll try to revive that, but need some suggestions about implementation.
URI includes URL representation and some schemas, which constructs unlike.
 
http://dlang.org/download
mailto:some@where.to?subject=hello
tel:+123456789
file:///tmp/1.text

Most common rules - some schemas (don't) contains double slash, and/or authority and path sections.
I can't define rules for all possible schemas, but i can define global AA which can register rules for schema build.


    struct URIOpt
    {
       bool  reqDSlash    = true;
       bool  reqAuthority;
    }
    private __gshared UrlOpt[string]   _urlOpts;

    void regURISchema(string names, URIOpt opt)
    {
        _urlOpts[name] = opt;
    }

    shared static this()
    {
        // Define common schemas
       regURISchema("ftp", URIOpt(true, true));
       regURISchema("ftps", URIOpt(true, true));
       regURISchema("http", URIOpt(true, true));
       regURISchema("https", URIOpt(true, true));
       regURISchema("file", URIOpt(true, false));
       regURISchema("mailto", URIOpt(false, true));
    }


Other ways? Ideas?

**Comment by DmitryOlshansky** [comment]
Looks sane though please no `__gshared` - use shared and explicit locking in regURISchema or immuatable and populate everthing inside of `shared static this`.

**Comment by JakobOvrum** [comment]
@anton-dutov, any plans on working on this? There are many suggested changes that remain unaddressed and although I have more suggested changes, I'm not sure if you're interested in continuing this.

As for variation between URI schemes;  why can't the same parser handle all variants?

**Comment by anton-dutov** [comment]
So, i'll try. On parsing step we can handle all variations, but when converting to string representation - different schemas, has different display format.

**Comment by anton-dutov** [comment]
At now we have two structs
- URI
- URIQuery
Where second struct has own key/val storage. 
Or better move storage to URI and URIQuery using as proxy to access them?

**Comment by rikkimax** [comment]
I've only recently been informed of this PR (I had no idea somebody even wanted to do this except myself).
I've been working on a URI abstraction for the purpose of retrieving information.
It does not handle encoding and it does use allocators.

Above this I have had the recommendation of adding punycode encoding and decoding, in case that information is useful to you @anton-dutov.

https://github.com/rikkimax/alphaPhobos/blob/master/source/std/experimental/uri.d#L50

**Comment by anton-dutov** [comment]
i'll contact you, to combine our ideas

**Pull request closed without merging**
