### PR TITLE
add checkwhitespace check for the auto-tester

### PR DESCRIPTION
**Pull request by rainers**
This should avoid files with trailing whitespace, tabs or CR to be merged.

### CODE REVIEW

**Comment by rainers** [comment]
@andralex As the author of the obdc code, could you please fix windows line endings and tabs in the etc.c.odbc package? I can add the changes here, but don't want to spoil the file history.

**Comment by rainers** [comment]
grrr, the grep version for the FreeBSD and OSX build servers seem not to support the -P option. I've tried numerous variations, but nothing seems to work in every environment, e.g.
```
grep -U -E $'([ \t]$|\r)' ...
```
works from the command line, but not when run from the makefile. Anyone with regex/bash/make-fu have an idea?

**Comment by yebblies** [comment]
There is an alternative that works on all the supported platforms - D.

**Comment by rainers** [comment]
I'm almost convinced ;-)
But running checkwhitespace from the dmd folder, I get
```
std.utf.UTFException@std\utf.d(1268): Invalid UTF-8 sequence (at index 1)
----------------
0x00412016
0x00411FAE
0x00411F27
0x004114E6
0x004020B0
0x004245AE
0x00424583
0x00424497
0x0041CA53
0x760B7C04 in BaseThreadInitThunk
0x77BBAD1F in RtlInitializeExceptionChain
0x77BBACEA in RtlInitializeExceptionChain
unix\make.exe: *** [checkwhitespace] Error 1
```
That doesn't really help...

**Comment by rainers** [comment]
It's in the changelo in the zlib folder, I've excluded it now.

**Comment by DmitryOlshansky** [comment]
All that's left is fixing line endings then ;)

**Comment by rainers** [comment]
Committed the removal of CR and tabs in the odbc modules. Please don't blame me for anything database related in there, I'm happy to have left that area 20 years ago...

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Pull request merged**
