### PR TITLE
remove Flag alias

### PR DESCRIPTION
**Pull request by 9il**

### CODE REVIEW

**Comment by andralex** [comment]
Nice, toggled. Please mind the build failure (looks like whitespace).

**Comment by 9il** [comment]
BTW, should be `Flag`, `Yes`, and `No` be imported publicly?

**Comment by andralex** [comment]
@9il not necessarily - the functions involving those may be not used or have popular defaults.

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by MetaLang** [comment]
Why is this a good change? It significantly complicates the method signature. Is this to conditionalize the import of Flag?

**Pull request merged**
