### PR TITLE
Fix issue 15807

### PR DESCRIPTION
**Pull request by dcarp**

### CODE REVIEW

**Comment by schveiguy** [comment]
LGTM. Pretty amazing this hasn't been caught before. Tons of unit tests in `Array!bool` use `insertBack`.

**Comment by dcarp** [comment]
@schveiguy: there are a lot of Array!bool unit tests, but none of these verified the elements above index 32. It took me a few debugging hours, till I found that the problem was not in my code, but in phobos >:(.

**Comment by schveiguy** [comment]
This is obvious enough, it doesn't need a second review.

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Comment by dcarp** [comment]
@schveiguy: Thanks Steve! Could you please also take a look at #4030 and #3972.

**Pull request merged**
