### PR TITLE
Refactor: remove pointless std.string.translateImplAscii()

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by schveiguy** [comment]
Yeah, seems pretty obvious that we don't need a function that is called once (effectively with the static if). LGTM

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
Just go ahead and merge not too controversial stuff @schveiguy.

**Comment by schveiguy** [comment]
Hah, careful with the license you give me ;)

**Pull request merged**
