### PR TITLE
isIdentical for float and double

### PR DESCRIPTION
**Pull request by 9il**

### CODE REVIEW

**Comment by andralex** [comment]
What's the difference from `is`?

**Comment by yebblies** [comment]
[Issue 3632](http://d.puremagic.com/issues/show_bug.cgi?id=3632) hasn't been fixed, so floating point `is` currently fowards to `==` and mis-compares NaN and +-0.

**Comment by yebblies** [comment]
The current failure should probably be fixed by templatizing `isIdentical` and converting the smaller type to the larger type if they don't match.

**Comment by andralex** [comment]
Guess the focus should go in the fix, not in adding a library artifact for working around it.

**Comment by 9il** [comment]
So isIdentical should be deprecated in the future?

**Comment by yebblies** [comment]
Only if Walter can be convinced that NaN payload should be tracked at compile time/mangled.

**Pull request closed without merging**
