### PR TITLE
Make std.traits.Select work for compile-time expressions

### PR DESCRIPTION
**Pull request by John-Colvin**

### CODE REVIEW

**Comment by JakobOvrum** [comment]
Patch contains trailing whitespace.

So I guess it's an alias vs enum thing? LGTM.

**Comment by John-Colvin** [comment]
Fixed. Yes, you can't `alias` an expression, but you can `Alias` the result it if it's ctfe-able.

It's a pity `Alias` isn't `public`.

**Comment by John-Colvin** [comment]
And now I know why `Alias` isn't public. Ugh. It can't tell the difference between a single element AliasSeq and a single argument.

**Comment by John-Colvin** [comment]
depends on https://github.com/D-Programming-Language/phobos/pull/3985

**Comment by John-Colvin** [comment]
I think this should be good to go now that https://github.com/D-Programming-Language/phobos/pull/3985 is merged.

**Comment by quickfur** [comment]
LGTM

**Comment by quickfur** [comment]
Auto-merge toggled on

**Pull request merged**
