### PR TITLE
Win32 COFF: fix std.process unittests

### PR DESCRIPTION
**Pull request by rainers**
use CRuntime_Microsoft instead of Win64.

### CODE REVIEW

**Comment by quickfur** [comment]
Does nobody care about Windows support?! It's been 4 days and not a single review...

Anyway, I'm not exactly qualified to review this either since I don't have a Windows dev environment, but the autotester has been green for a while now and I'm tempted to merge this if nobody else looks at it in the next few days.

**Comment by JakobOvrum** [comment]
I did look over this minutes after it was filed, but I have no experience with DMD/Win64. That said, I understand what it does: that line of code is specific to Microsoft's C runtime, both 32-bit and 64-bit, but DMD only supported the Microsoft runtime for 64-bit before COFF was implemented for 32-bit as well very recently by @rainers himself.

So, in theory, LGTM :)

**Comment by quickfur** [comment]
Should we just merge then? I'm not seeing the point of just letting this sit here and rot. It *is* just a 1-line change after all.

**Comment by JakobOvrum** [comment]
Auto-merge toggled on

**Comment by JakobOvrum** [comment]
@quickfur, agreed, thanks for paying attention :)

**Comment by yebblies** [comment]
> Does nobody care about Windows support?! It's been 4 days and not a single review...

@quickfur Most people don't care about win32 coff.  We really need an autotester for it.

**Pull request merged**
