### PR TITLE
Fix Issue 15823 - allow opIndex for const std.variant.Variant

### PR DESCRIPTION
**Pull request by MaksimZh**

### CODE REVIEW

**Comment by MaksimZh** [comment]
https://issues.dlang.org/show_bug.cgi?id=15823

**Comment by DmitryOlshansky** [comment]
LGTM

**Comment by DmitryOlshansky** [comment]
Please add Fix Issue 15823 in the commit title

**Comment by JackStouffer** [comment]
LGTM

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Pull request merged**
