### PR TITLE
Change taggedClassRef and taggedPointer so that the bitfield appear as a void* in the parent

### PR DESCRIPTION
**Pull request by deadalnix**
This is necessary because of type qualifier conversion rules (struct with and without pointes are differents) and the current implementation would be incompatible with a precise GC (that we don't have, but may at some point).

### CODE REVIEW

**Comment by DmitryOlshansky** [comment]
Makes sense

**Comment by deadalnix** [comment]
Ping ?

**Comment by schuetzm** [comment]
LGTM

**Comment by deadalnix** [comment]
As per @CyberShadow suggestion some more detail about the struct problem. Consider :

    struct S0 { int i; }
    const S0 s0;
    void foo(S0);
    foo(s0); // Alright ! S0 is a value type.
    
    struct S1 { void* p; }
    const S1 s1;
    void foo(S1); // Alright ! S0 is a value type.
    foo(s1); // Error : function foo(S1) is not callable using argument types (const(S1))

**Comment by schveiguy** [comment]
I admit to not having the patience to construct how this code works in my head, so I won't review it :) But can we have a unit test for the mentioned issue?

**Comment by deadalnix** [comment]
Added unit test

**Comment by schveiguy** [comment]
Thanks!

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Pull request merged**
