### PR TITLE
publically import empty too because users expect it

### PR DESCRIPTION
**Pull request by adamdruppe**
There's been a few forum threads about this and another question on irc just now so we might as well just follow user expectations.

### CODE REVIEW

**Comment by JackStouffer** [comment]
LGTM

**Comment by 9il** [comment]
LGTM

**Comment by jmdavis** [comment]
Wait, more selective imports? The fact that we're using any at all at the module level is broken.

So, while I can understand the motivation here, I'm not at all sure that it's a good idea - at least as long as selective imports are broken.

**Comment by adamdruppe** [comment]
Well, we should probably fix selective imports. Actually, I'm pretty sure I've seen patches for that before, maybe someone should just merge them.

But in the mean time, it'd be nice is we could fit user expectations a bit better and make this just work in the same pattern as other functions like `replace` which is imported on the very same line.

**Comment by jmdavis** [comment]
Well, of course, we should fix selective imports, but the main PR that fixes the import situation has been in limbo for quite a while, and it wasn't the first attempt: https://github.com/D-Programming-Language/dmd/pull/3407

Though now that I look at the bug again, the main bug with selective imports is that they're always public, and the imports in question here are intended to be public, so they're probably fine.

I can't say that I'm a fan of adding yet more public imports, but you pretty much need `empty` for string code anyway. In fact, if it weren't for the Unicode stuff, I'd strongly argue that object.d should contain the array range functions so that there were just always present, but that gets considerably messier thanks to the automatic decoding.

**Comment by adamdruppe** [comment]
On Sat, Jan 02, 2016 at 06:16:11PM -0800, Jonathan M Davis wrote:
> Though now that I look at the bug again, the main bug with selective imports is that they're always public, and the imports in question here are intended to be public, so they're probably fine.

Yeah. There's also a bit of an issue with the disambiguation being off, but I don't feel that's a blocker to using it.

> In fact, if it weren't for the Unicode stuff, I'd strongly argue that object.d should contain the array range functions so that there were just always present, but that gets considerably messier thanks to the automatic decoding.

Oh, I'd probably agree too.... and that bloody automatic decoding was such a mistake, I wish we could undo that.

**Comment by JackStouffer** [comment]
> in limbo

I think we should call a spade a spade here and say that the PR has been ready for a while but no one wants to review it.

**Comment by jmdavis** [comment]
> Oh, I'd probably agree too.... and that bloody automatic decoding was such a mistake, I wish we could undo that.

Sadly, I'm not sure that there's really any of the main devs at this point save for Andrei who think that it was a good idea (and many of us used to think that it was a good idea), but unless Andrei could somehow be convinced, it'll never change, and it would would be very difficult to do so in a way that isn't too disruptive anyway.

It would help considerably if we could make it so that all of the range-based functions work with both ranges of code units and ranges of code points in order to minimize how much code would actually have to change if we were to try and switch over. And I keep intending to work on that, but as with many things these days related to D, I have yet to find time for it, and no one else has been doing it AFAIK.

**Comment by jmdavis** [comment]
I wonder if we should at least put `empty` in object.d even if `front`, `popFront`, etc. aren't in there, since we practically treat it like a built-in even though it isn't, and it doesn't rely on the auto-decoding mess, unlike the others.

**Comment by andralex** [comment]
okay

**Comment by andralex** [comment]
Auto-merge toggled on

**Pull request merged**
