### PR TITLE
Range-ify std.string.chompPrefix

### PR DESCRIPTION
**Pull request by WalterBright**
http://dlang.org/phobos/std_string.html#.chompPrefix

unittests at 100%

### CODE REVIEW

**Comment by JakobOvrum** [comment]
The two functions changed have template constraints requiring `isRandomAccessRange!Range`, but the new implementations don't seem to require more than a bidirectional range and forward range, for `chomp` and `chompPrefix` respectively.

**Comment by WalterBright** [comment]
Yeah, you're right. Also fixed another problem I found with the constraints. `startsWith` and `endsWith` will autodecode the delimiter, sigh.

**Comment by JakobOvrum** [comment]
* `C2` makes no sense in the public interface now that `C1` is part of the implementation.
* The tests should test non-RA range inputs (`"hello world"c.byDchar` etc?)

Other than that, LGTM.

---------------------------------------

These two could be further generalized in the future to allow the delimiter to be a range as well.

---------------------------------------

I don't get the stance using `array` in unit tests instead of `equal`. Surely the last things our test suite needs are slower execution time and more memory use. Barring the import statement, using `equal` is even shorter code, although admittedly with an extra level of parentheses.

**Comment by kuettler** [comment]
In `chomp` the else block starts with the line
```
auto orig = str;
```
whereas in `chompPrefix` the line is
```
auto orig = str.save;
```
I guess `save` should be called in both cases.

**Comment by WalterBright** [comment]
> C2  makes no sense in the public interface now that  C1  is part of the implementation.

C2 is needed in the constraints.

> The tests should test non-RA range inputs ( "hello world"c.byDchar  etc?)

added.

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
> These two could be further generalized in the future to allow the delimiter to be a range as well.

Why wasn't that done right away?

**Pull request merged**
