### PR TITLE
fix Bucketizer.owns

### PR DESCRIPTION
**Pull request by japplegame**

### CODE REVIEW

**Comment by Hackerpilot** [comment]
What issues does this solve?

**Comment by japplegame** [comment]
Compilation fails if parent allocator has `owns` method.

**Comment by JackStouffer** [comment]
@japplegame So is it possible for a unit test to be made for this problem?

**Comment by japplegame** [comment]
@JackStouffer
Yes. I slightly updated Bucketizer unittest.

**Comment by Hackerpilot** [comment]
:white_check_mark:

**Comment by BBasile** [comment]
Why don't you take this one ? It's a bug fix and it's been green for a full month !

**Pull request merged**
