### PR TITLE
fixed issue 15596 - mention algorithm.mutation.stripXXX in std.string.stripXXX comments

### PR DESCRIPTION
**Pull request by BBasile**

### CODE REVIEW

**Comment by schuetzm** [comment]
It seems something in `XREF_PACK` is broken:
http://dtest.thecybershadow.net/artifact/website-f1fa75b46edfc3ec5685bf0764e09831ddfd0846-c28d139b8650130109f3546ffc30097c/web/phobos-prerelease/std_string.html#.strip

Hasn't there recently been introduced a generic REF-like macro?

**Comment by BBasile** [comment]
Not, XREF was not the issue. I have to add a horizontal bar before the first member of the arg of the macro, it failed even with REF (even if I use it now). The other day A.D.Ruppe explained me the thing [here](https://issues.dlang.org/show_bug.cgi?id=15683#c3). 

Anyway, after only **6** git fixup it's ok now.

**Comment by quickfur** [comment]
LGTM

**Comment by schuetzm** [comment]
LGTM

**Comment by BBasile** [comment]
note that it's only ddoc and it's not impacted by the malfunctionning machine in the auto tester network.

**Comment by quickfur** [comment]
Auto-merge toggled on

**Pull request merged**
