### PR TITLE
Rename AliasSeq to AliasList

### PR DESCRIPTION
**Pull request by JinShil**
See forum discussion: http://forum.dlang.org/post/mnhfhs$2b9o$1@digitalmars.com

### CODE REVIEW

**Comment by schuetzm** [comment]
Although I slightly prefer `AliasTuple`, I'm fine with this name.

**Comment by JinShil** [comment]
I'd be OK with `AliasTuple` too.  I guess I could make another pull request so folks have a choice.

**Comment by schuetzm** [comment]
And add another one for `AliasSplat` to make deadalnix happy :-P

**Comment by andralex** [comment]
That'd be a step backwards. I'll close it, please reopen if the decision goes that way - which is honestly unlikely; @WalterBright and myself are both con.

**Pull request closed without merging**
