### PR TITLE
break up unittest8

### PR DESCRIPTION
**Pull request by WalterBright**
unittest8 is causing dmd to run out of memory

### CODE REVIEW

**Comment by Hackerpilot** [comment]
Auto-merge toggled on

**Comment by Hackerpilot** [comment]
Here's the list of files that win-farm-1 is trying to compile in to unittest8.obj with this change:
```
etc\c\curl.d
etc\c\odbc\sql.d
etc\c\odbc\sqlext.d
etc\c\odbc\sqltypes.d
etc\c\odbc\sqlucode.d
etc\c\sqlite3.d
etc\c\zlib.d
std\c\fenv.d
std\c\locale.d
std\c\math.d
std\c\process.d
std\c\stdarg.d
std\c\stddef.d
std\c\stdio.d
std\c\stdlib.d
std\c\string.d
std\c\time.d
std\c\wcharh.d
std\c\windows\com.d
std\c\windows\stat.d
std\c\windows\windows.d
std\c\windows\winsock.d
std\experimental\typecons.d
std\internal\cstring.d
std\internal\digest\sha_SSSE3.d
std\internal\math\biguintcore.d
std\internal\math\biguintnoasm.d
std\internal\math\biguintx86.d
std\internal\math\errorfunction.d
std\internal\math\gammafunction.d
std\internal\processinit.d
std\internal\scopebuffer.d
std\internal\test\dummyrange.d
std\internal\unicode_comp.d
std\internal\unicode_decomp.d
std\internal\unicode_grapheme.d
std\internal\unicode_norm.d
std\internal\unicode_tables.d
std\internal\windows\advapi32.d
std\net\curl.d
std\net\isemail.d
std\regex\internal\backtracking.d
std\regex\internal\generator.d
std\regex\internal\ir.d
std\regex\internal\kickstart.d
std\regex\internal\parser.d
std\regex\internal\tests.d
std\regex\internal\thompson.d
std\regex\package.d
std\windows\charset.d
std\windows\iunknown.d
std\windows\registry.d
std\windows\syserror.d
```
This doesn't seem right.

**Comment by 9rnsr** [comment]
This is pointless because problem happens in win64 build.

**Comment by 9rnsr** [comment]
Auto-merge toggled off

**Comment by JackStouffer** [comment]
If there was ever a more concrete example of dmd using too much memory...

**Comment by 9rnsr** [comment]
#4173 is merged.

**Pull request closed without merging**
