### PR TITLE
fix attributes for synchronized (mtx)

### PR DESCRIPTION
**Pull request by MartinNowak**
- synchronized (mtx) is neither pure not const

- the compiler currently doesn't check attributes
  for synchronized statements

### CODE REVIEW

**Comment by MartinNowak** [comment]
[Issue 14251 – synchronized (mtx) doesn't check attributes (pure, const)](https://issues.dlang.org/show_bug.cgi?id=14251)

**Comment by burner** [comment]
LGTM

**Comment by burner** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
thx

**Pull request merged**
