### PR TITLE
Documentation fixes.

### PR DESCRIPTION
**Pull request by veelo**

### CODE REVIEW

**Comment by burner** [comment]
LGTM but can you rebase this commit to stable so it might make it into the next release

**Comment by veelo** [comment]
I'd love to, but how? I just used the "Improve this page" button and edited online on github. This is my first attempt at contributing documentation. So far it has been a smooth ride, but now I'm hitting the first speed-bump. I had hoped I wouldn't have to download anything.

**Comment by burner** [comment]
I think there is a way.

1. Close this PR
2. Goto the phobos github main site
3. Change branch to stable
4. Do what you did with this PR
5. Be happy

**Comment by veelo** [comment]
I'll have a go.

**Pull request closed without merging**
