### PR TITLE
fix issue 15364 - BitArray.len should be private

### PR DESCRIPTION
**Pull request by Blumerline**

### CODE REVIEW

**Comment by JakobOvrum** [comment]
LGTM

**Comment by JackStouffer** [comment]
LGTM

**Comment by schveiguy** [comment]
These public members were all not documented, so it makes sense that we don't need to worry about breakage (e.g. `bitsPerSizeT` was harmlessly public)

**Comment by schveiguy** [comment]
whitelisted @Blumerline

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Comment by JackStouffer** [comment]
> whitelisted @Blumerline

Whitelisted for what?

**Comment by schveiguy** [comment]
> Whitelisted for what?

autotester.

**Comment by WalterBright** [comment]
Yeah, except they did break things :-(

**Comment by schveiguy** [comment]
Any broken code was using undocumented features that were not meant to be accessible. If read-only access is necessary, then we can add public accessors. But `ptr` and `len` should not be writable.

**Comment by MartinNowak** [comment]
We always need to worry about breakage, this was so unnecessary.
Nobody would have an issue w/ properly deprecating access to those fields, but just randomly breaking code b/c sth. should have been done different is unacceptable.
https://github.com/D-Programming-Language/phobos/pull/3950

**Comment by schveiguy** [comment]
No, changing len or ptr or both externally is neither supported nor could possibly be accepted as valid code.

Any code that broke because of this had a bug, and now the person would see the bug should be fixed. We did anyone who's code broke a favor.

This is like saying fixing a buffer overrun broke my code.

**Comment by Hackerpilot** [comment]
http://imgs.xkcd.com/comics/workflow.png

**Comment by MartinNowak** [comment]
> Any code that broke because of this had a bug, and now the person would see the bug should be fixed. We did anyone who's code broke a favor.

It certainly wasn't used incorrectly in undead, and every breakage we introduce requires library maintainers to release new versions and uses  to update their dependencies.
If we don't deprecate such changes properly we cause a lot of downstream work and devaluate existing D code. We should be more careful with our tiny ecosystem.

**Comment by schveiguy** [comment]
> It certainly wasn't used incorrectly in undead

Certainly it wasn't when it was part of Phobos. As a separate 3rd party library (and isn't this the entire purpose of this library, to maintain support with the current phobos?), it should not be accessing internals of Phobos implementation. So yes, it was used incorrectly (although now fixed).

We can agree to disagree on this. I don't think we should cater or support any 3rd party library that uses internal details of Phobos implementations. You can disagree with that, but I can't have any care or sympathy for those libraries, sorry.

**Comment by MartinNowak** [comment]
We don't disagree on the fact that internals should be internal, but I'm arguing against simply breaking things b/c someone made a mistake years ago. The cost of properly deprecating those fields is literally zero.

**Pull request merged**
