### PR TITLE
Faster heap operations

### PR DESCRIPTION
**Pull request by andralex**
I was surprised that building and sorting the heap call percolate which in turn has two stages - going up and going down. To the best of my knowledge, all you need to do to build a heap is to sift elements down (not up). @Xinok could you please comment?

### CODE REVIEW

**Comment by Xinok** [comment]
I'm afraid this is my handy work. This technique is used in [Bottom-Up Heap Sort](https://en.wikipedia.org/wiki/Heapsort#Bottom-up_heapsort) because it performs nearly half the number of comparisons on average. The upside is that it should be faster when comparisons are expensive but the downside is that it's less cache friendly because it always sifts down all the way to a leaf node before sifting up.

**Comment by tsbockman** [comment]
The algorithm could be selected at compile time - use the sift down method for basic types known to have fast comparison operators (integers, floating point, pointers, etc.), but keep the current two-stage method for `struct` and `class` instances, to minimize comparisons?

I don't know that it's worth maintaining the extra lines of code, though.

**Comment by andralex** [comment]
@Xinok OK, I figured there must be some depth to it. So the approach trades comparisons for swaps. What data types did you measure improvements on?

I figure percolate() is sensible when there's not a lot of percolation back up, i.e. when you're actually percolating the extremum. During heap building however, you're percolating an arbitrary element so it makes sense to just go with siftDown. So I kept percolate in heapSort and siftDown in buildHeap. Makes sense?

With this last commit I eliminated one test on the common path in both siftDown and percolate.

**Comment by Xinok** [comment]
@andralex I don't remember exactly but most likely an array of integers. However, the benchmarks were for completely sorting the array. Here are some new benchmarks for just **building the heap**:

~4 million integers.
Sift-Down: 45ms, 7890573 comparisons
Bottom-Up: 54ms, 6917412 comparisons

~1 million strings:
Sift-Down: 93ms, 1911297 comparisons
Bottom-Up: 101ms, 1676076 comparisons

For building the heap, the bottom-up method is slower and doesn't result in a significant reduction of comparisons, so I would say the sift-down method is better. But for sorting, what I said before still applies.

**Comment by andralex** [comment]
@Xinok Great, thanks! So this pull should be in good order.

**Comment by andralex** [comment]
this blocks https://github.com/D-Programming-Language/phobos/pull/3934

**Comment by 9il** [comment]
LGTM

**Comment by 9il** [comment]
Auto-merge toggled on

**Pull request merged**
