### PR TITLE
Merge remote-tracking branch 'upstream/stable' into merge_stable

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by andralex** [comment]
@burner yah, what @CyberShadow said.

**Comment by burner** [comment]
Ok, what does this mean for this PR?

**Comment by MartinNowak** [comment]
I fixed the merge conflict.

**Comment by MartinNowak** [comment]
Can we please merge this, don't want to rebase it again.

**Comment by burner** [comment]
LGTM

**Comment by burner** [comment]
Auto-merge toggled on

**Pull request merged**
