### PR TITLE
Remove std.typelist

### PR DESCRIPTION
**Pull request by Hackerpilot**
"Please use std.typecons instead. This module will be removed in March 2015."

I think it's time.

### CODE REVIEW

**Comment by schveiguy** [comment]
https://github.com/D-Programming-Language/phobos/pull/2541 is where it was "deprecated", that was less than a year ago, and after the release of 2.066.0. So the first time anyone has seen it being deprecated in a released version is March 2015. I think we should wait at least until after 2.068 to remove this.

**Comment by schveiguy** [comment]
Perhaps we need to fix our deprecation messages to not spit out a date and instead a version number.

**Comment by DmitryOlshansky** [comment]
Nobody uses it anyway, and it never was a part of build. I'd say just kill it.

**Comment by schveiguy** [comment]
Regardless, if we ship it, it's possible people use it. I think we still need to wait at least one release, then kill it.

**Pull request closed without merging**
