### PR TITLE
std.datetime: Update Windows time zones for KB3148851

### PR DESCRIPTION
**Pull request by CyberShadow**
This should fix the autotester.

https://support.microsoft.com/en-us/kb/3148851
http://forum.dlang.org/post/570E94F7.1040200@puremagic.com

### CODE REVIEW

**Comment by CyberShadow** [comment]
CC @jmdavis

**Comment by braddr** [comment]
Auto-merge toggled on

**Comment by braddr** [comment]
if it passes, it's an improvement over right now, so toggled auto-merge on.  If any cleanups are warranted, those can happen afterwards.

**Comment by braddr** [comment]
Also, will need to be cherry picked to the stable branch

**Comment by 9rnsr** [comment]
> Also, will need to be cherry picked to the stable branch

I opened #4197.

**Pull request merged**
