### PR TITLE
posix.mak: Add DELETE_ON_ERROR

### PR DESCRIPTION
**Pull request by CyberShadow**
Delete output files if the command fails.

### CODE REVIEW

**Comment by DmitryOlshansky** [comment]
Seems good, would this mean essentially a clean rebuild after each build error?

**Comment by CyberShadow** [comment]
No, only of the failed make rule.

**Comment by schuetzm** [comment]
LGTM

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Comment by CyberShadow** [comment]
Thanks, please also see:
https://github.com/D-Programming-Language/dlang.org/pull/1001
https://github.com/D-Programming-Language/druntime/pull/1292
https://github.com/D-Programming-Language/dmd/pull/4692

**Pull request merged**
