### PR TITLE
fix lookup of core.stdc.stdio.remove()

### PR DESCRIPTION
**Pull request by WalterBright**
Another fix needed for: https://github.com/D-Programming-Language/dmd/pull/5445

### CODE REVIEW

**Comment by ibuclaw** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
What does that have to do w/ local imports?
And it would be much nicer to use a static or selective import.

**Comment by MartinNowak** [comment]
Auto-merge toggled off

**Comment by andralex** [comment]
A local import would be nice.

**Comment by WalterBright** [comment]
> What does that have to do w/ local imports?

It's a bit subtle. std.stream was not importing core.stdc.stdio directly, it was picking it up from somewhere else that was using a local import. The change to the compiler no longer searches local imports from other scopes, such as base class's using local imports.

Although the language change is breaking code, arguably the ones I've been fixing should never have worked, and some were relying on a related bug in the compiler where the scope chains were being incorrectly built.

**Comment by WalterBright** [comment]
Ready for automerge.

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
thanks, @MartinNowak

**Pull request merged**
