### PR TITLE
Move along some of the deprecations.

### PR DESCRIPTION
**Pull request by jmdavis**
Some of these are a bit old, since I haven't been on top of this as I should have been, but we haven't been deprecating a lot these days, so the list isn't all that long.

### CODE REVIEW

**Comment by quickfur** [comment]
LGTM.

**Comment by jmdavis** [comment]
Oh, lovely. The dmd test suite has never been updated after `compressionMethod` was deprecated, so its removal (which is actually quite behind schedule - it should have been removed in January) breaks the dmd test suite. I'll undo the changes in std.zip for now to work around that problem.

**Comment by jmdavis** [comment]
Okay. I decided to just leave this PR alone and fix the test suite like it should have been fixed ages ago. So, as soon as that PR gets merged, this one should pass as well (assuming that there aren't any other problems with the test suite anyway - it's not working properly on my box right now, making it kind of hard to verify): https://github.com/D-Programming-Language/dmd/pull/4987

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Pull request merged**
