### PR TITLE
rename std.typetuple to std.meta

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
Rename detection and blame work with git offline, not sure why github fails to do this.

**Comment by WalterBright** [comment]
Wouldn't it be better to use `git mv` instead of rm and add? That would dramatically reduce the diffs.

**Comment by andralex** [comment]
@WalterBright interesting. @MartinNowak is it possible to mv a file and then add a new one with the same name in the same commit?

**Comment by WalterBright** [comment]
Even if it has to be done as two separate PRs, it is mucho better.

**Comment by MartinNowak** [comment]
> Wouldn't it be better to use git mv instead of rm and add?

That doesn't matter, git doesn't record file moves, it uses a heuristic to detect renames.
That heuristic works here, but github fails to correctly show that.

**Comment by Hackerpilot** [comment]
> That heuristic works here, but github fails to correctly show that.

For whatever it's worth Gitlab has the same issue.

**Comment by MartinNowak** [comment]
Ping

**Comment by andralex** [comment]
diff is hard to review side by side but fingers crossed...

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by JakobOvrum** [comment]
There's also #3264, which was merged even though @andralex appears to be arguing against it in [this comment](https://github.com/D-Programming-Language/phobos/pull/3128#issuecomment-99323753)...

I am confused.

**Comment by Hackerpilot** [comment]
:disappointed:

**Comment by John-Colvin** [comment]
Yeah this is totally confusing. I quote:

Me:
> > Tuple needs to be entirely erased (aliases for backwards compatibility excepted) from phobos unless it's referring to std.typecons.Tuple.

@andralex:
> I disagree. I don't see a problem acknowledging there are tuples of values and tuples of other things. By the same argument, "List" should be removed unless it refers to a list of values - wait a minute, this very diff has a MetaList!
> 
> Please stop.

And yet here we are, with *exactly* that.

**Comment by MartinNowak** [comment]
> Huh, so in the end you decided to with the change but with the inferior implementation and missing documentation update?

This was the minimal change set to get rid of TypeTuple, which was the main point of #3128.
Walter has explained pretty clearly why renames are costly and therefore proposed this reduced change.
https://github.com/D-Programming-Language/phobos/pull/3128#issuecomment-99588540

I know it's tempting to throw away one of the crappy modules and just rewrite it, but we need to become a lot more conservative with this kind of changes and only do things that really justify to ask everyone to change their code.

It's also a bit unfair to entangle someone in a highly dynamic discussion and then held him liable for everything he wrote, controversial discussions work a lot better without emotions.

**Comment by andralex** [comment]
We're making decisions on a case basis and at face value to the maximum extent possible. (These are both important because they caution against using one change as precedent justifying another.) @MartinNowak explained the background of this well. In the case of naming it's impossible to explain things 100%, or to please everyone. We replaced a really unhappy choice (`TypeTuple`) because it was a net liability for learning the language. Walter argued to replace a few others (`ParameterTuple` etc) - I didn't agree or disagree much with these. All work does not break backwards compatibility (including by means of deprecation).

Improvements to documentation are of course gladly received. And of course, adding new value on top of what we have is the best step forward. This particular discussion has run its course - at least I have no wits to add to it.

**Pull request merged**
