### PR TITLE
package-shared unittest functions should not be under version(unittest)

### PR DESCRIPTION
**Pull request by andralex**
Package-shared artifacts used only for unittesting should not be versioned with `version(unittest)` because that precludes unittesting one or more modules against the build library. Example:

    make std/experimental/logger.test

has link-time errors. This PR fixes them.

### CODE REVIEW

**Comment by andralex** [comment]
Incidentally there's a speedup too:

    make -j8 BUILD=debug unittest

takes 48 seconds on my laptop, whereas

    make -j8 BUILD=debug std.test

takes 45.

**Comment by andralex** [comment]
Also tried on a big iron at work with -j64, 24s with the old unittest target, 20s with the new one (debug mode).

**Comment by burner** [comment]
LGTM

**Comment by burner** [comment]
Auto-merge toggled on

**Comment by burner** [comment]
@andralex  https://github.com/D-Programming-Language/phobos/pull/3400

**Pull request merged**
