### PR TITLE
add std.traits.isAutodecodableString() to fix Issue 14765

### PR DESCRIPTION
**Pull request by WalterBright**
https://issues.dlang.org/show_bug.cgi?id=14765

### CODE REVIEW

**Comment by MartinNowak** [comment]
Thanks, can you please rebase and reopen this pull to target the stable branch.

**Comment by WalterBright** [comment]
I don't know how to do that. Help?

**Comment by schveiguy** [comment]
When generating pr in github, change the branch you want to merge into before submitting

**Comment by WalterBright** [comment]
why not just pull this and cherry-pick it into other branches?

**Comment by MartinNowak** [comment]
> why not just pull this and cherry-pick it into other branches?

Because cherry-picking causes lots of merge conflicts (git doesn't know that 2 commits are identical).

**Comment by MartinNowak** [comment]
> I don't know how to do that. Help?

First rebase the commits from your pull onto stable.

```sh
git fetch upstream
git checkout fix14765
git rebase --onto upstream/stable fix14765~1 fix14765
```

The create a new pull request using github's interface or the [git-hub](https://github.com/sociomantic/git-hub) plugin.
```sh
git hub pull new -b stable
```

**Comment by WalterBright** [comment]
Here's what happens:
```
mercury ~/forks/phobos> git status
On branch fix14765
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        makefile
        phobos.zip
        std/math.old
        std/range/package.new

nothing added to commit but untracked files present (use "git add" to track)
mercury ~/forks/phobos> git fetch upstream
remote: Counting objects: 205, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 205 (delta 64), reused 69 (delta 64), pack-reused 136
Receiving objects: 100% (205/205), 289.98 KiB | 0 bytes/s, done.
Resolving deltas: 100% (99/99), completed with 32 local objects.
From github.com:D-Programming-Language/phobos
 * [new branch]      2.063      -> origin/2.063
 * [new branch]      2.064      -> origin/2.064
 * [new branch]      2.065      -> origin/2.065
 * [new branch]      2.066      -> origin/2.066
 * [new branch]      2.067      -> origin/2.067
   7653b6a..3ea3ec6  phobos-1.x -> origin/phobos-1.x
 * [new branch]      revert-2652-move_winsock -> origin/revert-2652-move_winsock
 * [new branch]      revert-3285-exp -> origin/revert-3285-exp
 * [new branch]      stable     -> origin/stable
 * [new tag]         auto-tester-testing -> auto-tester-testing
 * [new tag]         v2.064     -> v2.064
 * [new tag]         v2.064.2   -> v2.064.2
 * [new tag]         v2.065-b1  -> v2.065-b1
 * [new tag]         v2.065-beta1 -> v2.065-beta1
 * [new tag]         v2.065.0   -> v2.065.0
 * [new tag]         v2.065.0-b2 -> v2.065.0-b2
 * [new tag]         v2.065.0-b3 -> v2.065.0-b3
 * [new tag]         v2.065.0-rc1 -> v2.065.0-rc1
 * [new tag]         v2.066.0   -> v2.066.0
 * [new tag]         v2.066.0-b1 -> v2.066.0-b1
 * [new tag]         v2.066.0-b2 -> v2.066.0-b2
 * [new tag]         v2.066.0-b3 -> v2.066.0-b3
 * [new tag]         v2.066.0-b4 -> v2.066.0-b4
 * [new tag]         v2.066.0-b5 -> v2.066.0-b5
 * [new tag]         v2.066.0-b6 -> v2.066.0-b6
 * [new tag]         v2.066.0-rc1 -> v2.066.0-rc1
 * [new tag]         v2.066.0-rc2 -> v2.066.0-rc2
 * [new tag]         v2.066.1   -> v2.066.1
 * [new tag]         v2.067.0   -> v2.067.0
 * [new tag]         v2.067.0-b1 -> v2.067.0-b1
 * [new tag]         v2.067.0-b2 -> v2.067.0-b2
 * [new tag]         v2.067.0-b3 -> v2.067.0-b3
 * [new tag]         v2.067.0-b4 -> v2.067.0-b4
 * [new tag]         v2.067.0-rc1 -> v2.067.0-rc1
 * [new tag]         v2.067.1   -> v2.067.1
 * [new tag]         v2.067.1-b1 -> v2.067.1-b1
 * [new tag]         v2.063     -> v2.063
 * [new tag]         v2.063.1   -> v2.063.1
 * [new tag]         v2.063.2   -> v2.063.2
 * [new tag]         v2.064beta3 -> v2.064beta3
 * [new tag]         v2.064beta4 -> v2.064beta4
 * [new tag]         v2.066.1-rc1 -> v2.066.1-rc1
 * [new tag]         v2.066.1-rc2 -> v2.066.1-rc2
 * [new tag]         v2.068.0-b1 -> v2.068.0-b1
mercury ~/forks/phobos> git rebase --onto upstream/stable fix14765~1 fix14765
fatal: Needed a single revision
Does not point to a valid commit: upstream/stable
mercury ~/forks/phobos>
```

**Comment by MartinNowak** [comment]
Huh, what's wrong with repo setup? Why would fetching from upstream update `origin/stable` instead?
Please post the output of `git remote -v`.
You can rebase onto any valid [gitrevisions](https://www.kernel.org/pub/software/scm/git/docs/gitrevisions.html), just make sure it's the last commit on the upstream stable branch (currently dmd@35d35f1).

```sh
git checkout fix14765
# get the latest commit from stable as FETCH_HEAD
git fetch https://github.com/D-Programming-Language/dmd stable
# rebase all commits between fix14765~1 and fix14765 onto FETCH_HEAD
git rebase --onto FETCH_HEAD fix14765~1 fix14765
```

**Comment by MartinNowak** [comment]
see #3512.

**Comment by WalterBright** [comment]
```
mercury ~/forks/phobos> git remote -v
origin  git@github.com:WalterBright/phobos.git (fetch)
origin  git@github.com:WalterBright/phobos.git (push)
upstream        git@github.com:D-Programming-Language/phobos (fetch)
upstream        git@github.com:D-Programming-Language/phobos (push)
```

**Pull request closed without merging**
