### PR TITLE
 Consolidate / clean up exception types used for OS exceptions

### PR DESCRIPTION
**Pull request by CyberShadow**
https://issues.dlang.org/show_bug.cgi?id=13620

### CODE REVIEW

**Comment by quickfur** [comment]
ping
It would be nice to get a resolution on this, as several PRs depend on it.

**Comment by CyberShadow** [comment]
Do we need consensus or can I just fix up the remaining issues myself and someone will merge?

**Comment by quickfur** [comment]
Well, I just wanted to get the discussion going again, I didn't participate too much in the discussion so I don't know if it's merge-ready, just that it's stopped for too long. :-P 

Dmitry did propose on the forum to support catching by interface, then it would address people's concerns about wanting to catch exceptions by meaningful types as opposed to implementation-specific types.

**Comment by CyberShadow** [comment]
I'm going to have to revisit this subject in more depth, then.

**Comment by andralex** [comment]
closing for now, @CyberShadow please reopen when you're on this

**Comment by CyberShadow** [comment]
I would appreciate if someone familiar with Phobos could take over this, currently I would prefer to spend time on improving dlang.org and the forum rather than debating exception hierarchies.

**Pull request closed without merging**
