### PR TITLE
Solaris: Add inline assembly version of poly().

### PR DESCRIPTION
**Pull request by redstar**
Uses the same code as FreeBSD.

### CODE REVIEW

**Comment by ibuclaw** [comment]
And Linux too. Perhaps this should be consolidated under a common version, but otherwise looks good.

**Comment by quickfur** [comment]
ping @redstar @ibuclaw 
Any updates on this? Are we ready to merge?

**Comment by ibuclaw** [comment]
This is fine. IASM duplication is not ideal but with no other alternative that shouldn't prevent this.

**Comment by quickfur** [comment]
Auto-merge toggled on

**Comment by quickfur** [comment]
Nobody objected so I'm going ahead.

**Pull request merged**
