### PR TITLE
Add warning about GC to taggedPointer and taggedClassRef docs

### PR DESCRIPTION
**Pull request by schuetzm**
http://forum.dlang.org/thread/ildhefvrvxxuphkfckcy@forum.dlang.org

### CODE REVIEW

**Comment by schuetzm** [comment]
Includes trivial typo fix in the same section.

**Comment by schveiguy** [comment]
I think this was a mistake. Pointer math is allowed, and pointer bitops with given preconditions are equivalent to pointer math.

I think we should revert this and fix the docs.

**Comment by schveiguy** [comment]
It's not equivalent to pointer arithmetic, but we do allow pointer arithmetic to get the same result:

```D
void *ptr = ptrToSomeInt;
ptr++;
```

This is allowed, and fundamentally must be. There is no difference here. In fact, the code could be reimplemented this way, and the result, as far as the GC cares, is the same. The GC docs are wrong IMO.

**Comment by schveiguy** [comment]
I'll ask this: if the pointer is stored as a `void *`, does this warning go away? I am not actually sure it isn't, I can't tell from the code, because it's so meta.

**Comment by deadalnix** [comment]
That doesn't make any sense. The code specifically checks so that this is safe to do (you can only tag pointer withing the alignment, meaning you can't get a pointer past the end of the object).

Can we fix the GC doc rather than making this needlessly scary to use ? The GC cannot work if it can't handle that to begin with.

**Pull request merged**
