### PR TITLE
Usage examples: isAggregateType, isBuiltinType.

### PR DESCRIPTION
**Pull request by rcorre**
I think it would be nice to have examples for `isAggregateType` and `isBuiltinType` as the documentation comments don't say much.

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
Unrelated to your pull:

What's interesting is that we seem to have a different definition of what an aggregate type is, e.g. compared to C++. Here's a [nice rundown](http://stackoverflow.com/a/4178176) for the C++ definition. For one thing arrays are also aggregate types in C++.

I wonder why we've made interfaces aggregate types, since they can't contain any fields.

**Comment by rcorre** [comment]
Interesting. Not only is an array an aggregate, but a class might not be (i.e. if it has no default ctor).
Based on that link, the c++ definition seems to exist to identify types that support array-style initialization, i.e:
```
MyClass c = {1, 2, 3}
```
Since we don't have that, I think our definitions make sense for D.

I'd assume interfaces are aggregates because the underlying type implementing that interface can only be a class (or a wrapped struct).

**Comment by jwhear** [comment]
LGTM.  A minor nitpick: elsewhere in Phobos (e.g. http://dlang.org/phobos-prerelease/std_algorithm_searching.html#all) a space is used to align the un-notted `!` cases to highlight the bang when it is there.  So
```d
static assert( isBuiltinType!(C[string]));
static assert(!isBuiltinType!C);
```

**Comment by rcorre** [comment]
@jwhear: good point. I've adjusted it for consistency.

**Comment by andralex** [comment]
thx

**Pull request merged**
