### PR TITLE
Fix property enforcements in `std.functional._ctfe*` functions.

### PR DESCRIPTION
**Pull request by denis-sh**

### CODE REVIEW

**Comment by andralex** [comment]
We should move away from this style. New coolness is to not add prefix parens.

**Comment by andralex** [comment]
Oops I meant "suffix parens". Thanks for attention to detail but what we need here is to finally fix property enforcement...

**Comment by denis-sh** [comment]
> Thanks for attention to detail but what we need here is to finally fix property enforcement...

Thanks. Could you provide an issue or DIP with this fix to see what coding style to follow?

**Comment by denis-sh** [comment]
> New coolness is to not add prefix parens.

Thus loosing the information if it's a function call or a property access, which isn't clear if it's used in expression. Could you please give some notes where is the discussion and reasons of such change?

**Comment by andralex** [comment]
It's pretty clear no trailing parens are the way forward. Keeping this pull request open won't help formalizing the process of fixing `@property`, `-property` etc. @denis-sh please close this. Thanks.

**Comment by andralex** [comment]
Fine. Please don't continue doing this though. Thanks.

**Comment by denis-sh** [comment]
> Fine. Please don't continue doing this though.

Sounds mutually exclusive for me...

**Pull request merged**
