### PR TITLE
Fix PHOBOSSRC broken links

### PR DESCRIPTION
**Pull request by dcarp**
Fix some DDOC PHOBOSSRC broken links.

### CODE REVIEW

**Comment by Hackerpilot** [comment]
:white_check_mark:

**Comment by andralex** [comment]
thx!

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by schveiguy** [comment]
I think the `_` should have been left in `_regex`, but I'm not sure, because I have to build the docs locally to figure out if it makes a difference.

We really need a way to look at these changes before pulling automatically.

**Pull request merged**
