### PR TITLE
[ndslice] fix issues 15714 and 15715

### PR DESCRIPTION
**Pull request by 9il**
https://github.com/DlangScience/mir/pull/13

### CODE REVIEW

**Comment by justanotheranonymoususer** [comment]
@dlang-bot what are the Fix checkboxes?
Sorry for asking here, I don't know of a better place to ask.

**Comment by 9il** [comment]
```
Test failed.  The logged output:
../src/dmd -conf= -m32 -Irunnable  -L-lstdc++  -odgenerated/runnable -ofgenerated/runnable/cppa_0 runnable/cppa.d generated/runnable/cppb.cpp.o
generated/runnable/cppa_0
core.exception.AssertError@runnable/cppa.d(252): Assertion failure
```
What wrong with DMD?

**Comment by quickfur** [comment]
@9il: autotester is green now.  @klickverbot  Anything else that needs to be addressed, or is this ready to merge?

**Comment by DmitryOlshansky** [comment]
I'd trust Ilya to understand his module issues

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Pull request merged**
