### PR TITLE
Remove unneeded .dup of arrays

### PR DESCRIPTION
**Pull request by mrkline**
See comments from #2974, specifically
https://github.com/D-Programming-Language/phobos/pull/2974#discussion_r24388654

### CODE REVIEW

**Comment by JakobOvrum** [comment]
Thanks! Although marginally, this reduces memory use when running the test suite, which is very welcome.

LGTM.

**Comment by schveiguy** [comment]
I'm assuming you searched for `).dup`, because there are cases where just `.dup` is used still.

e.g.: https://github.com/mrkline/phobos/blob/remove-unneeded-dups/std/getopt.d#L808

Can you search for all dups and remove if not necessary?

**Comment by mrkline** [comment]
You got it.

**Comment by schveiguy** [comment]
Found some more:
https://github.com/mrkline/phobos/blob/remove-unneeded-dups/std/getopt.d#L978
https://github.com/mrkline/phobos/blob/remove-unneeded-dups/std/getopt.d#L997
https://github.com/mrkline/phobos/blob/remove-unneeded-dups/std/getopt.d#L1011

**Comment by mrkline** [comment]
Thanks for double-checking. Sorry for missing those - I was about to leave for work and just did a quick grep.

**Comment by mrkline** [comment]
Let me know if you want me to rebase these into one commit before the merge.

**Comment by schveiguy** [comment]
> Let me know if you want me to rebase these into one commit before the merge.

Nope, that is fine.

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Comment by schveiguy** [comment]
Auto-merge toggled off

**Comment by schveiguy** [comment]
Just realized, you forgot the opening parens on those last 3 :) Fix that, and I'll re-enable the auto-merge.

**Comment by mrkline** [comment]
Damn it - the one time I push without running rdmd and I do something dumb. This is what happens when I commit before coffee.

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by andralex** [comment]
Thanks! Wonder how these unneeded `.dup` suffixes passed review...

**Comment by schveiguy** [comment]
@andralex Look at the referenced comments from #2974. Those have been there a LOOOOONG time :)

**Pull request merged**
