### PR TITLE
Revert "Prefer std.typecons.Flag over booleans for some Phobos argume…

### PR DESCRIPTION
**Pull request by andralex**
Reverts D-Programming-Language/phobos#3281

We can't keep on breaking our APIs for the sake of ever-so-slightly-better.

### CODE REVIEW

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
Auto-merge toggled off

**Comment by MartinNowak** [comment]
Please be a bit more constructive here we can at least keep the newly added overloads.

**Comment by andralex** [comment]
@MartinNowak: after the merged pull is reverted, work can proceed on adding overloads. Seems the normal protocol to follow. No?

**Comment by MartinNowak** [comment]
See #3290.

**Comment by andralex** [comment]
@MartinNowak ehm, fine. Can we please count you to not push such changes in the future? We can't afford to police the codebase. We need to make sure we're all on the same page and quite frankly I'm still stunned on how this got in.

**Comment by WalterBright** [comment]
No, I don't want the overloads, either. See explanation in the 3281 thread.

**Comment by MartinNowak** [comment]
> I'm still stunned on how this got in

Simply because this is how we handled Flag changes in the past, they we're deemed easy enough to just make them. I'm not aware of any recent policy change for deprecations, but as you've become extremely sensitive to this kind of changes, it might be the right time to write a small guideline for deprecations (maybe as a DIP).

**Pull request closed without merging**
