### PR TITLE
fix issue 14966: misuse of super

### PR DESCRIPTION
**Pull request by rainers**
casting `super` to non-const does not work when trying to call base class implementation of a function.

### CODE REVIEW

**Comment by Hackerpilot** [comment]
:white_check_mark:

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Comment by DmitryOlshansky** [comment]
@braddr What's up with Win32_64 machine?

**Comment by schveiguy** [comment]
@DmitryOlshansky I asked @braddr about this, it's just a really slow machine. Unfortunately, it's the only one that does 64-bit builds.

**Pull request merged**
