### PR TITLE
Documentation code samples for std.json

### PR DESCRIPTION
**Pull request by AndyColson**
Hope ya'll forgive the shout-out to perl

### CODE REVIEW

**Comment by quickfur** [comment]
Please make the code examples ddoc'd unittests instead of untested code in comments. Also, please stick to [Phobos style](http://dlang.org/dstyle.html) for all code examples.

**Comment by AndyColson** [comment]
>Please make the code examples ddoc'd unittests instead of untested code in comments.

I'm not sure what that means.  Does that mean add the example code as a unittest?  Or, in a ddoc block add unittest (but why? does it run?  even as commented out code?)  Is there a sample someplace I could see?

I'll fix the styling.

**Comment by AndyColson** [comment]
Was it just the if { } else { } ?  Is there other style problems?

**Comment by quickfur** [comment]
A ddoc'd unittest is a unittest preceded by a documentation comment, like so:
````
///
unittest
{
    someCodeHere();
}
````
When generating documentation, Ddoc will include the body of such unittests as code blocks inside the documentation generated for the preceding function. Any text you put in the documentation comment of the unittest will also get included as part of the generated docs, so you can put additional explanations there as well.

This feature makes it possible to use unittests as example code; they will actually be run as part of the unittesting feature, so you can rest assured that the example code in the generated docs actually compile and run, and are not just some artificial example that may or may not compile and/or run.

**Comment by quickfur** [comment]
The style looks OK now. You might want to keep the max line length at 80 characters or so... but this is a soft limit, not a hard limit, so it depends on your judgment. It's a good idea to do this in the code examples, though, since otherwise it might look ugly in the generated docs (overly long lines may spill out of the code boxes on dlang.org).

**Comment by andralex** [comment]
@quickfur leaving this to you - thanks both!

**Comment by quickfur** [comment]
For the first one, you can put it immediately after the module declaration and imports. It *should* still show up at the very top, unless something else went wrong. In any case, it's not a bad idea to include imports in code examples -- sometimes new users may not know what the right import lines should be, and it can be frustrating if you can't figure it out when it seems obvious to the person who wrote said code examples.

**Comment by quickfur** [comment]
The other code examples look good. Thanks!

**Comment by AndyColson** [comment]
I'm building the docs with:  DMD32 D Compiler v2.067-devel-227ca8d
Maybe that version doesnt work?

If I move the ddoc just below the module line, then it disappears.
If I move it below the import it shows up with the enum JSON_TYPE docs.

Want me to move it just below the module in hopes it shows up?

Or you want me to leave it?

**Comment by quickfur** [comment]
Hmph, you're right, it appears that module declarations don't support ddoc'd unittests. Alright. Let's leave it as-is at the top for now, and I'll file a bug and look into how to fix the compiler to support this. Sorry for making you do something that doesn't work.

**Comment by quickfur** [comment]
Auto-merge toggled on

**Pull request merged**
