### PR TITLE
add std.algorithm.sorting {ordered,strictlyOrdered} to std.algorithm booktable

### PR DESCRIPTION
**Pull request by greenify**
It seems like updating a package's booktable can be forgotten - even with peer review ;-)

### CODE REVIEW

**Comment by JackStouffer** [comment]
LGTM

**Comment by Hackerpilot** [comment]
Auto-merge toggled on

**Comment by andralex** [comment]
Why was this pulled before https://github.com/D-Programming-Language/phobos/pull/4110?

**Comment by greenify** [comment]
> Why was this pulled before #4110?

Because those functions are already part of Phobos, so I assume that it was just forgotten to add them to the overview page:

http://dlang.org/phobos/std_algorithm_sorting.html#ordered

**Comment by andralex** [comment]
When did that happen? So now we have isSorted, ordered, strictlyOrdered, and we want to add isStrictlyMonotonic?

**Comment by greenify** [comment]
> When did that happen?

Wasn't it you?

https://github.com/D-Programming-Language/phobos/commit/5ca24b8392b8ebab0588ce9a98782d5cdc795fff
and
https://github.com/D-Programming-Language/phobos/commit/d54047a6a06c457e1c57ce8e2805dadb8b16f014

> So now we have isSorted, ordered, strictlyOrdered, and we want to add isStrictlyMonotonic?

+1 for having just two functions,

**Comment by andralex** [comment]
Oh so `ordered` and `strictlyOrdered` are for individual values, not ranges. Thx.

**Pull request merged**
